### ISSUE TITLE
CSS Validator in 1.4.1 incorrectly says that "initial" is not a "margin-left" value. Ditto for "margin-right"

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1009]
**Describe the bug**
CSS Validator in 1.4.1-test6 incorrectly says that "initial" is not a "margin-left" value. Ditto for "margin-right" and even "color".

W3C says the CSS syntax for "margin-left" (and "margin-right") is:

    margin-left: length|auto|initial|inherit;

where the value "initial" sets this property to its default value.

W3C goes on to say about the keyword's definition and usage that:

    The **initial** keyword is used to set a CSS property to its default value.

    The **initial** keyword can be used for any CSS property, and on any HTML element.

**To Reproduce**
1. Open Guiguts
2. Paste the contents of the attached file which contains CSS and HTML
3. Run HTML->CSS Validator

**Expected behavior**
That its should not flag it as an error!

**Environment**
* Guiguts version:  1.4.1-test6
* OS and version: Windows 10
[CSS-bug-report.txt](https://github.com/DistributedProofreaders/guiguts/files/9638882/CSS-bug-report.txt)

* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by G4OEU** [comment]
As additional context, despite the CSS Validator flagging "initial" as not a left-margin value, it seems to be recognised by the HTML engine in the browser and resets the margins to their default values, cancelling the "5%" value set in the original definition for "blockquot".

**Comment by windymilla** [comment]
I think it's because you are validating to CSS 2.1
Use the Preferences menu to turn that off, and validate to CSS 3.
Then there are no errors. If you're happy with that, you can close this, or I can - thanks

**Comment by windymilla** [comment]
Also, I think for margins, you could possibly use "auto" to get the result you want (though I don't know that for definite)

**Comment by G4OEU** [comment]
Gosh, didn't think about the level I was validating to. A couple of
thoughts.

1. Could/should the error panel I saw make some reference to possibility
that errors are the result of validating to wrong CSS level?

2. What might break if the default in GG was set to validate against level
3.0? Am I correct in recalling that PG(?) only allows certain features of
3.0 to be used at present?

Will close the issue myself when I get back to the desktop m/c. Am replying
from phone.

Quentin

**Comment by windymilla** [comment]
The default CSS level is already set to CSS3. At some point perhaps you switched to 2.1 and copied the setting.rc file from that release to your current release. I think most people use the CSS3 validation these days - retaining the 2.1 option was mostly historical, so I don't think there's any need for special messages about errors possibly being related to the wrong CSS level. Almost all CSS errors I've seen are actually errors in both versions.
