### ISSUE TITLE
eBookMaker does not honour <!-- --> bracketing in HTML

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1014]
**Describe the bug**
When eBookMaker encounters  bracketing of text, instead of treating the bracketed text as a comment and ignoring it, the .epub file displays the text.

**To Reproduce**
1. Open Guiguts
2. Open the <blah> menu ...

**Expected behavior**
The bracketed text is not displayed in a browser so I expected it also not to be displayed by the files that eBookMaker outputs.

**Environment**
* Guiguts version: 
* OS and version: 
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
The HTML text in question was a series of HTML paragraphs that I had commented out while I re-implemented the content as a proper list. 

The same behaviour is observed if the text between the  lines is ordinary text.

The commented HTML would have been removed in the final version of the file. Although I do not normally leave comments in the HTML, if I did I would expect eBookMaker to ignore them.

**Comment by cpeel** [comment]
ebookmaker bugs should be filed under https://github.com/gutenbergtools/ebookmaker -- Guiguts merely bundles it.
