### ISSUE TITLE
Improve default CSS used for poetry

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#1035]
**Describe the solution you'd like**
Try this code in headerdefault.txt from @rtonsing 
```
.poetry-container {
      display: flex;
      justify-content: center;
}

.poetry {
    text-align: left;
}
```
May possibly want to check fallback position if browser/device doesn't recognise `flex`.
Also, may want to leave alternative in comments, similar to at present.

**Comment by windymilla** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

**Comment by rtonsing** [comment]
Note that Roger says that ebook did NOT have the poetry centered on Nook & Kobo. Maybe those readers just don't support display:flex. It would still be better than losing text, since it is basically doing what the existing x-ebookmaker override in the default header does.
