### ISSUE TITLE
Spell Query enhancements

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1071]
Since we're currently discussing Spell Query, these new options sometimes would be helpful (at least to me):

1. display in alphabetical sequence instead of in position sequence
2. display only lower-case words
3. display only upper-case words

**Comment by windymilla** [comment]
1. Not sure if the ordering is possible since SQ is using the common ErrorCheck dialog, but maybe
2. and 3. Do you mean all uppercase, or first letter uppercase, eg. book, Book, BOOK

**Comment by charliehoward4dp** [comment]
Option (1) would make it easy to see similarly-spelled variants
Options (2) and (3): first-letter, e.g., book or Book

These options should be toggles, of course..

Based on comments at Distributed Proofreaders, some people are accomplishing the purposes of these options by copying the Spell Query lists to external editors, but that's cumbersome and inefficient.

**Comment by charliehoward4dp** [comment]
The first option (list alphabetically) should be case-insensitive (book, Book, BOOK) listed together.

**Comment by charliehoward4dp** [comment]
Word Frequency's "Check Spelling" can display in alpha sequence and can ignore case, so it is a partial alternative to this request. However, it seems likely that using either SQ or SC afterwards still will be helpful, so implementing these requests will avoid doing two separate spelling passes.

That said, WF's "Check Spelling" is a good fallback.

**Comment by windymilla** [comment]
Maybe we could always show all words, but have a three-way toggle: 
1. line number order (current ordering)
2. alphabetical ignoring case (ALPHA, Alpha, alpha, BET, Bet, bet, ...)
3. alphabetical with case (ALPHA, Alpha, BET, Bet,... alpha, bet, ...)
Case 3 would cover the lower case only/upper case only situation - sorting would be strict alphabetical based on the ascii/unicode number for each letter. So all words beginning with capitals would come before all words beginning with lowercase. So you could quickly scroll up/down to the section of interest. I think it might work for what you want.

It also occurred to me that it would be virtually no cost to include the alphabetical sorting option for other tool checks if useful. I'll have a look at the kinds of messages they output and see if it might be good to include.

It's possible/probable this won't make it into 1.5.2, though

**Comment by charliehoward4dp** [comment]
Yes, that’ll work and even has some additional advantages.

**Comment by jj2017** [comment]
Sounds wonderful.
