### ISSUE TITLE
"Negative repeat count" error message

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1080]
When rewrapping the attached file, this message pops up:

`Negative repeat count does nothing at D:/Documents/DistrProof/PP/GG 1.5.2 test1/lib/Guiguts/SelectionMenu.pm line 129.`

[wrapbug.zip](https://github.com/DistributedProofreaders/guiguts/files/10505047/wrapbug.zip)

It doesn't happen if the long line 11 is pre-split.

**Comment by windymilla** [comment]
Oops - I put the check in for trying to insert a negative number of spaces into the right-align code, but not the center-align code.
