### ISSUE TITLE
Additional Quick Search feature

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#1088]
It could be helpful to have an alternative Search string live, e.g. when searching for the start of a block (or HTML element) and then wanting to do some S&R work in that block/element, then move on to the next one.

Options:
1. Text field in the status bar, with a ">" (better symbol, like magnifying glass) button (to the left of the field) to click for searching (or maybe "Enter" when focus is in the text field)
2. Mini popup dialog that would always stay on top (user could drag it over the bottom right of the status bar) containing a search field and minimal other buttons
3. Option in the existing S&R dialog (which now has stay-on-top functionality) to display an additional Search box - consider if it needs its own regex/case/word/start-at-beginning check boxes)

Features to consider:
1. Shift-click the search button for reverse
2. To reduce screen space used, right-click search button (or text field? clash with "paste") for options like regex/case/etc
3. Probably no search history (but maybe?)
4. If in status bar, might still want to "float" it to drag to somewhere on screen, then re-dock it
5. Crazy idea - if you float/tear-off from the one in the status bar, you get a new instance, so theoretically you could do that twice and have two more search boxes. 
6. Same idea, maybe slightly less crazy would be to do this in the "Option in existing S&R dialog" method - like add/remove "Multi" replacements, just have add/remove "Multi" search boxes.
7. Keyboard shortcuts for goto/pop quick search and repeat quick search

**Comment by charliehoward4dp** [comment]
I'd like to have Quick Search once we've thought more about it. Most of these possible features are interesting options. Having multiple instances of the full S&R dialog could cause problems, as their "History" lists might conflict with each other: which instance's History would wind up being preserved in Settings.rc under various "closing" scenarios?

**Comment by windymilla** [comment]
I agree. I was thinking multiple mini-quick search dialogs if we went in that direction. We could also decide not to save quick search history in the settings.rc, just for this run of the program - it's meant to be a "Lite" version :)
Multiple search boxes in the full S&R dialog could save their history, just as the current Multi replace boxes do.

**Comment by windymilla** [comment]
None of the options would be too hard to mock up a version good enough for trying out, so we can even try out several of those options.
