### ISSUE TITLE
Remove non-functional "enhancements" option from a HELP sub-menu

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#109]
"HELP>bugs and enhancements>suggest an enhancement" just goes to a DP Wiki page that says to use Github to suggest enhancements. That's a subset of the first option on that sub-menu, so the second option "suggest an enhancement" should be deleted and the first option should be promoted to the main Help menu, replacing "Bugs and Enhancements" (or delete the entire sub-menu and make "Bugs and Enhancements" go directly to GitHub).

**Comment by windymilla** [comment]
I agree that just one menu entry should suffice for bugs & enhancements. I think it should go to the wiki page because that gives other options to the user, such as asking/commenting in the forum if they are put off by the idea of entering a GitHub issue.
