### ISSUE TITLE
Right-clicking "H" on Status menu cannot be cancelled

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#110]
Right-clicking "**H**" on Status menu brings up a standard File Selection dialog, as it should. However, if you try to close that dialog without selecting a file, it just comes back, forever, until you select a file. This behavior is documented in the Guiguts 1.1 Manual, so if/when it is resolved, the manual should be updated.

**Comment by windymilla** [comment]
This is a duplicate of #79

**Comment by cpeel** [comment]
Closing as a dup.
