### ISSUE TITLE
One "R/" not recognized

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1110]
When the attached file is rewrapped using "Rewrap All", the "R/" at the bottom of page 48 is not recognized, so that closing tag, the [Illustration tag below it, and "Miss Cavell" are moved to the right during rewrap.  The other 149 occurrences of this tag seem to be processed correctly.  This happens with this instance of /R...R/ in all versions of Guiguts starting with 1.5.0.

I tried deleting text above or below it, and copy/pasting the apparently identical three lines from the bottom of page 14 to this location at the bottom of page 48, but none of those made any difference.

[rewrapbug.zip](https://github.com/DistributedProofreaders/guiguts/files/10798863/rewrapbug.zip)

**Comment by windymilla** [comment]
I'm proud/ashamed to say that I guessed the reason for this before even looking at the file.
Your Pg049 page marker is between the `R` and the `/` on line 1236.
I'm not sure how it ended up like that.

I also tried copying the 3 lines from the bottom of p14
```
/R
HILAIRE BELLOC
R/
```
pasting them in above the 3 lines at the end of p48, then deleting the 3 lines at the end of p48. 
That fixed the problem.
