### ISSUE TITLE
Bug in /RR/ rewrapping when right-most part of a line is past the right margin

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1133]
**Describe the bug**
The 'wrapping' of a line within /RR/ markers has no effect if the right-most part of the line is already past the right margin.

**To Reproduce**
1. Open Guiguts with 
[RR-rewrap-bug.txt](https://github.com/DistributedProofreaders/guiguts/files/10900559/RR-rewrap-bug.txt)
2. Ctrl+a to select the whole file. It has two /RR/ 'blocks', the first with end of line outside of right margin and the second with end of line within the right margin.
3. Ctrl+w to 'rewrap' selection.

**Expected behavior**
I would expect the 'rewrapping' to slide a block left until the longest line is at the right margin.

**Environment**
* Guiguts version: 1.5.3
* OS and version:  Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
Although I know it doesn't happen in your example, could you say what you would want to happen with 
```
/R
                                                                        A line that is beyond the right margin
followed by a line that is near/at the left margin
R/
```
The block cannot be moved left or right

Also, if you are permitting your example, you would also need to decide what to do with
```
/R
  A long, long line that starts near the left but continues to the right and goes beyond the right margin limit
R/
```

I'm not sure I will end up fixing this - it may just be documented in the manual - I'll have a look at the code when I get to it.

**Comment by windymilla** [comment]
Is that `/R[4]` markup equivalent to reducing the right margin by 4 just for that particular wrap?

**Comment by windymilla** [comment]
I guess it is for the text version, but not for the HTML, which needs some right padding on the end of the line

**Comment by charliehoward4dp** [comment]
I'll add a suggestion to the documentation that it's advisable to check every block after rewrap (and will explain why).  There's already a regex for this in that section of the documentation. I'll also add a simple regex that looks for lines longer than 72 characters. Those are two tests I've been doing routinely for a long time.

If anyone has further suggestions, please offer them.
