### ISSUE TITLE
Spurious characters appear and reproduce in the "bookauthor" field of the .bin file

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1134]
Please skip this original post and see the follow-up, which comes closer to identifying the source of the problem.  This original post may contain useful details to supplement the follow-up.

When run from Guiguts versions 1.5.3 or 1.5.2, EBM generates the following PG header at the very beginning of my current project. This does not occur with other projects.

```
*** START OF THE PROJECT GUTENBERG EBOOK THE LIFE SAVERS OF CAPE COD ***
Language: English
 Most recently updated: March 6, 2023
Release date: January 1, 0001 [EBook #5]
Creator: J.ÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚ÂƒÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚ÂƒÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚ÂƒÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚Â W. Dalton


Title: The Life Savers Of Cape Cod


This ebook is for the use of anyone anywhere in the United States and most other parts of the world at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this ebook or online at [www.gutenberg.org](https://www.gutenberg.org/). If you are not located in the United States, you’ll have to check the laws of the country where you are located before using this eBook.


The Project Gutenberg eBook of The Life Savers Of Cape Cod, by J.ÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚ÂƒÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚ÂƒÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚ÂƒÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â‚ÃƒÂƒÃ‚Â‚ÃƒÂ‚Ã‚Â W. Dalton
```

That repeating string is not in the html file. The only two occurrences of the author's name are:

```
<p class="large vspace wspace">BY<br>
<span class="large">J. W. DALTON<br>
<i>Sandwich, Massachusetts</i></span>
</p>

```
and

```
<p class="p4 center">
<span class="smcap">Copyright, 1902, by J. W. Dalton</span></p>
```

There are no hard spaces or other invisible characters between the J. and the W.

I tried deleting and changing various things, including replacing "J. W. DALTON" with "ALEXANDER B. DALTON", but EBM continued to use "J. W. DALTON" with the spurious characters each time it generated files.  I shut down the computer, unplugged it, pressed and held the power button to discharge the capacitors and presumably ensure nothing remained in memory, then powered back up and reran EBM. It still is using "J. W. DALTON" even though that does not occur in the test file.

The files are available on request.  I didn't attach them because there are 137 illustrations, and the resulting zip is about 32MB in size. Also, it isn't clear to me whether it's unique to my operating environment.

**Comment by windymilla** [comment]
Problem is that the .bin file is written out containing the non-breaking space in the author name. However, the way the bin file is read back in (by executing it as Perl source code) means it doesn't cope with the Unicode character - probably other non-ASCII characters in author names would go wrong too. The reason it hasn't happened before is that the author name was not previously stored in the bin file.
I think you can fix it without manual editing of the bin file by popping the Autogen dialog again, and editing the Author field to get rid of spurious characters and make sure any spaces are normal ones.
I will fix it in the next release

Note to self: needs something a bit like the saving of search/replace history strings in setting.rc:
`$index =~ s/([^A-Za-z0-9 ])/'\x{'.(sprintf "%x", ord $1).'}'/eg;`
Make sure you use double quotes when writing it out, so the `\x{nnn}` characters are interpreted
