### ISSUE TITLE
Update the spellcheck to use GNU Aspell 0.60.8 (Released October, 2019) 

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#115]
I would like to see the spellcheck configured to use GNU Aspell 0.60.8 (Released October, 2019) downloadable at http://aspell.net/.

This would enable spellchecking far more languages than are available under Aspell 0.5 such as Latin and Ancient Greek.

I understand we are looking for a free spell checker that supports many languages and UTF-8 but this is here and available.  It doesn't seem that it would be that big a stretch to change from Aspell 0.5 to 0.60.8.  Switching to a completely different spell checker seems like a huge undertaking.  Does such a free spell checker that supports Windows, Apple, and Linux even currently exist?  Does it already support as many languages as Aspell 0.60.8?

**Comment by cpeel** [comment]
We do not ship aspell with Guiguts -- that has always been a separate tool to install. If you install an updated version of aspell Guiguts will use it.

Moreover I do not see a downloadable Windows binary from their website. If you find one, please let us know.

**Comment by okrick** [comment]
Good points.  I've always thought it was Guiguts itself that did not support the revised Aspell.

**Comment by srjfoo** [comment]
The installation instructions for Macs point to installing aspell 6

**Comment by windymilla** [comment]
Not possible to progress this, since the latest version of Aspell available for each platform can be already used on that platform.
