### ISSUE TITLE
"Find Transliterations" is a search function

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#116]
"Find Transliterations" is currently under the Tools-->Character Tools-->Find Transliterations menu.  Since it opens the same Search & Replace window that is the first item in the Search menu the "Find Transliterations" should logically be on that menu.  I suggest making it the second item in that menu above the separator bar and below the "Search & Replace" selection.

The "old" menu correctly placed "Find Transliterations" in the "Search & Replace" menu.

**Comment by windymilla** [comment]
Since Character Tools contains the other options that deal with Greek Transliteration and UTF entry, and the Search Menu already has such a lot in, I think it's better to leave this tool where it is. It has been there for several years in the "new" menu layout.
