### ISSUE TITLE
Unusual error messages

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1167]
Two sets of error messages related to a [likely] bad spelling dictionary.

The attached zip contains the input file (t06-stealth.txt) to Spell Query, its .bin, the project's Good Words List, and a file I thought was an Italian dictionary for use by Spell Query.  That dictionary is not the one available at DP, and DP's Italian dictionary works fine.  The reason for filing this bug report is the possibility that the two errors described below might occur with legitimate text.

1. When t06-stealth.txt is being edited by GG and only the "en" dictionary is selected, Spell Query reports 66 possible errors (65 once the GWL is applied) and runs properly.  When the dictionaries "en it" are specified and the "it" dictionary is the one in the attached zip (renamed to "dict_it_user.txt" and kept in "GGPrefs"), as soon as SQ begins, an endless stream of alternating error messages appears:

```
utf8 "\xE0" does not map to Unicode at ErrorCheck.pm line 1636, <$fh> line nnnnn
utf8 "\xF2" does not map to Unicode at ErrorCheck.pm line 1636, <$fh> line nnnnn
```
'nnnnn' is a numeric value that keeps increasing. The only way to stop this endless stream is to kill the GG window.

2. Out of curiosity, I loaded that [invalid] dictionary as a text file into GG itself, intending to look for invalid characters by using "Character Counts".  When doing so, this error message appeared:

```
20:16:02: Guiguts 1.6-test1: If you have any problems, please include any error messages that appear here with your bug report.
20:27:57: Use of uninitialized value in sprintf at D:/Documents/DistrProof/PP/GG 1.6.0-test1/lib/Guiguts/WordFrequency.pm line 1272.
```

That error message is what prompted filing of this bug report.

Either or both parts of this report may be spurious or too unusual to justify investigation, much less correction.

[badcharacters.zip](https://github.com/DistributedProofreaders/guiguts/files/11013436/badcharacters.zip)

**Comment by windymilla** [comment]
1. The dictionary is ISO-8859 and the SQ code was assuming it was Unicode
2. Nothing to do with encoding - it's because the file contains no spaces!
Both fixable

**Comment by windymilla** [comment]
By the way - this also caused me to spot another bug with the default language not being set to English when you open a file that has no language set if you have previously had a language set on a file.
