### ISSUE TITLE
Guiguts auto-saved although that option is not set

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1173]
Version 1.6-test1: While running Word Frequency and having made some hyphenation-related corrections, when I clicked "Character Cnts", Guiguts saved the file, even though "Preferences>Backup>Enable Auto Save" is not checked.

I don't know which file(s) if any, to include with this report. Here are what I believe are the relevent settings in "setting.rc":

```
$autobackup               = '1';
$autosave                 = '0';
$autosaveinterval         = '5';
```

**Comment by windymilla** [comment]
Also happens with `Ital/Bold/SC`, `Check . lower` and `Check , Upper` buttons. 
Behavior unchanged since 1.0.25 or before - no idea why it was/is needed.
