### ISSUE TITLE
"Convert Fractions" produces an error message

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1177]
Guiguts Version 1.6.0-test2: The attached file contains four fractions  Two are -1/2 and two are -1/8.  When using `TOOLS>Convert Fractions>` and any of the three methods offered, this error message appears:

```
21:45:49: Tk::Error: bad text index "tempselend" at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .frame.linenumbertext.frame.textunicode
 (menu invoke)
```

The caption bar of the window indicates "edited" but none of the fractions were changed.

The error does NOT occur with 1.6.0-test1.  Running `install_cpan_modules.pl` indicates that everything already was up-to-date.

[fractionbug.zip](https://github.com/DistributedProofreaders/guiguts/files/11085616/fractionbug.zip)

**Comment by windymilla** [comment]
Sorry about that - bug introduced during "minor" fix to fraction conversions. It only fails if you don't select a region to convert. If you select the whole file (Ctrl+a), then use the tool, you don't get the error. Will be fixed shortly.
