### ISSUE TITLE
PPvimage logs warning if PNG file used for cover image

### ISSUE THREAD

**Issue by Hopkins1** [DistributedProofreaders/guiguts#1183]
The PPvimage provided with Guiguts 1.5.3 reports the following when a PNG file is used for a cover image (a 8 bit depth 32 color PNG in the case tested):

WARNING: epub cover should be jpg

The Post-Processing FAQ states:

...include a cover image in your images folder called cover.jpg (or, much more rarely, cover.png, if the image is [appropriate as a "png"](https://www.pgdp.net/wiki/JPG_vs_PNG))...

This warning is created in ppvimage.pl on line 671.

I believe this warning is invalid. At a minimum PNG and JPG should be OK (I think EPUB 3.2 also allows GIF and SVG+XML).

**Comment by windymilla** [comment]
I agree that it shouldn't complain, so I've fixed that. Note however that the vast majority of cover images are more appropriate in jpeg format.

**Comment by srjfoo** [comment]
> ... Note however that the vast majority of cover images are more appropriate in jpeg format.

For example, in testing the change, I converted a 450kB jpg to a png. If I stuck with png-8, the file came in at 1.9MB. If I went for best quality png-24, it came in at 4.5MB.

**Comment by Hopkins1** [comment]
The test example I was thinking about would be a user generated cover with title page text on a plain single-color background.

**Comment by srjfoo** [comment]
> The test example I was thinking about would be a user generated cover with title page text on a plain single-color background.

It depends entirely on what you're using as a source. If you're using an actual title page, take into account the amount of text and the variation in color of the background page if you're keeping the color of the page instead of taking the background to white. I think what @windymilla and I are trying to say is, don't assume without checking that the `png` image will be smaller than `jpg`. It may be, but it may not be.

**Comment by Hopkins1** [comment]
I wrote up the issue to point out that the verification tool did not match the requirements. No other agenda on my part should be assumed.
