### ISSUE TITLE
Right margin for right-alignment not working in 1.6-test2

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1192]
**Describe the bug**
Right margin for right-alignment is not working. If you have a right margin set, such as /R[2] ,the /R[2]...R/ markup does nothing when you rewrap.

**To Reproduce**
1. Open Guiguts with 
[right_margin_for_right-alignment.txt](https://github.com/DistributedProofreaders/guiguts/files/11312294/right_margin_for_right-alignment.txt)
2. Select the three lines
3. Ctrl+w  to rewrap the selection
4. See error; i.e. nothing happens.
5. Remove the right margin specification from /R[2] and repeat steps 2 & 3. The line now rewraps to the default right margin.

**Expected behavior**
I expect the block to slide right so that the right-most character is positioned two spaces from the default right margin.

**Environment**
* Guiguts version: 1.6-test2
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
I'm pretty sure that `/R` takes the position of the right margin, rather than the indent from the right, so the number you use is more likely to be `/R[64]` than `/R[2]`
I can't see an example of block-right with a margin in the manual anywhere, but I think that's the case.
