### ISSUE TITLE
PPHTML flagging almost everything (incorrectly) in GG 1.6.0-test3; OK with test2

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1202]
PPHTML flags almost everything (incorrectly) in GG 1.6.0-test3; OK with test2, test1, and 1.5.3. Happens with both of the files I tested; one is attached for testing.

[pphtmltest.zip](https://github.com/DistributedProofreaders/guiguts/files/11582817/pphtmltest.zip)

**Comment by windymilla** [comment]
Oops - I did make a "small" change. Worked for my test, but that's why I have you :)
Thanks
