### ISSUE TITLE
Explainable behaviour in 1.6-test3 but is it a bug?

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1205]
**Describe the bug**
A paragraph spans four 'pages'. There are three illos within the paragraph. Two are on the second page and the third illo is on the third page. The page markers are still present. 

Ctrl+Shift+click is used to move the first illo to the top of the para. It does so correctly by moving that illo to the first blank line it finds that is above the location of the illo. That is found at the start of the para on the page above.

Ctrl+Shift+click is used again to move the second illo to the top of the para. It also operates correctly and places that illo immediately below the first one moved. 

However when Ctrl+Shift+click is used to move the third illo (which is on the third 'page' of the para text) it of course looks for the first blank line above it and finds that blank line where the first two illos were moved from; that is on page two of the para text.

That wasn't what I was naively expecting to happen which was to have all three illos, immediately at the head of the para. However I can see why it has behaved that way.

Now when I Ctrl+Shift+click again on that third illo it finally moves to its correct position under the other two. But it has required an extra Ctrl+Shift+click to achieve the desired end.

**To Reproduce**
1. Open Guiguts with
[illustration-fixup-test.txt](https://github.com/DistributedProofreaders/guiguts/files/11602130/illustration-fixup-test.txt)
2. Open the Tools>Illustration Fixup menu.
3. Scroll down to line 697. The illo is labeled 'Fig. 5'. Ctrl+Shift+click to move it to the top of the para it is in.
4. Scroll down to line 699. The illo is labeled 'Fig. 6'. Ctrl+Shift+click to move it to the top of the para it is in.
5. Scroll down to line 719. The illo is labeled 'Fig. 7'. Ctrl+Shift+click to move it to the top of the para it is in.
6. See where it is moved to which is not the top of the para beneath Fig. 5 and Fig. 6.
7. Ctrl+Shift+click again to move it to the top of the para beneath the other two illos.

**Expected behavior**
If the assumption is always that the illos being moved are within a paragraph then when an illo is moved the blank line following the illo should deleted.

**Environment**
* Guiguts version: 1.6-test3
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
I don't think we can assume that the illos being moved are always within a paragraph and so the blank line following the illo should be deleted. For example, a PPer might want to move an illo to a better place closer to the relevant text, given the flexibility of it being in HTML rather than on a printed page. I'm happy for more discussion about it and to try some more examples - maybe in collaboration with @charliehoward4dp

**Comment by G4OEU** [comment]
Nigel,

I'm happy for there to be further discussion and examination of other
examples. However the way this new feature is described in CHANGE.md and
the actions it offers imply strongly that it is intended to move illos from
inside a paragraph and place them above or below the paragraph.

That is a common and necessary action and I welcome the new feature to help
do it.

But such a tool is not necessary simply to move aoccasional illos outside a
paragraph to a better place in the HTML. You could use existing cut&paste
tools to do that.

Whether left as-is or changed to remove the blank line after the illo, it
will require careful explanation in the manual so that users are clear
about the context it is to be used in and the possible side effects.

Quentin

**Comment by charliehoward4dp** [comment]
The reason I suggested this feature, and its companion for Sidenotes, is that some projects have dozens-to-hundreds of them, and moving them with cut-and-paste takes a long, tedious time, and is subject to multiple errors.  These features are not intended for use in projects that have just a handful of illustrations.

For example, in six of my recent/current projects, some of which are in SR and some just recently posted, these are the [Illustration] counts: 72, 28, 119, 106, and 59.  The one with only 28 illustrations also has 200 [Sidenotes], and just about all of them had to be moved, some more than once, based on topic.

It always has been my intention to document when to and when not to consider using these new features, as well as how to use them.
