### ISSUE TITLE
Search/replace error when TEXT contains a $ sign followed by a number

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#121]
This was previously reported at https://sourceforge.net/p/guiguts/bugs/135/ 
And similar at (https://sourceforge.net/p/guiguts/bugs/134/
Guiguts 1.1.0 also does this 100% of the time.
okrick
_______________________________________________________
`Search: <table((.|\n)+?)</table>`
`Replace: <div class="center"><div class="ilb">\n<table$1</table>\n</div></div>`

Text:
```
<hr />
<table class="p1" summary="Errors in the books">
  <tr>
    <td class="tdl">An overstatement of net income of</td>
    <td class="tdr">$2,721,068</td></tr>
  <tr>
    <td class="tdl">A mischarge of worn-out equipment to profit and loss of</td>
    <td class="tdr">2,843,596</td></tr>
</table>
<hr />
```
Result:
```
<div class="center"><div class="ilb">
<table class="p1" summary="Errors in the books">
  <tr>
    <td class="tdl">An overstatement of net income of</td>
    <td class="tdr">
,721,068</td></tr>
  <tr>
    <td class="tdl">A mischarge of worn-out equipment to profit and loss of</td>
    <td class="tdr">2,843,596</td></tr>
</table>
</div></div>
<hr />
```
The error occurs in the fourth line of the original text: `<td class="tdr">$2,721,068</td>` has been split into two lines and the "$2" at the beginning of the number '"$2,721,068" has been deleted.

The error is repeatable with the example given above, but does not occur every time there is a $ sign in a table: it only happens occasionally. The project in question has 169 cells containing $ signs, but only two were altered this way, and in the other affected table, it occurred in the fourth row, not in the first.
Discussion
<hr />

    Charlie Howard
    Charlie Howard - 2017-07-24

    Turns out the error occurs frequently, not just twice, and the missing information always seems to be "$2", whether followed by another digit or by a comma. But, it doesn't occur every time nor in every table.

**Comment by windymilla** [comment]
Edited to mark the code using backquotes so HTML tags don't get interpreted.
Note: look at the SourceForge bugs for details of other character strings being wrongly substituted (e.g. `\n` and `\t`). Looks like the text is being treated as a regex and regex special characters are not being escaped. Comment that it doesn't go wrong during Replace All is explained by the fact that this uses the internal Tk Text window function (for a simple whole-file Replace All).

**Comment by windymilla** [comment]
See also #308
