### ISSUE TITLE
Count button results in repeated errors when "Case Insensitive" is checked

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts#1218]
**Describe the bug**
In Search & Replace, if "Case Insensitive" is checked, clicking the Count button results in repeated error messages:
"08:07:38: Operation "subroutine entry" returns its argument for UTF-16 surrogate U+DF0D at C:/Strawberry/perl/site/lib/Tk.pm line 251."

Unchecked, it works fine.

**To Reproduce**
1. Open Guiguts
2. Open the Search & Replace menu ...
3. Type a word
4. Check "Case Insensitive" 
5. Click the Count button
6. See error

**Expected behavior**
Count shown without error

**Environment**
* Guiguts version: 1.5.3
* OS and version: Windows 11
* Perl version: v5.32.1
* Perl distribution: Strawberry

**Comment by windymilla** [comment]
Sorry @rtonsing - I'm unable to reproduce that in GG 1.5.3
Maybe it's a specific text file or something else that I am or am not doing?
Can you try it with a different file and see if it still goes wrong? Either way, please could you make a file that fails available for me to test out. Thanks

**Comment by rtonsing** [comment]
Weird, I saw it with 2 different files, but now I can't repro it. Sorry for the trouble.

**Comment by windymilla** [comment]
Well, it's obviously a bug, so if it turns up again, we'll investigate further - thanks for reporting it
