### ISSUE TITLE
Incorrect generation on superscript italic string

### ISSUE THREAD

**Issue by jandacpp** [DistributedProofreaders/guiguts#1225]
**Describe the bug**
A string such as
`^<i>a</i>`
gets generated as
`<sup><</sup>i>a</i>`

**To Reproduce**
I was unable to upload an example file, but insert this string into any text paragraph and generate...

**Expected behavior**
Should generate
`<sup><i>a</i></sup>`

**Environment**
* Guiguts version: 1.5.3 (probably in 1.0.25 etc as well)
* OS and version: Windows 10 and iMac Ventura
* Perl version: 
* Perl distribution: Strawberry

**Comment by windymilla** [comment]
I'm not sure that `^<i>a</i>` is valid. It's certainly not expected by Guiguts.

If there is more than one character that needs superscripting, the whole superscript must be enclosed in braces, i.e.  `^{<i>a</i>}` which works correctly when converted to HTML.

`^<i>a</i>`  is interpreted the same as `^{<}i>a</i>`

**Comment by rtonsing** [comment]
I agree, ref. https://www.pgdp.net/wiki/DP_Official_Documentation:Formatting/Formatting_Guidelines#Superscripts, although it doesn't specifically discuss markup within the superscript.

**Comment by jandacpp** [comment]
If you put { } round the string `^{<i>a</I>}` then GG generates correct code. But it is a single superscripted letter, a, albeit italicized, so {} is not required indeed should be omitted, per documentation. So the foofers did not put them in.

If you have `^abc` then GG generates valid code <sup>a</sup>bc. Probably not what the user intended, but valid.

With `^<i>a</I>` GG generates invalid code.

I have never seen an italicized anchor, until this current book 'Rules for Compositors and Readers' :-)
The page (085.png) is here:
https://www.pgdp.net/c/tools/page_browser.php?project=projectID605b5bbf96c74&imagefile=085.png&mode=image

This is a rare corner case for sure, but I think GG should not produce invalid code for the single-letter italicized (or bolded) situation.
But if you want to close the issue as 'invalid format' I will not comment further.  Maybe a note added to the official doc. to clarify that {} should be in place for this case would be useful for foofers.

**Comment by windymilla** [comment]
I think I have a safe fix for this - it will convert the following
```
^<i>a</i>

^<b>a</b>

^<sc>a</sc>

^{<i>a</i>}

^{<a}

^<sc>a</sc>

^A
```
to
```
<p><sup><i>a</i></sup></p>

<p><sup><b>a</b></sup></p>

<p><sup><span class="allsmcap">a</span></sup></p>

<p><sup><i>a</i></sup></p>

<p><sup>&lt;a</sup></p>

<p><sup><span class="allsmcap">a</span></sup></p>

<p><sup>A</sup></p>
```

**Comment by jandacpp** [comment]
With the new *.pm the basic cases now generate the expected code.
I did notice that the case ^ab which generated good code with the old routine, now generates: `(<sup><</sup>i>ab</i>)`

And the third and sixth items in the above conversion list seem identical.

**Comment by windymilla** [comment]
Thanks @jandacpp. I'll look into that. Is it just ^ab with no italic markup? Very strange.
Yes, I intended to add braces to the 6th example but forgot

**Comment by jandacpp** [comment]
My bad.
^ab generates ok as before.
I had input ^<I>ab</I> which does not gen ok--but is clearly invalid input.
