### ISSUE TITLE
Manual edit/replace action bug

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1247]
**Describe the bug**
When manually editing to replace the character `x` in the string `x/` by highlighting it then overtyping to replace it,  the behaviour is not as expected. The character `x` can be any character and the string `x/` may be anywhere on a line. I first encountered the problem when trying to manually replace the closing `*/` of a 'No rewrap' pair. The opening `/*` had been successfully manually changed to `/P` and I was trying to change the closing `*/` to `P/` by highlighting and overtyping the `*` with a `P`.

Note also that you get a different but incorrect behaviour when, instead of highlighting and overtyping the `*` in `*/`, you first delete the `*` then insert a `P`. As described above it doesn't matter which character (as far as I have tested) prefixes the `/` or where the pair of characters is located on a line.

**To Reproduce**
1. Open Guiguts
2. Open 
[manual-edit-bug.txt](https://github.com/DistributedProofreaders/guiguts/files/12561582/manual-edit-bug.txt)
3. Carry out the manual editing actions described above.
5. See error

**Expected behavior**
I expect the character that is overtyped to replace the highlighted character without altering any surrounding characters. Similarly when delete/insert sequence is used instead.

**Environment**
* Guiguts version:  1.6.0  with its original CharacterTools.pm file replaced by a later one you sent me to fix another bug.
*  OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
I will try the original CharacterTools.pm to see if the problem still occurs and will update this report

**Comment by G4OEU** [comment]
I have confirmed that the behaviours described in the bug report above are related to changes made in the updated CharacterTools.pm file you sent me on or about August 2. They are not present in the CharacterTools.pm included with 1.6.0.

**Comment by windymilla** [comment]
I must be doing something a bit different to what you describe, I think.
I open the file, select the `x` on line 5, and type `P`, and a `P` replaces the `x`
I've confirmed I'm using the updated CharacterTools file.

Just check that you are not doing this straight after an `undo` - there is a known undo bug that doesn't always do what you expect when you make the next edit, but I don't have any way to tackle that.

**Comment by G4OEU** [comment]
You did exactly as I did. Looks like I may have a problem with the keyboard or system on my desktop m/c?

I've just reverted to the updated CharacterTools.pm file, loaded the test file I sent you and repeated what you did and what I described and, at present, it is working as expected. 

I will continue to work with my updated 1.6.0 and see whether the problem reappears.

Thanks for looking into this.

**Comment by G4OEU** [comment]
What happened to all the '*/' and '/*' that I typed in my original message!?

I thought it might be an issue with my display/system but opening up the same URL on a Linux box shows me the same text with all the asterisks missing in those strings!

**Comment by G4OEU** [comment]
Ahhh! Just saw that when I clicked the 'Comment' button to enter the comment above, the two asterisks before/after the slashes have disappeared. 

Will swap keyboards and reboot to see if that fixes the problems.

**Comment by windymilla** [comment]
Could be that the markup language (markdown) is interpreting them. Use the code button to format them or back ticks  `` around them instead of straight quotes,  eg `/*`

**Comment by G4OEU** [comment]
Didn't think of that. Will give a try.

**Comment by G4OEU** [comment]
Trying `/*` and `*/`

**Comment by windymilla** [comment]
Good - you can edit your previous comments & original description, if you want to, via the 3-dot menu. Not that it matters, since it's mostly just you and me that are reading it at the moment, though no doubt my beloved reviewers will read it later :)

**Comment by windymilla** [comment]
Problem has not reappeared
