### ISSUE TITLE
Allow user to load bad_words.txt file in Spell Query

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#1252]
User can already load good_words.txt, and Spell Query will not report any of the words contained therein.
If bad_words.txt was also loaded, Spell Query could always report those words, even if they are in the dictionary, in case any bad words got through the rounds.

**Comment by windymilla** [comment]
Prompted by issue #1251

**Comment by charliehoward4dp** [comment]
Since I’ve always thought that spellcheck and presumably spell query both used bad words list, as well as good words list, yes, this would be a good feature to add.

**Comment by charliehoward4dp** [comment]
The bad words probably should be added after good words has cleared its words out of the spell query list. Also, the bad words in the Spell Query list perhaps should be marked with an asterisk at the end of each word, or some other character that will indicate that it is a bad word.
