### ISSUE TITLE
Enhance index page linking

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#1264]
Some books have entries "See xyz" in the index, which it would be good to link to the "xyz" entry in the index.

Suggested solution: add id to every top-level index entry just using the first word of the entry as the id. Detect the "See" keyword and add link to the id.

Consider whether it would be better to add this as a subsequent operation to be done, rather than incorporating it into the HTML conversion mechanism.

Also, multi-volume indexes tend to end up linking pages that they shouldn't, e.g. page 100 in the current volume should be linked in the normal way, but page 459 in another volume should either not be linked or should be linked to page 459 in a PG text. This one may be possible/easier/more flexibly done via regexes than a feature.

**Comment by charliehoward4dp** [comment]
While the concept of making “see” links easier to create is attractive, the proposed solution has some drawbacks: it will clutter up the HTML Markup’s list of internal links (as well as the index itself), and won’t satisfy the “see” references to secondary or tertiary entries. If implemented, generation of those id’s should either be controlled by an option on the HTML Generator dialog or the HTML Menu, and, if feasible, the internal links dialog should have a “show/hide” button for those id’s.
