### ISSUE TITLE
Tools menu sticky

### ISSUE THREAD

**Issue by noystergithub** [DistributedProofreaders/guiguts#1273]
**Describe the bug**
After selecting an option off the Tools menu, the menu stays on the screen.

**Expected behavior**
Tools menu should disappear, as the other menus do.

**Environment**
* Guiguts version: 6.0
* OS and version: Ubuntu 22.04
* Perl version: 5.34.0
* Perl distribution: 5.34-x86_64-linux-gnu

**Comment by windymilla** [comment]
Has it always done that? I've never seen it. The only way I know to make a menu stay on screen is to click the "tear-off" line at the top of the menu when you open it.

**Comment by noystergithub** [comment]
Nigel

No, I think this behaviour began since the change to v1.6.0. It's quite consistent.

What's happening is that the Tools menu on opening behaves as the other menus do when you click on the tear-off line: that is, it automatically opens as a separate movable box.

Neil

**Comment by windymilla** [comment]
Thanks Neil

The only thing I can see that I can possibly think is different in 1.6.0 to 1.5.3 is that the Tools menu has one extra entry in it, which makes it slightly longer of course. Is it almost filling your screen vertically and perhaps triggering some "clever" behaviour to try to fit it in, do you think?

A couple of things to test (not permanent fixes). 
1. You could try choosing a smaller font for the menus: Preferences->Appearance->Set Fonts..., then uncheck "Use System Default for Menu, Labels, Buttons, etc", which should unlock the "Menus, Labels, Buttons, etc." row of controls, and you should be able to click the arrows next to the font size to reduce it.
2.  An alternative would be to remove one or two entries from the menu by editing the source code, but I don't know (or don't recall) whether you would be comfortable doing that - don't do it if you're not confident - you could PM me and I could send you an edited file instead. If you are confident, then go to where you have 1.6.0 installed, then the `lib` subfolder, then the `Guiguts` subfolder of that, and edit `MenuStructure.pm`, and remove one or more entries removing from an open bracket to a close bracket with comma, e.g.
Lines 512-518:
```
        [
            'command',
            '~Illustration Fixup...',
            -command => sub {
                ::errorcheckpop_up( $textwindow, $top, 'Illustration Fixup' );
            }
        ],
```
Lines 502-508
```
        [
            'command',
            'Load Checkfile~...',
            -command => sub {
                ::errorcheckpop_up( $textwindow, $top, 'Load Checkfile' );
            }
        ],
```

**Comment by noystergithub** [comment]
Thank you Nigel, the first and simpler of your suggestions solves it. Reducing the font size for menus etc. (from 12 to 11) brings the bottom of the Tools menu clear of the bottom of the screen, and the menu no longer appears as a sticky movable box.

All the best
Neil

**Comment by windymilla** [comment]
Thanks Neil

Do you want me to look to see if I can make the menu shorter again, maybe by moving some entries into a sub-menu so you can go back to size 12 font? Or are you happy with having the size 11 font, in which case I'll close this issue.

**Comment by noystergithub** [comment]
Nigel

Thank you, I can manage fine with size 11. I may not be the only user affected, though. I tried pushing the font size up to 20 and the longer menus started behaving strangely - either not opening at all, or opening one of the sub-options at random. Reverting to size 11 all returned to normal.

Neil

**Comment by windymilla** [comment]
Thanks, Neil - I'll close this for now, bear in mind the length of menus a bit more, and make that a higher priority if it appears to affect others.
