### ISSUE TITLE
Numbered pages sometimes shown as "none" in "Lbl" field of status bar, .png numbers sometimes shown out of sequence

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1276]
This is reporting two closely related issues, probably also related to #1272.

FIRST ISSUE:
1. open the attached .html in GG, then go to Lbl 61 or thereabouts. The "Lbl" field in the Status Bar will show the number you chose, e.g., "61".
2. Scroll down, perhaps just by using the "Page Down" key. The Lbl number will go to 62, then probably to "None" if you happen to land on an illustration "No Count" page. That's correct.
3. Scroll down once more, and you will be on Page Label 63, but the "Lbl" field will show "none." If it does show 63, move the cursor down a line or two, and it'll show "none". In fact, it's still on 63.
4. Go to another part of the file, then type "63" in the "Lbl" field's text entry box and click "OK". It'll go to that page (confirming that it knows where the pages are). It may or may not show "63" in the Lbl field; if it does, move the cursor down a couple of lines and it will show "none" in the "Lbl" field, even though its still in page 63.

SECOND ISSUE:
Do the same things as listed above, but after step 1, right-click "Img" in the Status Bar to display the Adjust Page Markers Dialog and the inline yellow png numbers. Then do steps 2 and 3, watching those yellow numbers. After you see "Pg073", you will see "Pg075" and then "Pg074" (out of sequence).

P.S. This doesn't happen in the Plain Text version, at least, not in limited testing. "Pg074" is immediately to the left of "Pg075".

[pglabel bugs.zip](https://github.com/DistributedProofreaders/guiguts/files/13343131/pglabel.bugs.zip)

**Comment by windymilla** [comment]
I think this is explained by the page break locations which are set in the .bin file. Here is an extract:
```
 'Pg073' => {'offset' => '2990.22', 'label' => '', 'style' => '"', 'action' => 'No Count', 'base' => ''},
 'Pg074' => {'offset' => '3005.0', 'label' => '', 'style' => '"', 'action' => 'No Count', 'base' => ''},
 'Pg075' => {'offset' => '3002.18', 'label' => 'Pg 63', 'style' => '"', 'action' => '+1', 'base' => ''},
 'Pg076' => {'offset' => '3048.54', 'label' => 'Pg 64', 'style' => '"', 'action' => '+1', 'base' => ''},
```
As you can see, the offset for Pg074 is 3005.0 (i.e. line 3005) whereas the offset for Pg075 is 3002.18. So, GG is being told that Pg075 is before Pg074. This is also what you see, as you mentioned in the Second Issue. 
I don't know how those offsets came to be like that, but once they are like that, GG's behavior is "correct", I think. As far as GG is concerned, from line 3002 to 3005 is Pg075 (Pg 63), but from line 3005 to 3048 is Pg074 (No Count).
I manually edited the bin file to swap those offsets, and loaded the file afresh
```
 'Pg073' => {'offset' => '2990.22', 'label' => '', 'style' => '"', 'action' => 'No Count', 'base' => ''},
 'Pg074' => {'offset' => '3002.18', 'label' => '', 'style' => '"', 'action' => 'No Count', 'base' => ''},
 'Pg075' => {'offset' => '3005.0', 'label' => 'Pg 63', 'style' => '"', 'action' => '+1', 'base' => ''},
 'Pg076' => {'offset' => '3048.54', 'label' => 'Pg 64', 'style' => '"', 'action' => '+1', 'base' => ''},
```
The behavior then was completely normal.

So, it's possible there is a bug (or could be user error) that caused the offsets to be out of order like that, but I don't think it would be possible to track that now we're at this stage, so I suggest we close this issue, unless you are able to shed more light on the history.

**Comment by charliehoward4dp** [comment]
I’ve had this problem before, but don’t know how to find another example, so I’m closing the case. Thank you for looking at it.

**Comment by windymilla** [comment]
Thanks Charlie

**Comment by charliehoward4dp** [comment]
Attached is a set of files that demonstrate the problem described above, and that it occurs during HTML Generate. The issue is clearly seen in the Pg011-Pg016 range (hereafter just called "range").

**h01-pregen.html** is plain text, ready to be processed by HTML Generate. If you look at its .bin, you will see that the offsets, Pg numbers, and labels are correct (each one is either larger than or equal to its predecessor).

**h02-gen1.html** is the output of HTML Generator.  There are some syntax errors, which are due to the way I block-marked the text. The errors are unrelated to the problem and are fixed in **h02-gen2.html**.  If you look at the range in **h02-gen1.html.bin**, you will see that Pg015's offset is less than Pg014's. One of the consequences of that newly-created sequence error is that the page label for Pg015 is displayed as "none" instead of "Pg 13".

I don't know whether this is worth attempting to fix or should just be left alone. The only two things it affects (AFAIK) are what's displayed in the "Lbl" box ("none" instead of "Pg 13") and the use of `\IP` in a regex (the replacement value becomes "999999" instead of "13"). I may be the only person using it, and since I know about the issue, can easily correct it.

Apologies if I'm being overly picky.

[pagenuml-sequence-bug.zip](https://github.com/DistributedProofreaders/guiguts/files/13368791/pagenuml-sequence-bug.zip)

**Comment by windymilla** [comment]
Not too picky at all - thank you - I will definitely spend some time tracking that down, since it shouldn't happen. It's excellent to have the example files that demonstrate it - I really appreciate having them.
Also nice for you to know it's GG, not you, that breaks the offsets!
