### ISSUE TITLE
Remove obsolete entries from Page Marker dialog

### ISSUE THREAD

**Issue by mannyack** [DistributedProofreaders/guiguts#128]
In the manual discussing the "Adjust Page Markers" pop-up (not to be confused with "Set Page Markers" or "Configure Page Labels"), it says:

> The Renumber button and page offset field are made obsolete by the Page Label dialog discussed below.

Please remove those options from that pop-up.

**Comment by windymilla** [comment]
These controls do have a purpose - the manual has been updated.
