### ISSUE TITLE
Be more tolerant when adding good/bad words to file

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#1282]
If bad words doesn't exist, there is no error, but if bad words does exist and good words doesn't, there is.

Better to add good and/or bad words, and only give an error if neither are in the project folder.

**Comment by srjfoo** [comment]
Why an error instead of a warning, if neither is there?

**Comment by windymilla** [comment]
I meant a dialog that pops up to warn the user, rather than a printed error, so "warning" would be a better word.
