### ISSUE TITLE
Replace Latin-1 chart with charts for DP character suites

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#133]
**Describe the solution you'd like**
The Tools-->Character Tools-->Latin-1 Chart does not cover all the characters needed now that DP/PG use Unicode. Provide a chart for each (commonly-used?) [DP character suite](https://www.pgdp.net/c/tools/charsuites.php)

**Describe alternatives you've considered**
The Tools-->Character Tools-->UTF Character Entry and Character Search tools provide a way of entering characters, but not organised into DP character suites, i.e. what should be helpful for the project.

**Comment by windymilla** [comment]
After discussion with @srjfoo also need to consider characters that are commonly used by PPers but not by proofers. Examples are curly quotes, emdashes, endashes, etc. Also, what about non-breaking spaces or other non-printing characters?

**Comment by cpeel** [comment]
> The Tools-->Character Tools-->Latin-1 Chart does not cover all the characters needed now that DP/PG use Unicode. Provide a chart for each (commonly-used?) [DP character suite](https://www.pgdp.net/c/tools/charsuites.php)

It's also worth thinking broader than DP -- do folks at DPCanada use GG? What about other PG suppliers? If so, making the Unicode charts pgdp.net character suite specific might not be useful.

**Comment by windymilla** [comment]
Forum comments from [here](https://www.pgdp.net/phpBB3/viewtopic.php?f=13&t=70756&p=1212558#p1212416) onwards suggest a preferred solution would be to just change what is in the chart to cover characters commonly needed by PPers.

> 3) Put Latin-1 supplement block into the Unicode menu. Retain the special chart, but move away from calling it a Latin-1 chart, and call it something like a "Commonly used" chart. It would have the relevant characters from Latin-1 supplement, but also very common characters from other blocks, e.g. curly quotes, em-dash, en-dash, maybe fractions other than 1/2, 1/4, 3/4, etc.

**Comment by windymilla** [comment]
Also see #143

**Comment by windymilla** [comment]
Change buttons to labels as was done in #361 to reduce spacing

**Comment by windymilla** [comment]
Fixed by #371
