### ISSUE TITLE
Word Frequency Accents reports only works with Basic Latin accented letters

### ISSUE THREAD

**Issue by mannyack** [DistributedProofreaders/guiguts#136]
I would like the ability to configure the Accents report in Word Frequency to work with accents other than Basic Latin, for instance with EEL or other character suites. It would be important to be able to select more than one character suite at a time.

While this could be done by specifying individual letters, I think that by character suite would make more sense.

**Comment by windymilla** [comment]
See [here](https://www.pgdp.net/phpBB3/viewtopic.php?p=1216088#p1216088) for links to the EEL character suites.
