### ISSUE TITLE
In the "Spell Check in Multiple Languages" dialog, change "Save Debug Files"

### ISSUE THREAD

**Issue by mannyack** [DistributedProofreaders/guiguts#137]
The problem that I am trying to address is in the "Spell Check in Multiple Languages" dialog, there are several buttons that enable actions by the user to bring about the intent of the dialog, and mixed in with them is "Save Debug Files". This should not be in the user's face. If you want to keep it, I am not sure the best way to segregate it: Change it to right click on an unusual part of the dialog? Hit a function key? As it is now, it appears that the dialog is still under development.

**Comment by cpeel** [comment]
When opening bugs, please fill out the provided template. Most notably which version of GG.

This issue is found in GG 1.0.25 and later.
