### ISSUE TITLE
The ASCII Table Special Effects buttons are random

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#139]
The three rows of selections in the ASCII Table Special Effects window are randomly sorted every time the window is opened.

**To Reproduce**
1. Open Guiguts
2. Open the Text-->ASCII Table Effects menu ...
3. The top three rows of buttons are randomly sorted.

That the top three rows of buttons keep the same positions every time the window is opened.

**Environment**
* Guiguts version: 1.1.0-beta 1
* OS and version:  Windows 10 Home 1909
* Perl version: Strawberry Perl (64-bit) 5.30.2.1-64bit
* Perl distribution: 5.30.2

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17208131/88206924-e78d8080-cc03-11ea-9a4d-2b2017acfd93.PNG)
![Capture2](https://user-images.githubusercontent.com/17208131/88206925-e8261700-cc03-11ea-8d84-6a7eca890e7e.PNG)

**Comment by windymilla** [comment]
Also check: Jeebies dialog Tolerant, Normal, Paranoid radio buttons - they are also stored in a hash.

**Comment by okrick** [comment]
You are right. Jeebies is also random.
![Capture](https://user-images.githubusercontent.com/17208131/88436048-514e8b80-cdb8-11ea-9d1a-08657b106fea.PNG)
![Capture2](https://user-images.githubusercontent.com/17208131/88436050-51e72200-cdb8-11ea-80bd-c85e4575182d.PNG)
