### ISSUE TITLE
Search & Replace should work within a COLUMN selection

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#144]
When a column of characters is selected, S&R should work within that column.  Currently, nothing happens.

"Flood Fill" does work within a column selection.

I have a specific reason for thinking this could be useful: creating HTML tables where there are empty cells.  If the table has been aligned for Plain Text, then highlighting a column of character positions will select non-empty cells (with non-blanks in them) and empty cells (with blanks in them).  Then, a S&R that replaces a space with, say, an @, will result in there being no empty cells, and HTML Markup's Auto Table should be able to create a table with (almost) everything in the correct columns.

The word "column" has been used here in two different ways: the "Selection" for S&R (or Flood Fill) refers to a character-column on the editing screen, while a Table column refers to cells that are one below another.

A workable alternative in some cases is to find an empty character column (immediately to the left or right of non-blank text) and Flood Fill it with, say @, then use an S&R regex to replace @([^ ]) with "space"$1.  But that won't work when the data has ragged margins.

If this is implemented, "Search within column selection" (without necessarily doing a replace) also should work.

**Comment by windymilla** [comment]
Charlie agreed to close - no longer required.
