### ISSUE TITLE
HTML conversion in-progress and completion pop-up

### ISSUE THREAD

**Issue by mannyack** [DistributedProofreaders/guiguts#146]
I am entering this on behalf of Ramón(rpajares).

When HTML conversion starts, please pop-up a window that says that it is running. When HTML conversion completes, change the message in this window to say that it has completed, and then enable an ok button to close the popped-up window.

Anyway, that is what I understood Ramón to be asking for. From my point of view, the in-progress pop-up might be a good thing, but keeping it around after completion should be configurable, with the default being to close the window on completion.

**Comment by windymilla** [comment]
Since HTML conversion has a "busy" dialog that lists the stages in the process while conversion takes place and vanishes when it is complete (similarly to other long processes) I don't think this is necessary.
