### ISSUE TITLE
Speed up rewrapping by refreshing less often

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#153]
**Describe the solution you'd like**
Speed up the rewrap process by only updating the screen every 10 paragraphs instead of every paragraph. Preliminary test suggests 3x speed improvement (4.5 seconds to 1.5 seconds on small file, 90 to 30 seconds on large file)

**Describe alternatives you've considered**
Removing updates completely, which does cause a further speedup, but no feedback to the user that it is working

**Additional context**
Relevant function calls in selectrewrap are textwindow->see, textwindow->update, and ::update_indicators

**Comment by charliehoward4dp** [comment]
I've wanted to suggest this for years.  It's also something to consider for "Replace all", "Move Footnotes to Landing Zone", "AutoGenerate", and probably some other things.  One refresh/second is more than enough.

**Comment by windymilla** [comment]
Charlie's idea of once per second is better, and is more easily transferrable between different operations
