### ISSUE TITLE
Validate .bin file when saving; warn and/or try to repair if errors are detected

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#154]
This would be an enhancement that attempts to catch & maybe fix a bug.  On rare occasions, GG saves a .bin file in which some or all of the image and/or page label pointers have become incorrect or even lost.  If I knew how to re-create the problem, I'd provide the details of "how" it happens.

I've seen three kinds of errors over the years:

1. A stretch of image pointers all become identical, pointing to the same line/byte.  This may affect between a few and many dozens of consecutive pointers.  It's important to remember that a small number of consecutive pointers may legitimately point to the same place, when one or more consecutive [Blank Page]s have been deleted.

2. Image pointers may go out-of-sequence, such that, for example, 006.png appears before 005.png.  (I had this yesterday.)

3. A stretch of Page Labels may become incorrect or lost.   "Incorrect" probably is impossible to detect, but "lost" sometimes is easy.  Yesterday (when the image pointers went out of sequence), ALL of the Page Labels were lost.  If GG had an internal switch indicating there had been Page Labels, or better yet, a count of how many there were, then it could determine if just a couple were deleted (deliberately, probably) or were lost due to a bug.

I don't have any suggestions as to what to do about these problems if they are detected, other than warning the user about the condition and suggesting s/he IMMEDIATELY exit GG (after the file has been saved) and examine the most recent previous .bin files (the .bak files from the most recent SAVE and/or the .bin from the most recent Save As), and, if they are intact, try to use their contents.  (Which is how I recovered.)

No sample files are attached, but I do have them if you think they might do any good.  Unfortunately, I have no idea what I was doing when this happened.  Fortunately, it was caught (and corrected) soon after it occurred.

This occurred with GG 1.1.0 Beta 1, but with miscellaneous updates applied.  It occurred around the time I was testing an informal update involving Reflow.pm, but do not think that module could have been the cause of the problem.

**Comment by windymilla** [comment]
I'm going to close this in the hope that fixes to the page label code, the S&R code, and the Auto Table code will have fixed this issue.
