### ISSUE TITLE
Add Goodwords to Proj. Dic. non-functional in Linux

### ISSUE THREAD

**Issue by maputan** [DistributedProofreaders/guiguts#161]
This has been an issue for me since at least version 1.0.25.

Steps to reproduce:

On linux (I use archlinux):

Open a file to post-process, with a populated good_words.txt in the same directory.

Run Spellcheck. Select "Add Goodwords to Proj. Dic."

Get Warning about possible misspellings in the goodwords file. 

Say Yes.

Nothing happens. The same number of misspelled words is shown.

Close spellcheck, restart spellcheck, and again the same number of misspelled words is shown.

I use aspell version 0.60.8-2 rather than the old version which is said to be necessary for GG (in all other respects, 0.6 works fine). I'd rather not install an old version of aspell to test this.

**Comment by cpeel** [comment]
Please fill out the template provided with the requested information.

**Comment by windymilla** [comment]
I can't reproduce the same error on Windows, but please can you check the two following points to narrow down where the error is happening:

1. Maybe working in a clean directory with just text file and good_words.txt, but the main point is to make sure you don't have a project dictionary (called mybook.dic if your book is mybook.txt) in the folder when you start. Carry out your steps to reproduce above, then after attempting to add Goodwords, check if a file mybook.dic has been created. If so, does it have the good words in it? In fact, does it have any words in it? I'd be particularly interested if it has a truncated version of the words, e.g. the good word was "windymilla" but in your project dictionary it appears as "windymill". 
2. Check if any error messages appeared in your shell window during any of the test.

Thanks

**Comment by maputan** [comment]
> I can't reproduce the same error on Windows, but please can you check the two following points to narrow down where the error is happening:
> 
> 1. Maybe working in a clean directory with just text file and good_words.txt, but the main point is to make sure you don't have a project dictionary (called mybook.dic if your book is mybook.txt) in the folder when you start. Carry out your steps to reproduce above, then after attempting to add Goodwords, check if a file mybook.dic has been created. If so, does it have the good words in it? In fact, does it have any words in it? I'd be particularly interested if it has a truncated version of the words, e.g. the good word was "windymilla" but in your project dictionary it appears as "windymill".
> 2. Check if any error messages appeared in your shell window during any of the test.
> 
> Thanks

Yes, the project dictionary file is created. It seems to contain all the good words, and not truncated.

No error messages.

If there's a possibility this might be related to Aspell 6 versus 5, I can try installing the old version.

**Comment by windymilla** [comment]
Could you try another test before we resort to trying out Aspell 5, please.

Start afresh again, and instead of using Add Goodwords to add to the
dictionary, just start a Spellcheck, and when it finds a spelling error,
use "Add to Project Dic. <Ctrl+p>". Then exit, restart Guiguts and do spell
check again. If it finds the same error again, then that would imply the
project dictionary is not being used (properly).

If it turns out that there is a code change needed to support Aspell 6, I'm
happy to try it. It's only Windows users that are restricted to Aspell 5,
so I would like users on other platforms to be able to use Aspell 6.
Perhaps before you try using Aspell 5, you could post in the Guiguts help
forum to ask if anyone running on Linux is using Aspell 6, and if so,
whether their project dict seems to work.

Thanks

**Comment by maputan** [comment]
It doesn't find the same error again: adding a word to the project dictionary reduced the number of suspect words, and the lower number was again shown when rerunning spellcheck.

In the project dictionary, the word which I added manually (in this case "png") is shown slightly differently from those added by the "add goodwords" function:
```

'pilao
' => '',
'png' => '',
'que
' => '',
'qui
' => '',
'quitted
' => '',
'si
' => '', 
```

Excitingly, editing the dictionary manually to remove the line breaks after some of the goodwords:

```

'pilao
' => '',
'png' => '',
'que' => '',
'qui' => '',
'quitted
' => '',
'si
' => '', 
```

decreases the number of suspects shown on the next run of spellcheck.

Maybe this is related to Linux v. Windows line endings?

**Comment by windymilla** [comment]
Yes. That definitely makes sense. That's what I thought looking at the
code, which looks a bit shaky in its handling of line endings. If course
when I asked you previously to check if the good words had been added, you
didn't know the exact format you were expecting to see.

I should be able to do a fix for that, that will work on all platforms by
stripping the line endings properly.

Thanks for persevering and getting to the bottom of it. If you let me know
your DP name, I can arrange a patch for you to test out.

**Comment by maputan** [comment]
That would be great -- I'm Henry Flower on DP.
