### ISSUE TITLE
Local CSS Validator error messages give line numbers that are 11 too low

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#175]
Example: When there's a CSS error in line 70, the error report says it's in line 59.  Apparently, it isn't counting the heading lines above <style type="text/css">. 

I can supply a test file if needed, but think you can reproduce it yourself by introducing any error in the css of an existing file you already have.

**Comment by windymilla** [comment]
Yes - new version of CSS validator reports the line number within the style block rather than the file. Needs fixing.
