### ISSUE TITLE
Typing Greek from polytonic keyboard does not insert expected character

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#183]
**Describe the bug**
If a Greek keyboard is installed, then either character with tonos is inserted or a question mark

**To Reproduce**
1. Open Guiguts
2. Switch to Greek keyboard
3. Type "qa" which are the keys for alpha with oxia
4. A "?" appears
5. Switch to MS Word, type "qa" - alpha with oxia appears.
6. Copy paste the character from Word to GG - character appears correctly.

**Expected behavior**
When typing "qa", alpha with oxia should appear

**Environment**
* Guiguts version: all
* OS and version: Windows
* Perl : Strawberry Perl

**Additional context**
[Useful link with oxia/tonos discussion & code points](https://www.pgdp.net/wiki/DP_Code_-_Unicode/Greek)
[Typing Greek wiki page](https://www.pgdp.net/wiki/Typing_Greek)

**Comment by srjfoo** [comment]
Failure mode on a Mac is slightly different. With the Polytonic Greek keyboard enabled, pressing the dead keys for the marks entered the marks as a separate character preceding the character the mark should go over (which is how it's supposed to be done in this case): `῏α῍α῀α`αια`

Typed the same way in BBEdit, copied, and pasted into GG provided the correct results: `ἆἂᾶὰᾳ`

Typing Polytonic Greek on a Mac does not (except for a couple of marks) involve the option/alt key. It's not (or at least not completely) a dead-key issue. I switched to the US International - PC keyboard, which has a couple of permanent dead keys, and they worked fine in GG, so whatever's driving GG apparently just doesn't understand anything but the basic Greek characters -- I can enter the accented Greek letters that are available (i.e. not many) using the plain modern Greek keyboard on the Mac.

**Comment by windymilla** [comment]
Consider adding accented Greek characters to the new Compose Key repertoire
