### ISSUE TITLE
Paste /w Newline Edit Menu Command

### ISSUE THREAD

**Issue by tomcosnj** [DistributedProofreaders/guiguts#186]
### Paste /w newline [added command request]

As it is very useful to be able to paste in copies of text and also add a blank line after the insertion, I created code for an **Edit Menu** item **Paste w/ newline** Ctrl+Shift+v which allows the user to paste in copied text adding a blank line afterward. 

### Code added to MenuStructure.pm

After the Paste command in the subroutines **menubuildold** and **menubuilddefault**, add the following:

```
			[
				'command', 'Paste w/ newline',
				-command     => sub { ::paste_newline() },  ###   Paste w/ newline added
				-accelerator => 'Ctrl+Shift+v'
			],
```

### Code added to Utilities.pm

A. @EXPORT  between &paste and &textcopy

```
@EXPORT = qw(... &paste_newline ...)

```

B. code added after Paste sub

```
sub paste_newline {          ##   Paste with New Line added
	my $textwindow = $::textwindow;
        $textwindow->clipboardPaste;
        $textwindow->insert('insert', "\n");
}

```

**Comment by windymilla** [comment]
I don't feel adding this extra functionality is sufficiently beneficial to counter-balance the overhead of another menu options, manual entry, etc., especially given the additional complications to the paste process needed in recent versions to cope with Unicode text strings. Most other text editors to not have such a feature, and the user can just hit the Return key after pasting if they want a newline.
