### ISSUE TITLE
Bookloupe doesn't flag end-of-line period, followed by lower-case on next line, as a possible error

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#221]
Bookloupe doesn't flag end-of-line period, followed by lower-case on next line, as a possible error.  See attached file,  When that text is rewrapped such that the period is mid-line, BL does flag it.

[bookloupebug.zip](https://github.com/DistributedProofreaders/guiguts/files/5180366/bookloupebug.zip)

**Comment by windymilla** [comment]
This is true, but cannot be fixed within Guiguts. Bookloupe is an independent piece of software, matching the behaviour of gutcheck before it, and is not currently maintained by anyone at DP.
