### ISSUE TITLE
Non-ISO-8859 character 

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#226]
**Describe the solution you'd like**
Please remove the Non-ISO-8859 character check from Gutcheck.

**Describe alternatives you've considered**
This check is no longer required.  We have not been limited to Latin-1 characters in our files for years.

**Additional context**
DP went to a great deal of effort to upgrade our website to UTF-8. And PG prefers UTF-8 submissions.  We should not be identifying valid UTF-8 characters as errors.
![Gutcheck](https://user-images.githubusercontent.com/17208131/93234814-a01dff00-f731-11ea-9d22-e87d81663406.PNG)

**Comment by cpeel** [comment]
This is a message from either gutcheck or bookloupe, not from Guiguts itself. Which of those tools are you using?

**Comment by okrick** [comment]
I have no idea. The caption at the top of the GuiGuts window says "Bookloupe/Gutcheck".  And the menu does not say either.  All I did was press F6 when in Guiguts.

**Comment by windymilla** [comment]
1. One way to check which tool you are running is to open Preferences-->File Paths-->Set File Paths..., then look at the entry for Gutcheck/Bookloupe. Most likely if you haven't changed it, it will be set to bookloupe.
2. The reports from gutcheck/bookloupe are "queries", not "errors" as you can see in your screenshot where you it says there are 25 queries. I have often seen 1000s of queries, which were fortunately not all errors. It's basically saying, "is this OK?".
3. If you use the `GC View Options` button, you can turn off any queries you do not want to see.
4. Gutcheck (and I believe more recently bookloupe) are used by the WWers when they check files, so normally DP does not make changes to the way it works.
5. A person might still be interested in knowing they have some non-ISO-8859 characters, for example, if they thought they only used ISO-8859 characters, but inadvertently used the wrong type of quote when writing a transcriber's note - an error I see quite often when PPVing.
6. An alternative to your request would be to see if it is possible to turn some of the GC View Options "on" by default - they are currently all "off" (which means don't hide the error). What do you think of that idea?

**Comment by okrick** [comment]
You are correct.  It is BookLoupe.

And if this is used by others outside of DP then this request should be closed.

**Comment by windymilla** [comment]
What did you think of my suggestion at the end, which would only affect
PPers, not other users?

**Comment by okrick** [comment]
It would be fine to mention this in the GG manual.  I'm aware of those from when I actually used Gutcheck before Roger created the PP Workbench.  I don't use Guiguts anymore.  Today was unusual since I was looking for the character which was causing the W3C Validator to abend on this file I was reviewing in PPV and the PP Workbench was temporarily unavailable.

**Comment by windymilla** [comment]
Since okrick said to close this, and he doesn't use Guiguts any more, and a more flexible solution is suggested in #229, close this issue.
