### ISSUE TITLE
Error starting GG: unknown color name "SystemButtonFace"

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/guiguts#227]
**Describe the bug**
When trying to start guiguts I'm getting the following error:
```
unknown color name "SystemButtonFace" at /Users/cpeel/git/guiguts/src/lib/Guiguts/Preferences.pm line 368.
```
and Guiguts does not start. This line was changed in commit `3068561c` so presumably a regression, possibly due to being on a Mac?

**To Reproduce**
1. Open Guiguts
2. See error in console

**Environment**
* Guiguts version: git hash `a8b4a2c5d`
* OS and version: MacOS 10.15.5
* Perl version: 5.30.3
* Perl distribution: homebrew

**Comment by windymilla** [comment]
Can you run a previous version and see if you get the message when you do Preferences-->Backup-->Auto Save. You may need to turn it on, then off. Thanks
