### ISSUE TITLE
Directory name or File name with UTF-8 characters not found

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#292]
If there is a character other than Latin-1 characters in the file path then Guiguts returns a 'Could not find file. Perhaps it has been moved or deleted' error message.
A clear and concise description of what the bug is. Include any related error messages output on the command line.

**To Reproduce**
1. Open Guiguts
2. Open the File menu ...
3. Scroll down to Open...
4. Select the C:\Users\okric\Documents\DP\PP\phœbe\phœbe.txt file
5. See error message 'Could not find file. Perhaps it has been moved or deleted.'

Both the directory and the file names have to be changed to C:\Users\okric\Documents\DP\PP\phoebe\phoebe.txt in order for GG to open the file.

**Expected behavior**
I expect Guiguts to open phœbe.txt.

**Environment**
* Guiguts version: 1.1.1
* OS and version: Windows 10 Home 1909 18363.1139
* Perl version: Strawberry Perl (64-bit) 5.30.2.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.2.1-64bit

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/17208131/96053565-9a046680-0e34-11eb-8bd7-7a25c35a40cd.PNG)
![Capture2](https://user-images.githubusercontent.com/17208131/96053569-9e308400-0e34-11eb-868f-d69173470c28.PNG)

**Additional context**
I do not feel this should be a priority.  It should be fixed whenever this section of code is changed.

**Comment by windymilla** [comment]
There are wider issues regarding filenames with utf8 characters:
1. LIne that fails is `unless ( -e $name ) {`
2. It is possible to save a file with utf8 characters without an error, but it doesn't encode the name correctly
3. If a file with utf8 characters ends gets into the "Recent files" list, then there are errors trying write this to setting.rc
4. Do PG accept filenames with utf8 characters?
