### ISSUE TITLE
Fix the S&R bug for files with '$' sign characters in the file

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#308]
**Describe the bug**
If a regex search finds a text string with the "$" character the replace substitutes a carriage return for the "$" character and the digit immediately after.  

**To Reproduce**
1. Open Guiguts
2. Open the Search menu ...
3. Select 'Search & Replace...'
4. Enter '/\*((\n|.)+?)\*/' in the Search Text window. 
5. Click the Regex checkbox
6. Enter ".ta lr$1.ta-" in the Replace Text window.
7. Click the Search Submit.
8. A section of text is found that includes this line:
> 1  column, per issue, $3.00; per scholastic year, $20.00
9. Click the Replace submit.
10. Results include this line:
> 1  column, per issue, $3.00; per scholastic year, 
> 0.00

**Expected behavior**
I expected this line to be unchanged:
> 1  column, per issue, $3.00; per scholastic year, $20.00

**Environment**
* Guiguts version: 1.1.1
* OS and version: Windows 10 Home 1909 18363.1139
* Perl version: Strawberry
* Perl distribution: Strawberry Perl (64-bit) 5.30.2.1-64bit

**Screenshots**
![before](https://user-images.githubusercontent.com/17208131/96755388-82266880-1387-11eb-84bc-b703b4f6c275.PNG)
![after](https://user-images.githubusercontent.com/17208131/96755403-894d7680-1387-11eb-9efd-7860205eaee6.PNG)

**Additional context**
This file is 'The Trinity Archive (Vol. I, No. 4)' https://www.pgdp.net/c/project.php?id=projectID5eba7ebdb46c3 
This bug has always been present in GuiGuts.
Consequently, my first step in PP is to replace all '$' signs with '¤' and my last step is to replace all '¤' with '$'.
I'd like to save new PPs from the arduous process of discovering this bug.

My apologies if this is a duplicate.  I recalling submitting this twice previously but I could not find it searching the current list of bugs.

**Comment by windymilla** [comment]
You are right. It (or very similar) was reported at SourceForge (Bugs [134](https://sourceforge.net/p/guiguts/bugs/134/)  in 2016 and [135](https://sourceforge.net/p/guiguts/bugs/135/) in 2017) and here at GitHub last July as Issue #121.

I had already marked #121 as planned for [Release 1.2](https://github.com/DistributedProofreaders/guiguts/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+1.2%22) but I haven't fixed it, or even properly investigated it yet. The thought fills me with dread.
