### ISSUE TITLE
Generated illo code for figleft and figright on handhelds

### ISSUE THREAD

**Issue by jandac-2020** [DistributedProofreaders/guiguts#341]
The default choice for users doing 'Auto Illus Search' when they choose figleft or figright stays as "%", and generates code like: 
```
<div class="figleft illowp50" id="ip021" style="max-width: 16.8125em;">...</div>
```
This works on browsers and ADE but fails on KP (sometimes? always?), producing a large centered image.
Code generated by the "em" option for above illo: 
```
<div class="figleft illowe16_8125" id="ip021a">...</div>
```
works as expected on web, ADE, and KP.

So for figleft and figright the default option should  change to "em". (Users can override if they really really want to).
The manual for 1.1.1 does not mention figleft/figright but it might help users to do so.

Use this zip file in dropbox: https://www.dropbox.com/s/88a5zva0lhcyyuh/pcem-epub.zip?dl=0
to generate .epub and .mobi files and view the issue with the images.

This zip file is also (I think!) attached below
[pcem-epub.zip](https://github.com/DistributedProofreaders/guiguts/files/5532822/pcem-epub.zip)

* Guiguts version:  1.1.1
* OS and version: Windows 10
* Perl version: 
* Perl distribution: strawberry

**Comment by windymilla** [comment]
First, I don't think it's anything to do with figleft/figright. I think figcenter would behave just the same.

Looking at the HTML code in your example, it seems as though you had the `Override % with 100% in epub` box checked when you generated this. That means that the image will show at 100% width in epub formats. The idea of that setting is that for larger images at least, you don't want just e.g. 50% width in epub/kindle, but want the image to show as large as possible.
The situation is complicated by the fact that you also want to limit images to not display bigger than their "natural" size, i.e. the number of pixels they have or they appear blurry/pixellated. That is the purpose of the max-width styling. 

So in the case of your "right pc" image, you have set its width to 81% of the screen width (in a browser), and 100% of screen width in epub/kindle formats. However, the image is only 175 pixels wide (10.9375em), so it's display size won't exceed that in a browser or in epub. Unfortunately, KP does not support max-width, so the image is permitted to display at the size you requested (100% width) in KP.

The manual does say "This works well with [very] large original images, but if you have a small image, such as a logo or something that should occupy only a small part of the screen, click "em" to tell Image Geometry to use the actual width and height." I think this 175 pixel image counts as small, so the user should select "em" to avoid the effects you describe.
However, I don't think this is a bug.

Final point - I did spot and correct a slight error in the wording of when to use the `Override % with 100% in epub` option, which might be the reason you didn't uncheck it.

If you are happy with the above, we can close this, or feel free to give more details.

**Comment by jandac-2020** [comment]
ok, i can agree it is not a bug.

And I did not really understand the meaning and effect of the 'override' button; your modified manual wording helps there.

But I still feel that the manual wording does not lead the average PPer to make the right choices in some cases. (I do not want to say mislead to make the wrong choices.) 

Take the case of an illo with a 'landscape' geometry that has been sized to 400x274, and displays on the left side of the actual book taking about half the book width, so I want to get it figleft in epub/mobi with text flowing round it.

Using 'pc%' works ok with ADE, but not with KP (as expected I think).

So make it 'em'. It still works with ADE, and still does not work with KP. (it generates a width of 25em.)

But, if I change this width down to 15em on the dialog screen, then things work on ADE and KP, and I am a happy camper.

Maybe my illo width of 400 is too much, it should be kept down to 200 or so. That works.
But who knew 400 was too much? We are now encouraged to make our illos larger than in the past to get improved resolution on a variety of displays -- and it is implied if not stated that the generated code will take care of things.

Or, if we keep the 400 width, and go with "em" geometry, it still does not work on KP. Unless we override the 25em width in the dialog box eg with, say, 15em.

Mofified zip file to show this attached:
[pcem-epub.zip](https://github.com/DistributedProofreaders/guiguts/files/5537910/pcem-epub.zip)


Would the following adjustment to the manual wording be helpful in guiding the less experienced PPer to get to a successful epub/mobi outcome in all cases:

===================
Geometry defaults to scaling the image by percentage, filling in a suggested maximum width, and showing you the basis for the calculation. You can change this percentage to suit your project or preferences. This works well with [very] large original images, but if you have a small image, such as a logo or something that should occupy only a small part of the screen, click "em" to tell Image Geometry to use the actual width and height.
If you want the image to be floated on the left or right side of the page with text flowing around it, click "em" to tell Image Geometry to use the actual width and height.
You may have to reduce the actual width in the dialog box to ensure text flow around the image on some handheld devices. 

=====================

On a related point, the installed default header file does not include the @media code for floating images figleft and figright on handhelds. Would it be helpful to do so?

regards,
JohnC

**Comment by windymilla** [comment]
Hi John

In that latest file, you have set the width of the pc pictures to 100%, but you say you want it to only be 50% of the width so text can flow around it. To get that effect, you have to set the percentage width to 50%, which will generate you an illowp50 class. I manually tried that, and it behaves as I would expect. In ADE and KP, it just takes up 50% of the page width and the text flows around it. That should happen however big the natural size of your file, 200px, 400px or 2000px.

The ADE/KP difference is just that if you have a small natural size, e.g. 200, then the illow will take less than 50% of the width if that would mean showing it at bigger than 200px width. This would certainly be true on a browser, and will cut in at the appropriate point in ADE, but KP doesn't support it. But KP does support having images that are 50% width.

On the question of @media code for figleft and figright, [the best practices document](https://www.pgdp.net/wiki/DP_Official_Documentation:PP_and_PPV/DP_HTML_Best_Practices/Case_Studies/Images#Illustration_with_text_flowing_around_it) doesn't recommend doing what you have done to float the image on handheld devices. Instead it suggests just centering the image so a figleft would behave like a figcenter. Personally, I don't think there is any problem with what you have done, i.e. re-specifying the float. You are quite right that neither of those two options are included in the default header.txt file supplied with GG. I have added a separate issue (#342) for that, putting off the decision about which option to include (or possibly include one with the second one commented out, that the user can uncomment if they so wish)

Anyway, have a look at my first paragraph above to see whether you think that covers what you expect to happen or if there are still anomalies.

Nigel

**Comment by jandac-2020** [comment]
_In that latest file, you have set the width of the pc pictures to 100%, but you say you want it to only be 50% of the width so text can flow around it. To get that effect, you have to set the percentage width to 50%, which will generate you an illowp50 class. I manually tried that, and it behaves as I would expect. In ADE and KP, it just takes up 50% of the page width and the text flows around it. That should happen however big the natural size of your file, 200px, 400px or 2000px._

Well, I didn't set it to 100%, the generator did. And I accepted it without enough thought. I can see that overriding it to force the 50% result must be done in a case such as this. Just as with the "em" option, if the generated code offers a large value, say 25em, it must be overridden by a smaller value, say 15em, to obtain the desired result on web/ADE/KP.

Thanks, I have learned a bunch from this, and appreciate your taking the time to adjust my mindset.

btw, I purloined the @media figleft/right code from the NDQ forum a couple of years ago.

JohnC

**Comment by windymilla** [comment]
Problem resolved - manual edited, new issue added to cover handheld code.
