### ISSUE TITLE
Greek Transliteration dialog always opens at smallest possible window size

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/guiguts#362]
**Describe the bug**
The Greek Transliteration dialog always opens in the smallest possible window size that MacOS supports (the size of the 3-button window controls wide x resizing icon tall). The dialog can be resized bigger. The new size is retained when accessing the dialog during the same GG session, but is small again if GG is closed and reopened.

**To Reproduce**
1. Open Guiguts
2. Open Tools -> Character Tools -> Greek Transliteration
3. See the teeny-tiny dialog

**Expected behavior**
The dialog has a sensible initial size showing all the controls.

**Environment**
* Guiguts version: 53a7a4e4b
* OS and version: macOS Catalina
* Perl version: v5.30.3
* Perl distribution: homebrew

**Screenshots**
![Screen Shot 2020-12-01 at 8 51 51 AM](https://user-images.githubusercontent.com/5853628/100937419-d6088f00-34a7-11eb-993f-38b43a6c115c.png)

**Additional context**
IIRC there was another dialog that had the same problem on the Mac but not elsewhere. I don't think we solved it there either but we gave the dialog a sensible default size and persisted the size in `settings.rc`. It would be interesting to understand what we're doing for some dialogs that size correctly and for others that don't.

**Comment by windymilla** [comment]
[It was here](https://github.com/DistributedProofreaders/guiguts/pull/204/commits/5667d763e68b63d5a0e020b30b668c7e02fb8b8c)
