### ISSUE TITLE
Auto Index creates links from dates and numbers that are not page numbers

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#394]
Not sure if this should be classified as a bug, feature request, or something other people like as-is:

AFAIK, DP requires page number references within an Index to be preceded by a comma and a space (or, perhaps, a semi-colon and a space).  Rigorously enforcing that rule means that "783" in the following will NOT be converted to a link by Auto Index, but "15" and "25" will be converted:

    Hill 783 15, 25

Current and previous versions of Guiguts convert "783" to a link. Such errors can be found and corrected by a regex such as:

  S: (?<!, )<a href="#Page_\d+?">([\d-]+?)</a>
  R: $1

IMO, it would be better if GG didn't make them into links in the first place.

**Comment by windymilla** [comment]
Consider whether to also allow some sort of restriction on the numbers that would be converted, e.g. in a 400 page book, only numbers between 1 and 400 would be linked. This could avoid accidental linking of dates in most books.

**Comment by windymilla** [comment]
After further discussion, no need for a page number restriction as described above. However, check that the code will cope with page ranges, e.g. 189-233. Probably sufficient to allow a hyphen in place of the "comma space" currently required.

**Comment by charliehoward4dp** [comment]
A hyphen may follow a page number when it's part of a range, e.g., 37-40.  I think GG handles that now, but it doesn't handle the "dash" being an ndash.

**Comment by windymilla** [comment]
I'll try to make sure it does handle an ndash too.
