### ISSUE TITLE
Program looping on search & replace

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#437]
I did a search and replace for single quotes '.  I did a couple just fine then a pop-up screen opened and the program went into an endless loop.  See attachment.
A clear and concise description of what the bug is. Include any related error messages output on the command line.

**To Reproduce**
1. Open Guiguts
2. Open the Search & Replace menu ...
3. Entered ' into the search field.
4. Multi was the only option checked.
5. Entered ‘ and ’ into two different Replace fields.
6. Clicked R & S
7. See error screen print.  The same message was duplicated on the cmd screen.

**Expected behavior**
That the next ' would be found.

**Environment**
* Guiguts version:  1.2
* OS and version: Windows 10 Home 20H2 
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17208131/103420207-07c65180-4b4b-11eb-89f2-54abf5341394.JPG)

**Comment by windymilla** [comment]
Thanks. I'm pretty sure looking at the errors, it's the same bug as Charlie
found which I've got a fix for and hope to release a new version in due
course.
In the meantime, when you work on a new file, just pop up the page labels
dialog and say "use these values". You can go and enter the correct values
later when you would normally do that.
Hope that's helpful

**Comment by okrick** [comment]
I've never used that dialogue.  Do you mean in the Search=>Goto Page Label?  I don't think it is Tools=>Fixup Page Separators.

Drat.  The loop started again.  This time I was just looking in each menu dropdown looking for page labels.

**Comment by windymilla** [comment]
Just save your file and restart Guiguts should also fix it.

**Comment by windymilla** [comment]
Page labels comes from right clicking on the label in the status bar that
says Lbl:None

**Comment by okrick** [comment]
I was just thinking that it had to with Preferences=>Backup=>Enable Auto Save since I noticed that check mark was gone this time when I restarted but I clicked Enable Auto Save then set  Autosave Interval to 1 and made a change to the file. But nothing happened at all--not even an auto-save.  At least I ruled out the looping had anything to do with the back ups.

**Comment by okrick** [comment]
I notice there is an autosave file from over an hour ago so I'll take a break and see if auto save resumes before reporting.

**Comment by okrick** [comment]
"Page labels comes from right clicking on the label in the status bar that
says Lbl:None"
Did that and got this popup:
![Capture](https://user-images.githubusercontent.com/17208131/103421754-e49fa000-4b52-11eb-862f-d931399a284e.JPG)
Nothing here that I can edit.

**Comment by windymilla** [comment]
Does your file have page dividing lines like you get from the rounds?
Are you still getting the error messages after restarting Guiguts?

**Comment by okrick** [comment]
I replaced the dividing lines with ".bn 002.png" style dividers for ppgen.

**Comment by windymilla** [comment]
Ah, OK.
Anyway, it should hopefully be fixed in a new 1.2.1 release coming soon if
it is still giving you issues.
Thanks for the report - do let me know if it keeps happening.
Nigel

**Comment by windymilla** [comment]
I've just release [1.2.1](https://github.com/DistributedProofreaders/guiguts/releases/tag/r1.2.1) which will hopefully fix this issue for you.

**Comment by windymilla** [comment]
Fixed in 1.2.1 via #432
