### ISSUE TITLE
Malformed UTF-8 character

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#438]
I just received this message log:
11:59:46: Guiguts 1.2.1: If you have any problems, please include any error messages that appear here with your bug report.
13:30:49: Malformed UTF-8 character: \xb9 (unexpected continuation byte 0xb9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
13:30:49: Malformed UTF-8 character: \xb9 (unexpected continuation byte 0xb9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.

A clear and concise description of what the bug is. Include any related error messages output on the command line.

**To Reproduce**
1. Open Guiguts
2. Double clicked on the word τιθένε to select it
3. Pressed control V to paste the word τιθήνη previously copied from a smooth reader's correction.
4. See error message above.

**Expected behavior**
I expected τιθένε to be replaced with τιθήνη.

**This was not reproduced on my second attempt.**

**Environment**
* Guiguts version:  1.2.1
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Comment by okrick** [comment]
I take that back.  This is happening perhaps every third time I replace a Greek word with another.  I can't distinguish any differences in the steps that I am using.

I can say that I am also copying the changes to the TN at the end.  So far simply pasting Greek words does not result in an error message.  It is only when I try to replace one with another and then less than half the time.

**Comment by okrick** [comment]
Hold on, this last one occurred when I just double-clicked to select the Greek word τὴν. I got the following message even before I was ready to paste a replacement.

11:59:46: Guiguts 1.2.1: If you have any problems, please include any error messages that appear here with your bug report.
13:30:49: Malformed UTF-8 character: \xb9 (unexpected continuation byte 0xb9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
13:30:49: Malformed UTF-8 character: \xb9 (unexpected continuation byte 0xb9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:23:10: Malformed UTF-8 character: \x83 (unexpected continuation byte 0x83, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:23:10: Malformed UTF-8 character: \x83 (unexpected continuation byte 0x83, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:56:41: Malformed UTF-8 character: \x84 (unexpected continuation byte 0x84, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:56:41: Malformed UTF-8 character: \x84 (unexpected continuation byte 0x84, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.

**Comment by okrick** [comment]
Then I got this error when I did paste τήν over τὴν
11:59:46: Guiguts 1.2.1: If you have any problems, please include any error messages that appear here with your bug report.
13:30:49: Malformed UTF-8 character: \xb9 (unexpected continuation byte 0xb9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
13:30:49: Malformed UTF-8 character: \xb9 (unexpected continuation byte 0xb9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:23:10: Malformed UTF-8 character: \x83 (unexpected continuation byte 0x83, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:23:10: Malformed UTF-8 character: \x83 (unexpected continuation byte 0x83, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:56:41: Malformed UTF-8 character: \x84 (unexpected continuation byte 0x84, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:56:41: Malformed UTF-8 character: \x84 (unexpected continuation byte 0x84, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
15:00:23: Malformed UTF-8 character: \x84 (unexpected continuation byte 0x84, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
15:00:23: Malformed UTF-8 character: \x84 (unexpected continuation byte 0x84, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.

**Comment by okrick** [comment]
I'm going to add the TN for this last one then put this aside until tomorrow.  I'm only on line 553 with perhaps 3000 lines to go.

**Comment by windymilla** [comment]
Suggestion. Instead of double clicking a word, does selecting by dragging
across the text work better.

I'll look at it later to see if it's a new thing or not.
Thanks
Nigel

**Comment by windymilla** [comment]
I've had a look - it's been doing that since version 1.1 (not that that helps you, but may help me in finding a solution). In 1.0.25, I wasn't able to double click a Greek word to select it, so the problem couldn't show back then. It might be that some additional support for Unicode characters is in the more up-to-date Perl we use now, which means words can be selected, but something is clearly not right - I don't know yet if it will be something I have access to, in order to solve it.

Although it might be annoying, I have the following suggestion: when you double click to select a word, always double click the very first letter of the word, e.g. the τ in τὴν - so far I haven't been able to get the error to pop up when I do that. If that fails, then try just click and drag to select the word instead of double clicking. I'd be interested to know if you ever get the error when you use either of those methods.

Sorry if it slows you down a little in your edits - hopefully those workarounds will help.

**Comment by okrick** [comment]
I'll give it a try.  Glad to hear you were able to duplicate it.  I woke up considering back to the old Guiguts just so I could finish the SR errata & get the project posted but I'll give your suggestion a try.

**Comment by okrick** [comment]
Took your advice & doing much better today  But just got this with Θεχαρίδα.  

My cursor was just after the last character α.
I pressed shift ctrl left and the cursor stopped the highlight at the ί
I pressed shift ctrl left again then this message log appeared

15:41:09: Guiguts 1.2.1: If you have any problems, please include any error messages that appear here with your bug report.
11:33:30: Malformed UTF-8 character: \xb4 (unexpected continuation byte 0xb4, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
11:33:30: Malformed UTF-8 character: \xb4 (unexpected continuation byte 0xb4, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.

I have been usually starting at the beginning of the word and shift ctrl right to select the word for replacement.  Don't recall if this was the first time from the end but don't see how it could be different.

What was different was that the cursor stopped at the ί.  The new GuiGuts mostly stopped the nonsense of treating UTF-8 characters as whitespace.

**Comment by windymilla** [comment]
Oh, I misunderstood - I thought you were using the mouse to double click
rather than using shift-ctrl-left.
That's helpful for me to make sure the solution I'm working towards also
handles the keyboard case as well as the mouse case.

I recommend double clicking the first character of the word as the best way
forward until I get my fix ready for release

Thanks for the update
Nigel

**Comment by okrick** [comment]
Yesterday I was double-clicking to select the words and was not clicking consistently at any position in the word--I favor the middle slightly more than near the ends.  Today I was usually clicking just in front of the first character then doing the shift ctrl right arrow thing.  That is easier for me than shift dragging the cursor over the word but I'll try switching to that method.

**Comment by windymilla** [comment]
What I'm suggesting is double click on the first character of the word,
i.e. right on the N in Nigel, not in front of or behind it. It may not be
totally reliable, but I'm well on the way to finding a solution to
(another) bug in Perl/Tk.

**Comment by okrick** [comment]
Taking a break from the Greek when this happened.  I double-clicked on "pépinières" and got this error. So the problem is not limited to Greek.

15:41:09: Guiguts 1.2.1: If you have any problems, please include any error messages that appear here with your bug report.
11:33:30: Malformed UTF-8 character: \xb4 (unexpected continuation byte 0xb4, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
11:33:30: Malformed UTF-8 character: \xb4 (unexpected continuation byte 0xb4, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
16:03:26: Malformed UTF-8 character: \xa9 (unexpected continuation byte 0xa9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
16:03:26: Malformed UTF-8 character: \xa9 (unexpected continuation byte 0xa9, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
