### ISSUE TITLE
The <big> & <small> HTML Markups are deprecated

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#445]
**Describe the solution you'd like**
Replace the HTML Markup <big> & <small> actions with optional markups set in the user preferences.

**Describe alternatives you've considered**
The buttons can be removed entirely.

Low priority.  Add this to the list of items to be changed on the next revision to the HTML Markup menu.

**Comment by windymilla** [comment]
I don't think `<small>` is deprecated now (though possibly was at one time), just `<big>`. Both remain valid for us at present since we do not generally produce HTML5. 
It is recommended to use CSS instead for spans of smaller or larger text.

**Comment by windymilla** [comment]
Not the right time to remove this yet due to us not producing HTML5. There are buttons to assist with using spans to achieve bigger and smaller text if the user so chooses.
