### ISSUE TITLE
10:52:25: Wide character in print at C:/DP/guiguts/lib/Guiguts/FileMenu.pm line 319.

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#447]
**Describe the bug**
I pressed ctrl-s. Got the following error message.

13:28:55: Guiguts 1.2.1: If you have any problems, please include any error messages that appear here with your bug report.
10:52:25: Wide character in print at C:/DP/guiguts/lib/Guiguts/FileMenu.pm line 319.

**To Reproduce**
1. Open Guiguts
2. Open the File=>Save menu ...
3. See error
4. Per the Windows file explorer display the file date modified = the date/time I pressed ctrl-s

**Expected behavior**
I expected the file to be saved without receiving an error message.

**Environment**
* Guiguts version: 1.2.1
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Comment by windymilla** [comment]
Thanks - I can't see from the code how it would writing a wide character at that line - it is writing the Track Operations history to the .bin file, which just consists of the operation being done and the time at which it is done. 
It's possibly too late now, but if you see the same thing again, please could you attempt to quickly take a copy of the .bin file before Guiguts has a reason to save it again, and upload it here or send it to me. Thanks

**Comment by okrick** [comment]
[maclairn-src.txt.bin.zip](https://github.com/DistributedProofreaders/guiguts/files/5777921/maclairn-src.txt.bin.zip)
I've saved since but this bak is closer to the time of the fault.

**Comment by windymilla** [comment]
Perfect! That's located the issue - thanks. 

Using the Orphaned Brackets tool to check English curly quotes (and possibly others) is recorded in the Operations History if it is turned on. When the file is saved, this is written to the .bin file, but apparently not in a utf8-safe manner, so the "wide character" being complained about is the curly quotes in
```
$::operationshash{'Found no more orphaned “ ”'}='2021-01-06 10:52';
```
A long-standing bug (at least 1.0.25), but the error used to be just in the command window, so was probably either overlooked or ignored.

**Comment by okrick** [comment]
Outstanding.  Glad I reported it.  I usually rely on the pptext smart quote check but I was overwhelmed in the current project.  It not only has a lot of them but the paragraphs are huge so a note at the end that a quote was not closed wasn't that helpful.  The orphaned brackets helped me sort things out.
