### ISSUE TITLE
Prevent deletion of user's custom menu items with new releases

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#450]
**Describe the solution you'd like**
I'd like new releases to not delete my custom menu.  New or changed global items should load at the top with unique to this user items below them.

**Describe alternatives you've considered**
Having a new GuiGuts install rename the "setting.rc" file to "setting.old" before overwriting.

**Comment by windymilla** [comment]
I understand the reason for wanting that. I'm not quite sure how to do it. The user's settings are in setting.rc as you said. A new release has to have a clean setting.rc to cope with changes in the release. 
If you upgrade according to the instructions, your old setting.rc file will be in `c:\guiguts-old\setting.rc`, so, with care, you could copy the relevant portion into the new one once you have run the new Guiguts once. This is described approximately in section 4 of UPGRADE.md under the release.
Do you think that is acceptable?

**Comment by okrick** [comment]
Good point.  That is acceptable if there is no way to implement this.

**Comment by windymilla** [comment]
Agreed to close - would need a major overhaul of how settings are stored and transferred between releases.
