### ISSUE TITLE
Search & Replace Window Width issues

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#460]
**Describe the bug**
1. The Search & Replace Window does not return to the same width if it is closed and reopened.
2. Shrinking the Search & Replace Window hides the History drop-down selectors once the window width is less than about 50% of screen width.  Perhaps this is why the width gets restored every time the window is reopened.
3. I did notice that the height cannot be changed now.  I think this is a good thing.  Height changes caused issues in the old Guiguts.
4. I also note that the position of the left edge of the window is restored just as it did in the old version.  I also think this is good.

**To Reproduce**
1. Open Guiguts
2. Open the Search=>Search & Replace menu ...
3. Change the width of the window.
4. Once the Window is reduced to less than ~50% pc screen size the History dropdowns are gone.
5. Close the Search & Replace window.
6. Reopen the Search & Replace window.
7. The window opens at the same width as in step 2.  Does not matter if the width is increased or decreased. 

**Expected behavior**
I expect Guiguts to remember the width of the S&R window.  I like that the height is fixed and that the position is remembered.

**Environment**
* Guiguts version: 1.2.2
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Additional context**
The particular issue I find perplexing with the width is that the S&R default is more than 50% of the window width.  When the Guiguts is snapped to the left 50% and my image window is on the right 50% of the screen then the S&R window overlays a portion of the image window.  When the image viewer window is foreground then I can't see the Search/Replace buttons unless I slide the S&R window partly off-screen to the left.

The default could be shrunk enough for me but I doubt that solution work for everyone.

**Comment by windymilla** [comment]
The S&R dialog has behaved this way (re-sizing) since at least version 1.0.25.
What has changed is that the user can now choose a font for the text fields. A larger font would mean a wider dialog, which makes the resizing issue more obvious.

**Comment by okrick** [comment]
I see. If I choose "Use system default for text entry fields"  then the S&R window is about 40% of full screen or 80% of the Guiguts which is sized at 50% screen.  If I uncheck that then the S&R window is about 60% of full screen or 120% of the Guiguts half-width screen.

I prefer the S&R to use the same font as the main screen but I'll see if I can live with it.  But why is a default width forced on me?  I can't think of a valid reason for this change.  The old Guiguts did not do this.
---------------------
Do you want me to split off the disappearing drop-down history indicators into a separate bug report?  I'm happy to do so.  I felt they were related but now I realize this should have been two reports.

**Comment by windymilla** [comment]
As I said in my comment, I just tried it out. Both GG 1.1 and GG 1.0.25 and
probably before that, so about 10 years, it has always reset its width when
you pop it. Have a try in 1.0.25 and you'll see, unless I've completely
missed something

**Comment by windymilla** [comment]
The disappearing dropdowns also behave the same as for many years. I will
address these issues, but not in a bug fix release. For now, I'm just going
to make the default width narrower, from 60 character fields to 40,which
should help, although not addressing the long - standing resize issues

**Comment by okrick** [comment]
I'm sorry.  You're correct.  I didn't remember the behavior from the earlier version but both things work that way in the earlier version.  

I'll revert to the system default for the text entry fields.

**Comment by windymilla** [comment]
Hopefully once I release 1.2.3 soon with a reduced width to 40, you'll be
able to go back to the font you prefer
