### ISSUE TITLE
'Configure Page Labels' issue in 1.2.2

### ISSUE THREAD

**Issue by jandac-2020** [DistributedProofreaders/guiguts#468]
1) Working on a new project, I right-clicked on the 'Lbl Pg' button and edited the 'blank'  Labels as usual to reflect the page numbering of the actual book, then clicked on 'Use these values' to save it to the *.bin file.
2) Next day I reload GG1.2.2, look at my file, and the page numbering shown on the toolbar is still correct. I later looked at the .bin file itself, and it looks good to me, with the changes that I did.
3) However, when I right-click on the 'Lbl Pg' button to make some edits, the dialog box ('Configure Page Labels') that comes up is the 'blank' starting version -- not the correct actual .bin file created yesterday. So I cannot make any edits to it, unless I start from scratch.

My work-in-progress .txt and .bin file attached.

[fields.zip](https://github.com/DistributedProofreaders/guiguts/files/5817733/fields.zip)

**Comment by windymilla** [comment]
I believe this is fixed in 1.2.3, although it may need a fresh start for
the bin file.

**Comment by windymilla** [comment]
Fixed in 1.2.3
