### ISSUE TITLE
Auto Illo Gen issue in 1.2.3

### ISSUE THREAD

**Issue by jandac-2020** [DistributedProofreaders/guiguts#470]
After autogen of the *split.htm file, and auto illo gen of the illos, the generated list of ".illowxxx" entries had an unwanted space after the . and before the illowxxx ie ". illowxxx"
Easy to fix, but should not happen.

**To Reproduce**
1. Open Guiguts 1.2.3
2. Load any *.htm file that has associated illos, preceding html generation. (Probably not relevant but my file has no poetry.)
3. 'Autogenerate HTML'
4. 'Auto illus search' and generate a couple of its illos
5. Look at the inserted css ". illoxxx" entries, they have a space after the dot.

**Expected behavior**
".illowxxx" with no space.

If you can't reproduce this on your files in your environment, I can provide a zip of my files+images.

**Comment by windymilla** [comment]
Thanks for the report. It's already fixed by pull request #469, but I haven't created a new release yet.
Sorry for the inconvenience

**Comment by windymilla** [comment]
Fixed by #469
