### ISSUE TITLE
15:46:30: Use of uninitialized value in pattern match (m//) at C:/DP/guiguts/lib/Guiguts/SearchReplaceMenu.pm line 1944. 

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#479]
**Describe the bug**
Orphan bracket () search result:
10:32:01: Guiguts 1.2.3: If you have any problems, please include any error messages that appear here with your bug report.
15:46:30: Use of uninitialized value in pattern match (m//) at C:/DP/guiguts/lib/Guiguts/SearchReplaceMenu.pm line 1944.
15:46:30: Use of uninitialized value in pattern match (m//) at C:/DP/guiguts/lib/Guiguts/SearchReplaceMenu.pm line 1944.
15:46:30: Use of uninitialized value in pattern match (m//) at C:/DP/guiguts/lib/Guiguts/SearchReplaceMenu.pm line 1944.
15:46:30: Use of uninitialized value in pattern match (m//) at C:/DP/guiguts/lib/Guiguts/SearchReplaceMenu.pm line 1944.
15:46:30: Use of uninitialized value in pattern match (m//) at C:/DP/guiguts/lib/Guiguts/SearchReplaceMenu.pm line 1944.

**To Reproduce**
1. Open Guiguts
2. Open the Tools=>Check Orphaned Brackets...
3. Select Bracket or Markup Style ()
4. Click Search
5. See error

**Expected behavior**
I expect it to find the first case of unpaired parenthesis if any.

**Environment**
* Guiguts version: 1.2.3
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Additional context**
Here is the file.
[hazlitt5.zip](https://github.com/DistributedProofreaders/guiguts/files/5839280/hazlitt5.zip)

**Comment by windymilla** [comment]
I can't reproduce this from that file following those instructions. Please could you download the file and check the instructions again - I'm on a similar setup to you so it should be the same for both of us. I'm hesitant to add something to the code when I can't see the problem happening, and won't be able to check if any fix I make actually solves the problem. Thanks

**Comment by okrick** [comment]
I downloaded the file and tried again.  This happens every time on this file.  I closed GuiGuts and Strawberry Perl then tried again.  I still get the error message.  

It does not matter if I do it entirely by mouse, left-clicking the Tools=>Check Orphaned Brackets then left clicking the () then clicking the Search button.  Or if I do it entirely by keyboard, alt-t, o, three tabs, then space to select () then tab to the select button and space again.

**Comment by windymilla** [comment]
I've worked out why I couldn't reproduce it - the brackets you put in the bug report are round brackets (parentheses), but actually it is the curly brackets {braces} that are going wrong. I discovered it by using your keyboard navigation instructions - the "three tabs" bit took me to the braces check. Sure enough, I saw the error.
I will get it fixed - thanks for the report.

**Comment by okrick** [comment]
Sorry, I reported what I see.  The {} look like () in the Orphaned Brackets window.  I'll try to increase the size of text in the window.  

Actually, I think I'd know by now from the position what was there considering I've probably clicked through this a thousand times.  I just click on each button sequentially until one finds a potential issue.

**Comment by windymilla** [comment]
Thanks for reporting that error - it's another (small) victory for me having made the errors that were previously not noticed by people more visible.

In your file, you have four consecutive close braces without open braces, used as they often are to group lines together
```
A Philosopher,    }
An Eremite,       } all properly habited.
A Ploughman,      }
A Shepherd,       }
```
These should be reported as potentially orphaned by the code. If you have just 3 of them, they would be. If you have 5, then the first 4 are ignored and the 5th one reported. In the exact case of 4, they are silently ignored. If those 4 are the last 4 such brackets in the file (as yours are), the ignoring is not silent because it triggered an error message.

I've removed this "feature" of ignoring exactly 4 in a row, which I'm sure had a reason for its original existence 10+ years ago, but I can't see why we would want it. This will also fix the error message.

**Comment by okrick** [comment]
How odd.  I recall that if there were a series of them usually only one would be found.  I agree.  I'd prefer an alert for every orphaned parenthesis or bracket.  

I believe there may be similar code for the /*...*/ and /#...#/ sequences.  I know nested /#.../#...#/...#/ block quotes are OK in the formatting rounds but they make me very unhappy during PP when I encounter an unexpected one.  I would prefer an alert for those as well.  But on the other hand, I can design a simple macro for this check myself so this isn't critical.

Thank you for fixing this,
