### ISSUE TITLE
"Malformed UTF-8 character" error when using Ctrl-left arrow

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#500]
**Describe the bug**
15:21:32: Guiguts 1.2.4-beta: If you have any problems, please include any error messages that appear here with your bug report.
21:48:55: Refusing to run "start" command with unsafe characters ("<>|&()!%^): https://books.google.com/ngrams/graph?year_end=1924&smoothing=50 at C:/DP/guiguts/lib/Guiguts/Utilities.pm line 254.
22:01:24: Malformed UTF-8 character: \x9c (unexpected continuation byte 0x9c, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
22:01:24: Malformed UTF-8 character: \x9c (unexpected continuation byte 0x9c, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
08:23:53: Malformed UTF-8 character: \x99 (unexpected continuation byte 0x99, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
08:23:53: Malformed UTF-8 character: \x99 (unexpected continuation byte 0x99, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.

**To Reproduce**
1. Open Guiguts
2. Click at the end of the word "d’hygiène" in line 7968. (< is not included in the selection)
3. Press Ctrl-left arrow

**Expected behavior**
I expect the word "d’hygiène" to be selected with no error messages

**Environment**
* Guiguts version:  1.2.4-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Files**
[psychopathia.zip](https://github.com/DistributedProofreaders/guiguts/files/5898301/psychopathia.zip)

**Additional context**
I've been using the WF check accents to find potential foreign passages and marking them accordingly.  I've used the same method to select the phrase on a dozen or so and this is the first one with an error.  I checked for invisible characters in this word but all of the characters are normal UTF-8 characters.  This is repeatable--I get the same result every single time. None of the characters specifically mentioned are within the selection.

Incidentally, I've selected words and passages this way for decades now.  And for years in Guiguts without warnings.  Hard to stop something I do without a thought.

**Comment by windymilla** [comment]
I edited the Issue title, as the earlier error message was from 10 minutes previously, presumably when trying to do a Google ngrams search.

**Comment by windymilla** [comment]
I've downloaded the file, gone to line 7968 and placed the cursor after the word d’hygiène
When I press Ctrl-left-arrow, the cursor moves back to the beginning of the word hygiène as expected, but no error message.
I'm on Windows 10, with essentially 1.2.4-beta, apart from a few insignificant recent edits (word frequency dialog, HTML markup dialog, rewrapping bug, search/replace dialog, page separator dialog)
I won't be able to investigate unless we can find a way of reproducing it. Have you tried exiting GG and restarting it, then loading the file again?

**Comment by okrick** [comment]
Exited GG, reopened it, and reopened a copy of the file I sent.  You are correct--the issue is gone, no error message.

Close this.  I'll try to remember to do the close and reopen GG steps just before finishing the report in the future.

I suggest closing this.

**Comment by windymilla** [comment]
Thanks - there is obviously something odd somewhere, but I agree we should close this for now.
