### ISSUE TITLE
Malformed UTF-8 character: \x9c (unexpected continuation byte 0x9c, with no preceding start byte)

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#502]
**Describe the bug**
10:11:00: Guiguts 1.2.4-beta: If you have any problems, please include any error messages that appear here with your bug report.
14:59:11: Malformed UTF-8 character: \x9c (unexpected continuation byte 0x9c, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
14:59:11: Malformed UTF-8 character: \x9c (unexpected continuation byte 0x9c, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.

**To Reproduce**
1. Open Guiguts
2. Open the Word Frewuancy=>Hyphens menu 
3. Scroll down to 'bime-by' and double click the entry
4. 'bime-by' on line 7092 is selected
5. Cursor between the 'y' and the semicolon
6. Ctrl-left arrow
7. See message

**Expected behavior**
I expect to select 'bime-by' without an error message

**Environment**
* Guiguts version:  1.2.4-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**files**
[josiah.zip](https://github.com/DistributedProofreaders/guiguts/files/5907387/josiah.zip)

**Additional context**
More or less a repeat of an earlier bug report. 
This was repeatable until I closed and restarted GuiGuts.  Then quit.

If you still can't figure out what is happening then just close this and I'll reopen it when it happens again.

**Comment by windymilla** [comment]
Success! I can reproduce that, with a slight change to the instructions:
At step 6, I have to press Ctrl-left-arrow 3 times.
Note the same error is in 1.1.1 (though only output to the command window, so less intrusive) 
The error does not happen in 1.0.25 (possibly/probably due to a different version of Perl?)

**Comment by okrick** [comment]
Odd. I can't make it happen in 1.0.25 but I thought I had only one version of Perl on my machine.  

Oh, I see it was a part of 1.0.25.  And it is a plain cmd window next to GuiGuts instead of the 4 strawberry cmd window.

So I presume this means I have to change the habits of decades to comply with Strawberry's restrictions.

**Comment by windymilla** [comment]
Well now I can see it, I have a chance of fixing it. I already fixed the similar previous one, so don't despair just yet :)

**Comment by okrick** [comment]
Great.  I hope you succeed.  I haven't given up hope.😀

**Comment by windymilla** [comment]
No guarantees, but I found two ways in which the bug in Tk could still sneak past my previous fixes. Your file now doesn't give that error for me around 'bime-by'
