### ISSUE TITLE
Fixup Page Separators 80% and 99% can safely delete consecutive separators automatically

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#507]
When there are two or more consecutive/adjacent page separators, e.g.,

> tea-canisters, pepper-boxes, teacups, etc., served for
> -----File: 142p.png--------------------------------------------------------
> -----File: 142r.png--------------------------------------------------------
> -----File: 143.png---------------------------------------------------------
> the necessary vessels, and the sand-tub furnished the
> matter to be analysed. I only had to take care to

80% auto and 99% auto can delete all of them automatically if no hyphen is involved, and can delete all but the last if there is a conditional hyphen "-*'.  This also applies to end-of-chapter situations, such as:

> sobriety, and an earnest seeking for truth.
> -----File: 220.png---------------------------------------------------------
> -----File: 221l.png--------------------------------------------------------
>  
>  
>  
>  
> INDEX.

where both (or all) can be deleted automatically.

**Comment by windymilla** [comment]
When looking at a separator, just delete it if it is immediately followed by another.

**Comment by charliehoward4dp** [comment]
Yes, that's a better way of expressing the request.
