### ISSUE TITLE
"Display/Adjust Page Markers" can silently turn off "Auto Img" without turning off its color

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#512]
If "Auto Img" is ON and then the next/prev arrowheads are used to go from page to page, or the next/prev buttons in "Display/Adjust Page Markers" are used to go from page to page, they turn off the "Auto Img" function but do not change its color from violet back to default gray. This leaves the user believing that "Auto Img" still is ON when it's actually off.

To reproduce this:

* on the Status Bar, click "Auto Img" to turn it on. Optionally,  scroll/click to another page to confirm it's working. The external viewer will show the matching image, as it should.

* click either the ">" or "<" arrowhead surrounding "See Img". The "Display/Adjust Page Markers" dialog will appear and "Auto Img" will remain colored.

* using either the keyboard or the mouse, scroll to an area of text that is on a different page and click in that area

* the external viewer will continue to show the previous image, as though nothing had happened in GG

* close the "Display/Adjust Page Markers" dialog. "Auto Img" will remain colored and the feature will remain OFF

* click "Auto Img". It will remain colored, but the feature will turn ON, and the matching image will appear in the external viewer.

* BTW: if "Auto Img" is on when "File>Project>Display/Adjust Page Markers" is used, "Auto Img" remains on, until/unless a "next/prev" button in the Dialog or "next/prev" arrowhead is used. If the Dialog is displayed through the menu system and closed without any of those buttons being used, "Auto Img" remains in effect.

Alternative fixes:

* when one of the next/prev arrowheads is used (silently turning off "Auto Img") change the "Auto Img" button color back to default gray. This is my preferred solution, and should be simple to do.

* store the "Auto Img" state when one of the arrowheads is used and restore that state when "Display/Adjust Page Markers" is closed.  I don't like this alternative and think the programming complexities might make things worse than they are now.

**Comment by okrick** [comment]
Me too.

And I like the first alternative Charlie suggested.
