### ISSUE TITLE
GG 1.2.x "Configure Page Labels" has no scroll bar and cannot get past what fits in the window of a certain file

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#541]
GG 1.2.3 and 1.2.4 cannot configure page labels for the main .txt file of "U.S. Marine Operations in Korea, Volume 5", project ID projectID5c69166719efb https://www.pgdp.net/c/project.php?id=projectID5c69166719efb . (The file is in that project's zip: https://www.pgdp.net/projects/projectID5c69166719efb/projectID5c69166719efb.zip). Earlier versions of GG, including 1.1.1 and 1.025 work with this file, and files from other projects work with GG 1.2.3 and 1.2.4

A few lines appear in the "configure" window when "Lbl: None" is right-clicked in the Status bar (or when the option is chosen from the FILE>Project menu), and eventually, the window becomes fully populated to the extent it can be seen.  However, there's no scrollbar, so it isn't possible to get past 041.png.

HOWEVER: making the Dialog window shorter causes the scrollbar to appear, and the window then can be used and made longer with the scrollbar remaining available. This is repeatable, and starting with a shorter Dialog window (since it remembers its previous height) shows the same problem.

This is a longer-than-average text file (724 page images), so perhaps that's a factor.

**Comment by windymilla** [comment]
Sorry, Charlie. I can't reproduce. I've tried my latest dev version, 1.2.4 and 1.2.3 (renaming my setting.rc so it starts with a fresh one). I load the text file. After the pause while it populates the window, the scrollbar is always there and enabled. I also tried changing the dialog size with no problems. Then restarting with the different dialog size saved, again with no problems.
The only thing I can think of that I might have different is that I upgraded my Strawberry perl and Tk. Did you do that? I think it's most unlikely to be that - more likely something in your setting.rc for those releases, although I don't know what that setting could be to have that effect.

**Comment by windymilla** [comment]
If you do find it's your setting.rc, perhaps you could send that to me and I'll investigate the cause.

**Comment by charliehoward4dp** [comment]
I renamed setting.rc and re-ran GG 1.2.4. Problem still occurred with a newly-generated setting.rc.

Unzipped GG 1.2.4 from the original download, dragged-dropped the file onto run_gg.bat. Problem did **not** occur the first time, but occurred each time thereafter.  Deleting setting.rc in that folder and trying again did not help: the scrollbar was missing every time, but appeared as soon as the Dialog window was resized.

Same with GG1.2.4focus.  There are no modifications at all in that folder or any of its sub-folders. Worked once, then never worked again (until Dialog is resized).

So far, this problem only has occurred with that file and, to a limited extent, with children of that file (page labels have been assigned, some lines of text moved around): sometimes there's a scrollbar, sometimes not.

Since the presence or absence of setting.rc doesn't affect the results, there's no point in pursuing an analysis of its content. No other files or folders in a new, clean copy of GG 1.2.4 or GG 1.2.4focus have "today's" date, implying that nothing else has been changed. Maybe this is a Windows 10 issue just on my computer.  I will post this and then reboot the system to see if that makes a difference.

**Comment by charliehoward4dp** [comment]
Rebooting the computer did not resolve this issue.  Since there's an easy workaround (even a trivial resizing of the Dialog causes the scrollbar to appear) and it doesn't happen with other files I've tried, you can ignore this report.  I'm hesitant to close it for a while, in case someone else encounters the same issue, but it's OK with me if you decide to close it.

**Comment by windymilla** [comment]
Try editing HTMLConvert.pm.

At about line 3885 you will see
```
        $top->update;
```
Change it to
```
        $frame1->yview( 'scroll', => 1, 'units' );
        $top->update;
        $frame1->yview( 'scroll', -1, 'units' );
```
See if that has any effect - it's the only bit of relevant code I can see that has changed between 1.1.1 and 1.2.4

**Comment by charliehoward4dp** [comment]
Yes, that seems to have fixed the problem :-), although I've only tried it three times. It's surprising that a module intended for HTML use would be involved with creating/updating page labels.  Could it affect anything else (adversely, that is)?

Thank you for researching and finding this.
