### ISSUE TITLE
UTF-8 borders on text tables paste as ASCII

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#550]
**Describe the bug**
I was reducing the width of text tables with borders by copying the columns into guiguts.  The UTF-8 border characters were changed to ASCII.

**To Reproduce**
1. Open Guiguts
2. Paste (ctrl-v) a text table with borders into the document.
3. The result is that all of the UTF-8 characters were changed to odd ASCII characters.

**Expected behavior**
I expect the paste to be exactly what I copied.

**Environment**
* Guiguts version:  1.2.4
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Screenshots**
Copied text:
 ┌────────┬──────┬─────────┬─────────┬─────────┬─────────┬─────────┐
 │Seasons.│Weeks.│  West   │  North  │ Central │  East   │  South  │
 │        │      │District.│District.│District.│District.│District.│
 │        │      │         │         │         │         │         │
 │        │      │         │         │         │         │         │
 │        │      │         │         │         │         │         │
 │        │      │         │         │         │         │         │
 │        │      │         │         │         │         │         │
 ├────────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┤
 │Winter  │  13  │    2,127│    2,588│    3,064│    3,227│    3,542│
 │Spring  │  13  │    1,611│    2,066│    2,264│    2,264│    2,682│
 │Summer  │  13  │    1,486│    1,817│    2,064│    2,220│    2,458│
 │Autumn  │  13  │    1,518│    1,959│    2,144│    2,476│    2,655│
 ├────────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┤
 │ Totals │  52  │    6,742│    8,430│    9,536│   10,187│   11,337│
 ├────────┴──────┼─────────┼─────────┼─────────┼─────────┼─────────┤
 │Population     │  300,705│  365,660│  373,806│  392,496│  438,060│
 │  enumerated,  │         │         │         │         │         │
 │  1841.        │         │         │         │         │         │
 ├───────────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
 │Deaths out of  │      224│      231│      255│      260│      259│
 │  10,000       │         │         │         │         │         │
 │  inhabitants  │         │         │         │         │         │
 │No. of         │    44·60│    43·38│    39·20│    38·53│    38·64│
 │  Inhabitants  │         │         │         │         │         │
 │  out of which │         │         │         │         │         │
 │  1 death      │         │         │         │         │         │
 │  happened     │         │         │         │         │         │
 └───────────────┴─────────┴─────────┴─────────┴─────────┴─────────┘

Pasted result was:
  ââââââââââ¬âââââââ¬ââââââââââ¬ââââââââââ¬ââââââââââ¬ââââââââââ¬ââââââââââ
 âSeasons.âWeeks.â  West   â  North  â Central â  East   â  South  â
 â        â      âDistrict.âDistrict.âDistrict.âDistrict.âDistrict.â
 â        â      â         â         â         â         â         â
 â        â      â         â         â         â         â         â
 â        â      â         â         â         â         â         â
 â        â      â         â         â         â         â         â
 â        â      â         â         â         â         â         â
 ââââââââââ¼âââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¤
 âWinter  â  13  â    2,127â    2,588â    3,064â    3,227â    3,542â
 âSpring  â  13  â    1,611â    2,066â    2,264â    2,264â    2,682â
 âSummer  â  13  â    1,486â    1,817â    2,064â    2,220â    2,458â
 âAutumn  â  13  â    1,518â    1,959â    2,144â    2,476â    2,655â
 ââââââââââ¼âââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¤
 â Totals â  52  â    6,742â    8,430â    9,536â   10,187â   11,337â
 ââââââââââ´âââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¤
 âPopulation     â  300,705â  365,660â  373,806â  392,496â  438,060â
 â  enumerated,  â         â         â         â         â         â
 â  1841.        â         â         â         â         â         â
 âââââââââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¼ââââââââââ¤
 âDeaths out of  â      224â      231â      255â      260â      259â
 â  10,000       â         â         â         â         â         â
 â  inhabitants  â         â         â         â         â         â
 âNo. of         â    44Â·60â    43Â·38â    39Â·20â    38Â·53â    38Â·64â
 â  Inhabitants  â         â         â         â         â         â
 â  out of which â         â         â         â         â         â
 â  1 death      â         â         â         â         â         â
 â  happened     â         â         â         â         â         â
 âââââââââââââââââ´ââââââââââ´ââââââââââ´ââââââââââ´ââââââââââ´ââââââââââ

I've closed Guiguts and restarted it with the same result.

**Comment by windymilla** [comment]
Thanks Rick. Due to limitations in Perl/Tk handling of unicode characters, most of the time the paste works correctly. However there are occasions like the one you discovered where it fails. In that case, use the Alternative Paste I added. It's in the Edit menu, just below Paste. Also, you can use Ctrl-Alt-v for alternative paste in the same way you would use Ctrl-v for normal paste. If that works OK, let me know then I'll close this - there really is no more I can do to fix pasting unicode strings into Guiguts, I'm afraid.

**Comment by okrick** [comment]
The alternative paste works fine.  I don't have much call for this type of paste except where I am splitting tables.

You can close this.

**Comment by windymilla** [comment]
Alternative paste fixes this.
