### ISSUE TITLE
The three File>Project>View Project ... options all fail with the same error message (1.3 only)

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#558]
**Describe the bug**
Attempting in 1.3 to view the project's comments, main page or discussion using the three **View Project ...** options available on the **File>Project** menu all fail with the same error message being seen in the Message Log window that pops up: 

**File>Project>View Project Comments**
08:32:51: Tk::Error: Can't locate Win32/Unicode/Process.pm in @INC (you may need to install the Win32::Unicode::Process module) (@INC contains: C:/Users/nqgc/Desktop/DP/Tools/guiguts-win-1.3_210221/guiguts/lib . C:/Strawberry/perl/site/lib/MSWin32-x64-multi-thread C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib) at C:/Users/nqgc/Desktop/DP/Tools/guiguts-win-1.3_210221/guiguts/lib/Guiguts/Utilities.pm line 283.
 (menu invoke)

**File>Project>View Project Page [www]**
08:35:48: Tk::Error: Can't locate Win32/Unicode/Process.pm in @INC (you may need to install the Win32::Unicode::Process module) (@INC contains: C:/Users/nqgc/Desktop/DP/Tools/guiguts-win-1.3_210221/guiguts/lib . C:/Strawberry/perl/site/lib/MSWin32-x64-multi-thread C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib) at C:/Users/nqgc/Desktop/DP/Tools/guiguts-win-1.3_210221/guiguts/lib/Guiguts/Utilities.pm line 283.
 (menu invoke)

**File>Project>View Project Discussion [www]**
08:38:59: Tk::Error: Can't locate Win32/Unicode/Process.pm in @INC (you may need to install the Win32::Unicode::Process module) (@INC contains: C:/Users/nqgc/Desktop/DP/Tools/guiguts-win-1.3_210221/guiguts/lib . C:/Strawberry/perl/site/lib/MSWin32-x64-multi-thread C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib) at C:/Users/nqgc/Desktop/DP/Tools/guiguts-win-1.3_210221/guiguts/lib/Guiguts/Utilities.pm line 283.
 (menu invoke)

These three options work correctly in 1.2.4 with the same file loaded and running in the same Perl environment.

Note that if the projectID displayed by File>Project>Set Project ID in 1.3 is joined to the ends of the two path strings displayed by Preferences>File Paths>Set DP URls...  in 1.3, they form valid URLs that correctly display the project main page and the project discussion forum respectively.

**To Reproduce**
1. Open Guiguts with [tryit.txt](https://github.com/DistributedProofreaders/guiguts/files/6034828/tryit.zip)
2. Open the File>Project menu 
3. Scroll down to each of the three View Project ... options and click in turn to display their respective page
4. See error message in the Message Log window that pops up for each of them

**Expected behavior**
To work as in 1.2.4 running in the same Perl environment when the same options are invoked on the same file loaded in GG.

**Environment**
* Guiguts version: 1.3_20210221
* OS and version:  Windows 10
* Perl version: v3.50.3
* Perl distribution: See below.
C:\Users\nqgc>cpan --version Loading internal logger. Log::Log4perl recommended for better logging                                                   C:\Strawberry\perl\bin/cpan version 1.64 calling Getopt::Std::getopts (version 1.12 [paranoid]),
running under Perl version 5.30.3.
    [Now continuing due to backward compatibility and excessive paranoia. 
     See 'perldoc Getopt::Std' about $Getopt::Std::STANDARD_HELP_VERSION.]                                                
Nothing to install! 

**Screenshots**
N/A

**Additional context**
Works in 1.2.4 but not 1.3 as noted above.

**Comment by windymilla** [comment]
Sorry - this is my fault. When you install a new release you need to run the cpan installation script: install_cpan_modules.pl
It's in the top level folder of the release and is the same one mentioned in the normal installation instructions. I know I gave the impression there was nothing extra to do when installing 1.3, but you do need to do that, because 1.3 uses that perl module to allow unicode characters to be sent to system commands like opening a website. I should have mentioned it.

If you have the option of closing this issue, you can do that - I'm not sure if you have permissions for that. If not, I will close it.

**Comment by G4OEU** [comment]
Fixed. Not a GG code issue. See Nigel's comment above.
