### ISSUE TITLE
1.3 Beta error trying to use HELP Menu to request an enhancement/report a bug

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#559]
In GG 1.3_210221, clicking HELP>Report Bug... caused the error reporting window to pop-up with the following message:

> 11:19:24: Guiguts 1.3_210221: If you have any problems, please include any error messages that appear here with your bug report.
> 11:28:58: Tk::Error: Can't locate Win32/Unicode/Process.pm in @INC (you may need to install the Win32::Unicode::Process module) (@INC contains: D:/Documents/DistrProof/PP/GG 13.0Beta1/lib . C:/Strawberry/perl/site/lib/MSWin32-x64-multi-thread C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib) at D:/Documents/DistrProof/PP/GG 13.0Beta1/lib/Guiguts/Utilities.pm line 283.
>  (menu invoke)

This also happens with some other options on the HELP menu.

(Works OK in 1.2.4, which is how I got here.)

**Comment by windymilla** [comment]
Sorry. I should have told you to run the cpan install script. It won't
break old releases, but it will install that perl module

**Comment by charliehoward4dp** [comment]
Yes, that fixed it. Thanks.
