### ISSUE TITLE
ASCII Table Effects loses page labels within its range

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#561]
When using ASCII Table Effects, selecting a multi-page table and then manipulating it results in the entire table being assigned to the last page label of the range.  This isn't a major problem, but it makes it more difficult to compare portions of the resulting table with the original page images.

**Comment by windymilla** [comment]
Note to developer: last few routines in ASCIITables.pm (coladjust onwards) all essentially delete the table and reinsert the modified version at the end of the routine. This is most likely where page markers are being moved. Somehow need to decide where page markers should be in replacement table.
