### ISSUE TITLE
Content Providing: Remember Directory

### ISSUE THREAD

**Issue by mannyack** [DistributedProofreaders/guiguts#562]
When "Import Prep Text Files..." is used, remember the source directory, and use it as the default location for "Export as Prep Text Files...". (I also think that "Import Prep Text Files..." could invoke the "Save As" dialog, and put the directory where the prep files came from in the .bin file.)

**Comment by windymilla** [comment]
I don't really understand the bit in brackets. I have never done prepping
text files, which probably explains my ignorance - could you clarify what
you want to happen please.
