### ISSUE TITLE
(1) Rewrap bug in Plain Text; (2) AutoGenerate loses some of that text in HTML

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#564]
This bug is present in 1.1.1, 1.2.3, 1.2.4, and 1.3Beta1. It is not present in 1.0.25.  It manifests differently in Plain Text Rewrap than in HTML Generate.

PLAIN TEXT REWRAP: When the attached Plain Text paragraph is rewrapped, a blank line appears in the middle of it.  The problem seems to be caused by the "I/3/1" (no quotes; the first character is the capital letter eye, and I think GG interprets "/I" as the closing tag for the Index ... even in Plain Text). There were about 28 such errors, all of them involving strings like that, beginning with the capital letter eye, then a slash, then two more numbers separated by another slash.

To reproduce the problem, open "rewrapbug.txt" (in the attached zip) and rewrap it.

HTML GENERATE: After HTML Autogenerate, some of the text in that paragraph (and others like it) was completely lost. The resulting paragraph contained a closing &lt;/ul&gt; where the missing text had been.  Here's the complete resulting HTML paragraph:

> &lt;p&gt;Actually, more than an hour elapsed before the Communists
> initiated their first main ground attack to regain Bunker. By that&lt;span class="pagenum" id="Page_119"&gt;[Pg 119]&lt;/span&gt;
> time, heavy casualties from the continued shelling had forced Company
> B to pull back from the ridge and take up positions on the
> reverse (eastern) slope of Bunker Hill. At this point, with reduced
> Company B forces and with no radio communication between Captain
> Scranton’s unit and 3/1, Lieutenant Colonel Armitage sent
> &lt;/ul&gt;
> MLR. Shortly before 1600, a force of more than 350 Chinese lunged
> out of the low ground of Hill 123, west of Bunker, to attack defensive
> positions along the ridge between Hills 124–122. Striking in
> rapid succession first the west side and then the northern end of the
> Company B position to find a weak spot in the defense, the enemy
> counterattack finally concentrated on the southwestern part of the
> hill.&lt;/p&gt;
> 

The &lt;/ul&gt; replaced

> I/3/1,[181] under Captain Howard J.
> Connolly, forward from the 

which was lost from the file.  Autogenerate must be treating the "/I" as a closing block marker for an Index, even though it doesn't immediately follow a newline.

The complete file and its bin are available if needed. The Plain Text is over 30,800 lines in length. Looking the Plain Text over immediately after rewrap, I see that other sections of text also are missing.  The common characteristic in each case is that a nearby preceding line contained something like "I/3/5" (no quotation marks; the first character always is the capital letter eye).  That string usually is NOT at the beginning of the line, but was once, There are about 28 errors like this in the Plain Text, and presumably corresponding ones in the HTML (where text goes missing and is replaced by &lt;/ul&gt;).
[rewrapbug.zip](https://github.com/DistributedProofreaders/guiguts/files/6046960/rewrapbug.zip)

**Comment by windymilla** [comment]
I've fixed the rewrap issue, but can't reproduce the HTML Autogen issue, which is probably a similar fault in a different part of the code. Do I need the full file for that or is there a way to make it show in the test file? If so, please upload here or somewhere. Thanks

**Comment by charliehoward4dp** [comment]
The attached HTML file ("generatebug.html" and its bin) is ready for AutoGenerate. Before doing so, you may want to search it to find a couple of I/ examples, so you'll know where to look for missing text replaced by  &lt;/ul&gt; afterwards. The first few are in images 133 (five times), 135 (once), and 138 (twice).

[generatebug.zip](https://github.com/DistributedProofreaders/guiguts/files/6052575/generatebug.zip)
