### ISSUE TITLE
Tools>Footnote Fixup: Perl loops when attempt to move footnotes to Chapter LZ

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#601]
**Describe the bug**
The file used in this test is the same file included for Issue #600. With the file as it is, moving the five footnotes to Chapter LZ works as expected except for the following behaviour:

When Chapter LZ is chosen, FOOTNOTES: LZ markers are placed at the end of each chapter _except_ for the last. Note that neither the first 'chapter' (the 210 -line long PREFACE) nor the last chapter ("CHAP 2") have any footnotes. However the PREFACE gets a FOOTNOTES: LZ marker but CHAP 2 doesn't. This is probably relevant to the Perl looping bug described next.

Reload the test file and add a sixth footnote at the end of the file; that is, after the the end of CHAP 2 with its anchor anywhere in the last paragraph. Then repeat the steps to move footnotes to Chapter LZ. You will note that after clicking Autoset Chap. LZ you again see the same behaviour with the positioning of FOOTNOTES: LZ markers already noted. However now the last chapter, CHAP 2, has a footnote (#6) but still gets no LZ marker.

If you now click Move FNs to Landing Zones(s), despite there being no LZ marker at end of CHAP 2, the GG window freezes. The Windows 10 Task Manager shows the Perl interpreter as being very busy, using about 15% of CPU time as if in a tight loop.

**To Reproduce**
1. Open Guiguts with [footnote-fixup-test-V2.txt](https://github.com/DistributedProofreaders/guiguts/files/6097278/footnote-fixup-test-V2.txt)
2. Open the Tools>Footnote Fixup menu.
3. Then follow the processes described above.
4. See LZ marker location behaviour already described and then the 'looping'.

**Expected behavior**
It is clear what the expected behaviour should be.

**Environment**
* Guiguts version: 1.3_210304
* OS and version: Windows 10
* Perl version: v5.30.3
* Perl distribution: Perl distribution: C:\Strawberry\perl\bin/cpan version 1.64 calling Getopt::Std::getopts (version 1.12 [paranoid]), running under Perl version 5.30.3

**Screenshots**
N/A

**Additional context**
It appears that moving footnotes to Autoset End LZ works as expected, even with the sixth footnote added at the end of the file.

**Comment by windymilla** [comment]
The placement of End LZ is correct - it places them at every chapter start (4 blank lines) regardless of whether there are any 
footnotes that will end up moving there. When the Move FNs to Landing Zones operation runs, it automatically adds a LZ to the end of the file to mop up any footnotes that appear after the last LZ the user has set up. This gets deleted later if not used.
The loop was happening during the deleting of unused zones - the last one was so near the end that it accidentally looped round to start searching at the beginning again.
