### ISSUE TITLE
Ability to increase the size of label text on buttons and text entry fields in GG-created tool dialog boxes. E.g. S&R

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#630]
**Describe the solution you'd like**
In Windows 10 I have some control over text size in drop down menus and other parts of the display. However I cannot increase the very small text size of labels on buttons, and beside text entry fields, in tool dialog boxes such as Search & Replace. The smallness of the label text has only just become apparent due to recent changes in my vision.

**Describe alternatives you've considered**
I can use Preferences>Appearance>Set Fonts to change the displayed size of text that is typed into text entry fields but the text of GG generated labels beside those fields, and on buttons, remains very small. That is not helpful if you want all the text in the tool dialog to be more readable. This difference in respective text size is demonstrated in slightly exaggerated form in the screenshot below.

**Additional context**
Search & Replace tool menu: [capture_001_16032021_082909_cropped](https://user-images.githubusercontent.com/71753626/111284499-15fb1880-8638-11eb-9b48-e87394493ff3.jpg)

**Comment by windymilla** [comment]
A quick fix for now is to edit run_guiguts.bat and change the line
`perl "%GG_DIR%guiguts.pl" "%ED_FILE%"`
to
`perl "%GG_DIR%guiguts.pl" "%ED_FILE%" -font "Times 16"`
for example.
Of course you can choose other fonts/sizes.

I will think about whether it is possible/easy enough to add something to the Preferences/Font Selection so it can be changed within the program - I'm pretty sure it won't change instantly like the other font stuff - it would probably require a restart.

**Comment by windymilla** [comment]
Fixed by #635
