### ISSUE TITLE
A minor bug in Automatic Word Highlighting if I have understood the manual correctly

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#637]
**Describe the bug**
I Right-clicked H in the Status Bar and selected wordlist/en-common.txt.  According to the manual, "After a brief delay, all words listed in that file are highlighted wherever they appear in the document. Page through the document and each word of interest will stand out for you to inspect. Left-click the H button to turn highlighting off and on."

However I have to Left-click H in the Status Bar first to get the highlighting. Then toggling highlighting ON/OFF works fine thereafter. It is just that, based on the manual extract above, I expected the default 'highlighting' action to be "ON" and the words highlighted after a wait but it' appears to be "OFF" at start up.

Is the behaviour of GG correct and the manual wrong or vice versa?

**To Reproduce**
1. Open Guiguts, load a project file, then Right-click H in the Status Bar
2. Open the wordlist/en-common.txt file

**Expected behavior**
Expect to see some words highlighted in the document I have open in GG. But I have to toggle highlighting ON first by Left-clicking H in Status Bar.

**Environment**
* Guiguts version: 1.3_210313 (not 1.3_120313 as the GG title bar says!)
* OS and version: 
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
Looking at the code, it doesn't look as though the original author was intending to turn on highlighting when a file was loaded, and the "bug" is in old versions too, so in that sense it is the manual that is "wrong". However, it would be more friendly to behave as the manual describes, so I'll make that change - it's quite easy (I think!)

**Comment by windymilla** [comment]
I also noticed that if you have highlighting on, it is remembered the next time you start GG. The "H" icon is lit up, but there is no highlighting. It should highlight when it loads the file. I'll fix that too.
