### ISSUE TITLE
Configure Page Labels - 1.3_210320

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#640]
**Describe the bug**
Trying to change the Start @ value. I can get it to work sometimes but at other times I get an error (see below). I also cannot change what has been typed in the entry field. If I try to then I get an error - sometimes.

What is happening is a bit confused as I'm using the new implementation of Configure Page Labels intuitively (i.e. without documentation) and I may be contributing to the problem.

**To Reproduce**
1. Open Guiguts with the .txt/.bin files in this .zip archive: [x.txt.zip](https://github.com/DistributedProofreaders/guiguts/files/6176506/x.txt.zip)
2. Right-click Lbl: in the Status Bar.
3. In the Configure Page Labels dialog immediately try to change the Start @ value.
4. See error below:
22:14:06: Guiguts 1.3_210320: If you have any problems, please include any error messages that appear here with your bug report.
22:14:27: Tk::Error: wrong # args: should be ".toplevel1.frame1.listbox index index" at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .toplevel1.frame1.listbox
 [\&Guiguts::HTMLConvert::__ANON__]
 (in validation command executed by entry)
22:14:27: Tk::Error: wrong # args: should be ".toplevel1.frame1.listbox index index" at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .toplevel1.frame1.listbox
 [\&Guiguts::HTMLConvert::__ANON__]
 (in validation command executed by entry)

**Expected behavior**
Expected behaviour is obvious.

**Environment**
* Guiguts version: 1.3_210320
* OS and version: 
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
I see a slightly different behaviour if the .txt.bin file is temporarily renamed; that is, there is only a .txt file available to Guiguts when Configure Page Labels is invoked.

Two comments about this new implementation:
1. It is a clever solution to the 'large file problem' that previously broke Configure Page Labels and I welcome it.
2. However the layout of the 'dialog' buttons could be tweaked. More spacing between the groups of radio buttons would be helpful. I realise you have tried to align them above their respective columns but it looks untidy having them all pushed together on the LHS of the dialog box. I also found it a bit confusing. If, for example, the '--> Pg nnn' label column was swapped back to where it is in the earlier GG versions, that would naturally space the Arabic/Roman/" and the Start @/No Count/+1 radio button groups. However your new arrangement of the columns has an attractive logic about it!

**Comment by windymilla** [comment]
1. Fix bug when text in entry field was selected, which meant that the listbox reported
no items selected - using 'activate' instead for indexes, but still selecting so that the
selected page is highlighted in the list.
2. Added frames round top sections and spaced list entries slightly more to make
the layout clearer.
3. Added Auto-Img button which shows the image when a page is selected.
4. Added Double-Click binding to list to show the selected image.

**Comment by G4OEU** [comment]
The 210321 fixes are working well on my 1660 page test file. The framing of the radio button groups improves the appearance. Hadn't previously twigged to the Control-click and Shift-click bindings for Action and Style but they're neat and improve usability.
