### ISSUE TITLE
Use of uninitialized value $bh in numeric le (<=)

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#643]
**Describe the bug**
I get this error message when I press the up arrow key.

10:28:02: Use of uninitialized value $bh in numeric le (<=) at C:/DP/guiguts-win-1.2.4/guiguts/lib/Guiguts/TextUnicode.pm line 592.
10:28:02: Use of uninitialized value $by in numeric le (<=) at C:/DP/guiguts-win-1.2.4/guiguts/lib/Guiguts/TextUnicode.pm line 592.
10:28:02: Use of uninitialized value $by in subtraction (-) at C:/DP/guiguts-win-1.2.4/guiguts/lib/Guiguts/TextUnicode.pm line 615.
10:28:02: Use of uninitialized value $by in addition (+) at C:/DP/guiguts-win-1.2.4/guiguts/lib/Guiguts/TextUnicode.pm line 618.
10:28:02: Use of uninitialized value $testX in concatenation (.) or string at C:/DP/guiguts-win-1.2.4/guiguts/lib/Guiguts/TextUnicode.pm line 634.
10:28:02: Tk::Error: bad text index "@,354" at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .frame.linenumbertext.frame.textunicode
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 TextUnicode::UpDownLine at C:/DP/guiguts-win-1.2.4/guiguts/lib/Guiguts/TextUnicode.pm line 634
 <Key-Up>
 (command bound to event)

**To Reproduce**
1. Open Guiguts
2. Go to line 7058 c:0 of the attached file.
3. Press the up arrow key.

**Expected behavior**
I expect the cursor to move to line 7057 c:0

**Environment**
* Guiguts version:  1.2.4-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

[9154.zip](https://github.com/DistributedProofreaders/guiguts/files/6206714/9154.zip)

**Comment by windymilla** [comment]
Although it shouldn't give this error, the reason is that you have an odd character at the start of the line. If you look in the status bar you can see it is Dec: 65279 Hex: FEFF Zero Width No-Break Space
If you delete that character, the error goes away.
I will look to see if it is easy to fix the error anyway for release 1.3

**Comment by okrick** [comment]
How odd.  The BOM was in the PG footer boilerplate I was given.  And here I thought we were to avoid BOMs at PG like the plague!  I'll let the provider know.

Thank you,
