### ISSUE TITLE
Right-Align Numbers in Selection -1.3 (1.2.4 as well?) 

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#655]
**Describe the bug**
I suspect a 'feature' rather than a bug. 

Right-Align Numbers in Selection  works when you are aligning a single number (with one or more digits).

It does not work if there are two numbers on the line separated by a comma. This is a common occurrence in a ToC or Index. See example below.

**To Reproduce**
1. Open Guiguts
2. Cut and paste the following three lines, ensuring there is **at least two spaces** between text and first digit of a number:
```
line   1
line   2
lines   3, 4
```
3. Select the three lines then
4. Txt->Right-Align Numbers in Selection
5. Note that the first two lines have their numbers right aligned to the default right margin (72) but that the third line remains unchanged.

**Expected behavior**
Expect all numbers to be right aligned thus:
```
line          1
line          2
lines      3, 4

```
**Environment**
* Guiguts version: 1.3_210321
* OS and version: 
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
Now fixed - it will accept any number of numbers as long as they are separated by commas, hyphens or ndashes, and optionally some space, for example, the following will be right-aligned
`asda  5-6, 7,  8–9,10`
