### ISSUE TITLE
Possibilities for Footnote Fixup enhancements

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#680]
**Describe the solution you'd like**
### A check for malformed footnotes to appear on the Footnote Check display to include the associated line numbers.  Things such as:

- Any instance of the word Footnote (upper or lower case) without an anchor.  Show these as No anchor found or invent a Malformed footnote category.  Then a count comparison is unnecessary.  This would be more helpful since the user could find the error with a click.
- [Fotnote or any other combination with a 1 harm match which begins a line.  Either show these as No anchor found or invent a Malformed footnote category.

### Duplicate Anchor handling:

- Warnings for true duplicate anchors on the Footnote Check screen with a line number, specifically two or more like anchors between matching footnotes, usually two [A] or similar anchors on the same page. So there would be something like:

> [Footnote A: xyzzy]
> 
> ...Y2[A]
>
> ...you are in a maze of twisty little passages, all alike.[B]
>
> ...inside building.[A]
> 
> [Footnote A: plugh]

Many times these appear as out of sequence (see next item) but not if the [A] anchors are consecutive.  

- The Out of Sequence test should test if the sequence of the first duplicate in a sequence of anchors does not agree with the footnote sequence, not the last one.  Otherwise when the footnotes are reindexed and the duplicates are fixed with matching numbers for each pair then the Out of Sequence check falsely indicates an error for items such as the example shown. In other words, there should be no blue Out of Sequence errors on a project where every footnote has a unique index and are in the same order as the first instance of each anchor.

> Note: Some may disagree with the notion that the first anchor is the primary one of a duplicate.  Most publishers put the footnotes in the same order as the first occurrence of the anchor where a duplicate exists.  I'm only attempting to follow their lead.

- Very low priority but it would be nice if duplicate anchors could be indexed with the same id during reindexing.  I'd estimate that 20% or less of books with footnotes have true duplicates.  A PPer can always append an odd character to the second and subsequent duplicate footnotes and correct those after reindexing.

**Comment by windymilla** [comment]
I'm sorry - I think the work to implement these additional checks is too substantial for the benefit. Perhaps you might edit this to remove some of the more complex requests or close this one and add one or more smaller ones.
