### ISSUE TITLE
Guiguts Help on DP Forum (www) incorrect

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#686]
**Describe the bug**
The link to "Guiguts Help on DP Forum (www)" is incorrect

**To Reproduce**
1. Open Guiguts
2. Open the Help menu ...
3. Click "[Guiguts Help on DP Forum (www)](https://www.pgdp.net/phpBB3/index.php)"
4. The General (https://www.pgdp.net/phpBB3/index.php) index page appears

**Expected behavior**
The link should be( https://www.pgdp.net/phpBB3/viewtopic.php?f=13&t=11466)

**Environment**
* Guiguts version:  1.3.0-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.32.1.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.32.1.1-64bit

**Comment by windymilla** [comment]
Either something odd is happening, or you are mistaken. The link does go to the "Help with: guiguts" topic, number 11466.

Try exiting your browser and clicking the option in Guiguts again.

**Comment by okrick** [comment]
Closing and reopening Guiguts worked. 

This can be closed

**Comment by windymilla** [comment]
Agreed
