### ISSUE TITLE
Ctrl+f issue

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#687]
**Describe the bug**
If the Search Dialog window is on top of and smaller than the document window then the Search dialog disappears after the ctrl+f key is pressed.  Only the document window is visible. Yet the Search dialog is on the far left when I press alt-tab which means it should be in the foreground. The document window despite being visible is not in the foreground since a keypress will not enter a character or move the cursor.  

Only if the document window is smaller than the full screen and the search dialog is outside the boundary of the document window will the search dialog still be visible.

**To Reproduce**
1. Open Guiguts
2. Open the Search=>Search & Replace menu ...
3. Enter a search term
4. Press ctrl+f
5. The Search dialog vanishes and only the document window is visible.

**Expected behavior**
I expect the document screen to move to the search result with highlighting and the Search & Replace dialog to always have the foreground and be visible.  If I wanted to edit the item found then I would have used ctrl+g which opens the document screen in the foreground.

**Environment**
* Guiguts version:  1.3.0-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.32.1.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.32.1.1-64bit

**Additional context**
This is not new in this version.  It worked like this in 1.0.25.

**Comment by windymilla** [comment]
As you say, this is how Guiguts has always worked and was designed this way. Although some of the search/replace functionality is dated and/or idiosyncratic, I am not going to change it since all users are familiar with how it behaves.
