### ISSUE TITLE
Rewrap adds a blank line wherever there was a closing no-wrap marker

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#688]
GG-1.3_210331:

The title of this issue describes it.  The attached file has 11 pairs of no-wraps.  Five of them are followed by a chapter break (4 blank lines).  Before using "Rewrap All", there are no 5-blank line breaks and no 2-blank line Section breaks. After "Rewrap All", there are five 5-blank line breaks and six 2-blank line Section breaks.

This does not happen in GG-1.3.0-beta, but that version incorrectly rewrapped the first [Illustration] by indenting the second closing #/ and placing the closing right bracket after it, on the same line.  (That did not happen in GG-1.3_210331.)

Neither of these errors occurred in GG 1.2.4.

[rewrapbug.zip](https://github.com/DistributedProofreaders/guiguts/files/6254030/rewrapbug.zip)

**Comment by windymilla** [comment]
The first issue is already fixed by #685.
The second issue is now fixed by #689, although it is interesting to note that this block in a footnote breaks the "blank line after block markup" rule.
