### ISSUE TITLE
Add additional CP support to WF Character Count

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#691]
**Describe the solution you'd like**

1. Maintain a list of selected DP character suites that can be popped from the CP menu.
2. Option in CP menu to toggle highlighting of characters in WF Character Count that are not in the selected suites.
3. Allow suggestion of additional char suite to select, e.g. by Ctrl-clicking highlighted character in list. Maybe pops a OK/Cancel dialog asking "Add XYZ char suite to selected list?" if character is in a char suite. Pop warning "Character not in any known char suite" if not.

**Comment by mannyack** [comment]
This would require that guiguts has knowledge of the DP character suites. It would be nice to have that somewhat dynamic, i.e. keep local info regarding all known character suites, but have an automated way of updating the data automatically from the web-site when the user requests. The maintainers of the site would need to expose the character suites somehow. (I don't know if they have done that.)

**Comment by srjfoo** [comment]
Define "expose the character suites somehow"? They're in the code, which is available at github.

**Comment by windymilla** [comment]
I don't think the amount of use of the feature nor the low frequency of changes to the character suites would justify implementing a dynamic update. Much simpler and sufficient, IMO, would be to just issue a minor GG release to incorporate a new character suite.
