### ISSUE TITLE
Search & Replace dialog after Txt->Manually Convert Small Caps Markup

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#722]
**Describe the bug**
A minor issue. After closing the Txt>Manually Convert Small Caps Markup dialog and opening Search & Replace dialog, the latter presents with three, empty, Replacement Text entry fields open because 'multi' is still set. Clicking on the '-' radio button removes one of the three entry fields but no more. They are reduced to one, as expected, when you switch to 'single' from 'multi'.

**To Reproduce**
1. See description above.

**Expected behavior**
I expected that S & R would open with 'single' set and present just one Replacement Text entry field, just as it normally does when Txt>Manually Convert Small Caps Markup has not been run beforehand.

**Environment**
* Guiguts version:  At least 1.3.0 and 1.3.1-beta
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
I don't see a way to fix this that isn't much more trouble than is warranted by the seriousness of the problem. Not only is the multi flag set to be on, but Regex is also turned on. Note that right-clicking in the Word Frequency dialog pops the Search dialog and also forces Regex on; running a Scannos check either turns on Regex or Whole Word depending on the name of the scannos file; there may be other similar (ab)uses of the Search dialog. So I think this limitation will have to remain as it is for now (and always has been, at least for the last 10 years).
