### ISSUE TITLE
Tools->Check Orphaned Brackets->English Curly Quotes falsely flagging balanced double quotes

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#732]
**Describe the bug**
Tools->Check Orphaned Brackets->English Curly Quotes is falsely flagging balanced double quotes

**To Reproduce**
1. Open Guiguts with file [CQ-bug.txt](https://github.com/DistributedProofreaders/guiguts/files/6391590/CQ-bug.txt)
2. Open the Tools->Check Orphaned Brackets menu
3. Chose the 'English curly quotes' radio button
4. Scroll down to the 'Search' button and click that.
5. See error in which the two sets of opening double quotes on line 5 are highlighted incorrectly although the sets of opening/closing double quotes on that line are balanced.

**Expected behavior**
I expected no errors to be flagged but note 'Additional context' comments below that suggest this line is either difficult to correctly parse and convert or that there is also a related bug in the Curly Quotes conversion routine.

**Environment**
* Guiguts version:  1.2.4 and 1.3.1-beta at least
* Perl version: 
* Perl distribution: 

**Screenshots**
N/A

**Additional context**
This is not a contrived example but actual text from the project I am currently PPing. It should be noted that Txt->Convert to Curly Quotes also tripped up over the same line with '@@@' being displayed at the end of the line after conversion. Double quotes had to be flipped on the line to get a correct conversion to curly quotes.

**Comment by windymilla** [comment]
Sorry - this isn't possible to fix without massively increasing the sophistication of curly quote checking. I'm afraid we'll have to put up with the false positive in this case (basically open quote followed by open quote rather than close quote).
