### ISSUE TITLE
Enable multi-selection of pages in "configure page labels"

### ISSUE THREAD

**Issue by susanskinner** [DistributedProofreaders/guiguts#734]
**Enable simultaneous selection of multiple pages in "configure page labels"**
Enable to the user to select multiple pages at once in the configure page labels box so that the required action can be applied to them all simultaneously.

**Additional context**
I work on a lot of periodicals which have split proofing pages, meaning that I need to set every second page or so to "No Count". This previously required one click per change but now needs two. Similarly, some large reference work projects such as dictionaries also have split column pages and require a lot of adjustment of page labels. Having to move from the list to the top of the box and back to the list again is a lot slower than the previous one-click method (despite the overall functionality now being much faster and more reliable).

**Comment by windymilla** [comment]
By the way (unofficially) if I had a large book which followed a strict pattern of alternate pages throughout (or for long sections) I'd be strongly tempted to edit the .bin file and use a regex to change the label to no-count on odd (or even) numbered pages, but then again, I am lazy :)

**Comment by susanskinner** [comment]
I did not know about Ctrl-click but that does exactly what I need it to! (And I will now go RTFM to see what else I've missed :-))

**Comment by windymilla** [comment]
Top tip. Press F1 on your keyboard while a dialog is up to go straight to
the relevant manual page

>
>
