### ISSUE TITLE
Make px Default Geometry if Allow px Sizes for HTML is Enabled

### ISSUE THREAD

**Issue by tomcosnj** [DistributedProofreaders/guiguts#742]
Thanks for adding the option for PX.

However, although the user has enabled the use of PX (which implies that they would prefer that to be the default selection on the Image dialog), the Image dialog still has % as the default Geometry.

Therefore, an enhancement is requested so that if the user enables the use of pixels in the Image dialog that the default geometry be set to px.

**Comment by windymilla** [comment]
I didn't quite agree with your logic - there could be someone who uses percent for most images and pixels for decorations, etc.
I've therefore made it so it remembers the width type you used last, which should work for everyone.
