### ISSUE TITLE
Change to Info displayed in Spell Checker window

### ISSUE THREAD

**Issue by DP-SF2001** [DistributedProofreaders/guiguts#760]
Currently when spell checker finds something not in the dictionary it may show four different things after the "Not in Dictionary" message on the top line. It can be a mix of exact match, hyphenated match, different case match, and possessive.

Up to four numbers may appear above the current word:

1 number is just the number of occurrences (exact matches)
2 numbers mean number of occurrences and number of occurrences as part of a hyphenated word, e.g. "abc" twice and "abc-d" once would say "2, 1 hyphens in text"
3 numbers mean number of occurrences, number of occurrences with different case, e.g. "Abc", and number of possessives, e.g. "Abc's"
4 numbers mean occurrences, case, possessive, hyphen

It would be nice if some kind of comment field appeared under the count to explain what each of the numbers meant in any of the four situations above.

**Comment by windymilla** [comment]
Also a bug discovered. The above four numbers are not shown for the first spelling error, only subsequent ones.
