### ISSUE TITLE
Regex text replace with case change deletes trailing puctuation & space

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts#762]
**Describe the bug**
I am trying to restore small caps markup to a processed text file, using the Regex from [DP Regex Cookbook](https://www.pgdp.net/wiki/Regex_Cookbook#Change_ALL_CAPS_to_Small_Caps).
But although it includes trailing punctuation and space in the highlighted text, on replace it is deleted. I don't know if this is a Guiguts, Perl, or Regex issue, but it seems to me all text in the matched (highlighted) expression should be included in the "$1" replacement.
With 14,000 matches to go through (single initials match, unfortunately), this is a big problem.

**To Reproduce**
1. Create a text file with line: "20. ASIA, _Hist. Account of Discovery and Travels in_."
2. Search for "((\b(\p{IsUpper}+\W?\s?)\b)+)", Regex checked
3. "ASIA, " is highlighted
4. Enter replace text "<sc>\T$1\E</sc>"
5. Click Replace
6. Result: "20. <sc>Asia</sc>_Hist. Account of Discovery and Travels in_."
7. Comma and space are missing
8. Internal punctuation and spaces seem to be handled OK

**Expected behavior**
Trailing punctuation and space either not included in match, or included in replacement.

**Environment**
* Guiguts version: 1.3.1 standard zip install
* OS and version: Windows 10 Pro for Workstations 20H2 64-bit
* Perl version: 5.32.1001
* Perl distribution: Strawberry Perl 64-bit

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rtonsing** [comment]
That is better, thanks! Now after trying it, I see it would be better to exclude the trailing punctuation and/or space, most of the time, depending on context. I'll see if I can adjust the regex.

**Comment by windymilla** [comment]
See [this post](https://www.pgdp.net/phpBB3/viewtopic.php?f=13&t=11466&p=1247187#p1247187) for a probably-related regex bug.

**Comment by windymilla** [comment]
Limitation documented in Guiguts manual [here](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Searching#Limitations)
