### ISSUE TITLE
Stealth scanno error message

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#764]
Finished a stealth scanno pass using regex.rc, kept the S&R dialog on-screen, pressed F8, selected encommn.rc, got the Message Log pop-up shown below. Could not reproduce this when repeating the entire process, but didn't do "Next Occurrence" of the regex.rc's while doing so.  No files attached; if it happens again, I'll include files.

Using GG 1.3.1.  Had run "install_cpan_modules.pl" immediately after unzipping the installation download and before trying to use GG for the first time afterwards.  "install_cpan_modules.pl" did install some updates.

Here's the content of Message Log:

 Tk::__ANON__ at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 683
 Guiguts::SearchReplaceMenu::findascanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 534
 Guiguts::SearchReplaceMenu::getnextscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 1604
 Guiguts::SearchReplaceMenu::stealthscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/KeyBindings.pm line 42
 Guiguts::KeyBindings::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 424
 (eval) at C:/Strawberry/perl/site/lib/Tk.pm line 424
 Tk::MainLoop at D:\Documents\DistrProof\PP\GG 1.3.1\guiguts.pl line 378
 Tk::die_with_trace at C:/Strawberry/perl/site/lib/Tk.pm line 488
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 Guiguts::SearchReplaceMenu::findascanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 683
 Guiguts::SearchReplaceMenu::getnextscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 534
 Guiguts::SearchReplaceMenu::stealthscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 1604
 Guiguts::KeyBindings::__ANON__ at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/KeyBindings.pm line 42
 <Key-F8>
 (command bound to event)

**Comment by charliehoward4dp** [comment]
This happened again, with a different project. This time, it does seem to be reproduceable, at least when I immediately reselected en-common.rc. However, when I closed/reopened GG, starting regex.rc and then immediately switching to en-commn.rc succeeded with no error message.  Finished the regex.rc pass and selected en-commn.rc; the errorlog appeared immediately, and the S&R dialog is on-screen but empty.  I'll attach associated files in a zip.  Please note that both the regex.rc and en-commn.rc files in that zip are customized, not the distributed ones. the project files (t11-stealth.txt and t11-stealth.txt.bin) were saved after the regex.rc pass  Here's the error log:

 Tk::__ANON__ at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 683
 Guiguts::SearchReplaceMenu::findascanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 534
 Guiguts::SearchReplaceMenu::getnextscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 1604
 Guiguts::SearchReplaceMenu::stealthscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/KeyBindings.pm line 42
 Guiguts::KeyBindings::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 424
 (eval) at C:/Strawberry/perl/site/lib/Tk.pm line 424
 Tk::MainLoop at D:\Documents\DistrProof\PP\GG 1.3.1\guiguts.pl line 378
 Tk::die_with_trace at C:/Strawberry/perl/site/lib/Tk.pm line 488
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 Guiguts::SearchReplaceMenu::findascanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 683
 Guiguts::SearchReplaceMenu::getnextscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 534
 Guiguts::SearchReplaceMenu::stealthscanno at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/SearchReplaceMenu.pm line 1604
 Guiguts::KeyBindings::__ANON__ at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/KeyBindings.pm line 42
 <Key-F8>
 (command bound to event)

[stealthbug.zip](https://github.com/DistributedProofreaders/guiguts/files/6577260/stealthbug.zip)

**Comment by windymilla** [comment]
It's actually the Hint dialog that's causing the issue. When F8 is used, the first thing it does is delete the S&R dialog, which also deletes the Hint dialog but doesn't realise it has. So after loading the first regex it tries to display something in the hint dialog, thinking it is still open - bang!

**Comment by charliehoward4dp** [comment]
Easy to workaround, thanks.

**Comment by windymilla** [comment]
Should be fixed by my latest commit anyway - so will be OK in next version
