### ISSUE TITLE
Identify words with characters from incompatible Character Suites

### ISSUE THREAD

**Issue by mannyack** [DistributedProofreaders/guiguts#768]
I would like to see a new button on the Word Frequency function, called something like “Mixed Suites”. This button would create a list of all words in the document with characters from incompatible Character Suites. (This list should normally be null.) 

Basic Greek and Polytonic Greek are compatible. Basic Latin and any or all of the Extended European Latin suites are compatible. However, characters from any of the Latin suites should not appear in the same word as character(s) from the Greek character suites.

I am not sufficiently familiar with the other character suites to know their compatibility profiles. The best person to discuss that with would be Andrew (bunny-crunch).

**Comment by windymilla** [comment]
This looks feasible at first glance. 

Note to developer:
@srjfoo stated [here](https://www.pgdp.net/phpBB3/viewtopic.php?p=1248009#p1248009) that mixed script words are flagged by the DP code, so it would be worth looking at the logic used there to see if it is transferrable to GG.

**Comment by mannyack** [comment]
So far we have the following character suites:

Latin group: Basic Latin, Extended European Latin A, Extended European Latin B, Extended European C, Medievalist supplement, Semitic and Indic transcriptions

Greek group: Basic Greek, Polytonic Greek

Cyrillic: (imminent)

Symbols: Symbols collection.

If we define that character suites within the same group listed above are compatible (and otherwise not), that would might do it. I have a question in to Andrew about whether he thinks that the various extensions of Latin are compatible with each other.

As defined so far, this would be great for CP, however PP can intentionally introduce characters that are not in any of the DP character suites. For PP we need a more generalized tool that ignores DP character suites and looks at the [Script](https://en.wikipedia.org/wiki/Unicode_character_property#Script) associated  with each code point, and ensures that all the code points within a word have the same “script”. 

That Wikipedia article also discusses characters that are labelled <not a character> and deprecated code points. These should throw an error of some type, possibly make them incompatible with everything, even themselves.

**Comment by mannyack** [comment]
Andrew replied that he thinks that script is the way to go, not character suite, even for CP.

**Comment by windymilla** [comment]
Sorry, I don't think this is worth the coding effort. GG does not currently access the "script" so the info isn't immediately available. I don't think it would often find anything during PP, particularly as the Word Frequency Character Counts are always used to check which characters are in the file. If you're willing, please close this, or alternative you can try to make a stronger case for the work to be done.

**Comment by mannyack** [comment]
As Nigel feels it is not worth it, I am closing this issue.
