### ISSUE TITLE
Tk::Error: Failed to AUTOLOAD 'Tk::Frame::yview' when using the mouse wheel in Unicode Character Search

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/guiguts#77]
I am getting the following error when I use the mouse wheel to scroll in the Unicode Character Search dialog:
```
Tk::Error: Failed to AUTOLOAD 'Tk::Frame::yview' at /Users/cpeel/git/guiguts/src/lib/Guiguts/Utilities.pm line 577.
 Carp::croak at /usr/local/Cellar/perl/5.30.3/lib/perl5/5.30.3/Carp.pm line 291
 Tk::Widget::__ANON__ at /usr/local/Cellar/perl/5.30.3/lib/perl5/site_perl/5.30.3/darwin-thread-multi-2level/Tk/Widget.pm line 347
 Guiguts::Utilities::__ANON__ at /Users/cpeel/git/guiguts/src/lib/Guiguts/Utilities.pm line 577
 <Button-5>
 (command bound to event)
```

To reproduce this:
1. Open Guiguts
2. Open the Unicode Character Search dialog (Tools -> Character Tools -> UTF Character Search)
3. Search for a character (eg: `latin b`)
4. Scroll the dialog using the touchpad

Env:
* Platform: macOS 10.15.5
* Perl: v5.30.3 via homebrew
* Guiguts: pre-release 1.1.0 (commit f3f37c3f)

I'm able to scroll with the mouse wheel in the main window just fine. It doesn't appear(?) to use the BindMouseWheel function so perhaps this function is no longer needed?

Aside: The "UTF Character Search" menu item should probably be renamed "Unicode Character Search". The "UTF Character Entry" menu doesn't match the dialog name that opens up -- both of which should probably be "Unicode Character Entry".

**Comment by windymilla** [comment]
I can't see the bug as it is occurring in platform-specific (non-Windows) code. However, I do see the scroll wheel doesn't work like it does in the main window (and in the gutcheck window, which seems to also call BindMouseWheel, but doesn't actually need it to work).

**Comment by windymilla** [comment]
I see the same behaviour (scroll wheel not working) in 1.0.25. It would be interesting to know if the Tk error was also happening in 1.0.25. I suspect so, but maybe not - maybe due to a change of Perl interpreter/version. This dialog is probably not (heavily) used by (m)any users.

**Comment by cpeel** [comment]
I may futz around with it some and see if we can simply remove that function and have the dialogs that use it still work (at least on Mac). I don't think this is a ship-blocking issue.

**Comment by windymilla** [comment]
Agreed - thanks. I haven't looked in detail at what makes the GC error dialog scroll correctly (on WIndows). No doubt the mysteries will come to light at some point.

**Comment by windymilla** [comment]
Same error seen using GC error dialog, possibly using mouse wheel or right-clicking on errors?
```
Tk::Error: Failed to AUTOLOAD 'Tk::Frame::yview' at c:/DP/guiguts/src/lib/Guiguts/ErrorCheck.pm line 376.
```

**Comment by windymilla** [comment]
Potentially useful code from thundergnat [here](https://comp.lang.perl.tk.narkive.com/1DjuOEM0/tk-pane-yview)
```
The Pane doesn't seem to pass MouseWheel events to the apropriate
subwidget. Change the lines below to get it to work under Windows.
Not sure what changes, if any, may be necessary to get it to work
under Linux.
...
# [ sub { $_[0]->yview('scroll', -($_[1] / 120) * 3, 'units') },
# Ev('D') ]

[ sub {
if ($_[0]->isa('Tk::Frame') and ($_[0]->Parent)->isa('Tk::Pane')) {
$_[0] = $_[0]->Parent;
}
$_[0]->yview('scroll', -($_[1] / 120) * 3, 'units') },
Ev('D')]
```
