### ISSUE TITLE
Remove or improve "Enable Quotes Highlighting" on Preferences>Appearance menu

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#780]
Currently, when this option is enabled, modifying text in the main window highlights the ASCII quote marks (if any) on either side of the modification, but only if there are quotation marks within the modified line. IMO, this is worse than useless: useless because it only operates on a single line, which the user easily and more quickly can do visually; and worse than useless because it requires modifying what is most likely correct text, and therefore also requires undoing the modification, and doing so correctly.

Also, once the quote marks are highlighted, there's no straightforward way to remove the highlights: the actions that remove other kinds of highlighting don't work for this; neither does turning off the option on the Appearance sub-menu.  The only two ways I've found to remove these highlights are to close Guiguts or to modify a line that doesn't contain any quote marks (after unmodifying the highlighted line and then remembering to unmodify the second line.)

The easier choice would be to remove it from the menu without bothering to delete the code.  If it's kept, it should scan multiple lines in both directions until it finds a pair of quotation marks, and it should look for curly as well as straight quotes. (Ctrl+period already does all of this and Ctrl+zero removes those highlights.)  AND, it shouldn't be initiated by modifying the text. Shift-click, ctrl-click, or alt-click would be safer, if not already used for something else.  AND, there should be a straightforward way to unhighlight the quotes if it found any.  (Therefore, IMO, it should be removed from the menu.)

**Comment by windymilla** [comment]
See [this post](https://www.pgdp.net/phpBB3/viewtopic.php?f=13&t=11466&p=1250360#p1250360) for discussion/technical comment
