### ISSUE TITLE
Improve UI for improved quote highlighting feature

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#796]
**Describe the solution you'd like**

Suggested by @charliehoward4dp:

Not a bug, but IMO an inconvenient UI issue: the improvements to "Preferences>Appearance>Enable quotes/bracket highlighting" are nice, useful, and address the issues I reported, but: when the option is enabled, routine clicking in the text for any purpose initiates a quotes-search with highlighting.  Since clicking in the text for any purpose probably is the single most frequent thing anyone does with an editor, it shouldn't be so cumbersome to turn this highlighting feature on and off.

How about this, instead: since Ctrl+period is the keyboard shortcut for highlighting all double quotes within a selection, add a keyboard shortcut of Ctrl+colon to do what "Preferences>appearance>enable quotes/bracket highlighting" does, move that option to the Search menu, along with all the other highlighting options, and let Ctrl+0 turn off that highlighting, just as it turns off all the others?

An alternative would be to use something other than just clicking in the text to initiate highlighting when the option is enabled.  Maybe Ctrl+colon all by itself would work?

**Comment by windymilla** [comment]
I agree it seems cumbersome as it currently is. It isn't really the same as the other options in the Search menu (which actually has quote highlighting anyway) since they work in the selected text only. This option works anywhere in the file focused around the cursor position, and is most analogous to "Enable Scanno Highlighting". Some people might view that as a positive feature, that you can just turn it on and leave it on as you move around the file during certain phases of your work, rather than keep having to click/press to check the quotes in the surrounding area.

As well as being in the Prefs menu, "Enable Scanno Highlighting" has a status bar button "H", so is easy to turn on and off there. Maybe just a shortcut like Ctrl+(semi?)colon, as you suggest, so you don't have to go into the Prefs menu, and can click it on and off easily. I'm reluctant to put a "Q" button in the status bar for a relatively obscure feature. More thoughts welcome.

**Comment by charliehoward4dp** [comment]
Yes, after making this comment, I realized that colon requires a SHIFT, so the shortcut key should be Ctrl+semi-colon.  Let it remain where it is on the Preferences>Appearance menu, and the shortcut key doesn't enable/disable the option, but only functions when the option is enabled. Some alternative ways of using it:

1. Place cursor someplace and then Ctrl+;. Highlights remain on until the next Ctrl+; or the option is turned off;

2. Building on #1, Ctrl+0 turns off these highlights along with all other highlights that it turns off.  (But Ctrl+0 doesn't disable the option itself.)

AFAIK, there's no current use for Ctrl+; so someone could leave the menu option on permanently and only use the shortcut when needed.

**Comment by rtonsing** [comment]
I'm curious what the UI issue is here, are you seeing a long delay? I'm not, but my system is probably a lot faster than most. Maybe a half second to highlight/unhighlight when clicking a new spot.

**Comment by windymilla** [comment]
I think it's just the turning on and off that needs tackling. Since it is quite an intrusive feature, you probably wouldn't want it turned on the whole time. It should therefore be easier to turn it on & off, rather than going into a sublevel of the Prefs menu. I don't think there's an issue with delays - the routine runs every 400 milliseconds (like the scanno highlight routine) so you will always get a delay of up to that figure however fast your computer is. 
I think the consensus is probably just to add Ctrl+semicolon as a shortcut to toggle the Prefs option. Once it is in wider circulation, there may be more user feedback.
