### ISSUE TITLE
Add a "Count" function to the new right-click pop-up menu

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#810]
When processing proofer's notes, and occasionally at other times, it's often necessary to determine whether or not an odd spelling is a typo or the author's style.  Currently, the only practical ways to do this are to (1) search using a separate text editor (e.g., Notepad++ or another copy of GG) that has a copy of the project text and a "Count" function; or (2) to make the word (or phrase) the Search argument in GG, do the count, and then restore the Search argument for proofer's notes.  Both methods are awkward.

If the right-click pop-up menu had a simple (exact-match-only) "Count" option, it would offer a quicker and simpler way of getting the desired information. (The user would have to highlight what should be counted, as the [**note] search argument highlights too much.) This option could appear after "Paste", but it should NOT have a shortcut key:
  Cut
  Copy
  Paste
  Count
  Bookmarks

**Comment by windymilla** [comment]
I'm reluctant to add to the right click menu, as I am concerned it might lead to lots of requests for more entries, and the right click menu would get unwieldy. I've learned it's hard to remove things once they are added. 
Maybe a keyboard shortcut to a regular menu entry would be an alternative? 
Have you thought about where it would display the count?

**Comment by charliehoward4dp** [comment]
Something like "Quick Count" or "Frequency Count" on the SEARCH Menu would be fine, with a shortcut key of your choice. The result would be a pop-up message with the "OK" button highlighted as the Focus, so that pressing ENTER would get rid of it.  And yes, I can anticipate requests for embellishments, as I thought of some while making the request (should occurrences of "end" in "pending" be counted? No.)

**Comment by charliehoward4dp** [comment]
If this is implemented, I hope "keyboard shortcut" will be directly from the main text window, without having to open a primary menu first.

**Comment by windymilla** [comment]
Yes. Something related to the current search shortcuts but maybe with Alt or Shift held down
