### ISSUE TITLE
Retain status between GG invocations of the 'Unlimited Anchor Search' radio button in Footnote Fixup menu

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#813]
**Describe the solution you'd like**
Retain status between GG invocations of the 'Unlimited Anchor Search' radio button. At present its setting is only retained between runs of Footnote Fixup within the same GG invocation. If you quit GG and then restart, the 'Unlimited Anchor Search' radio button is reset to its default of 'unchecked'.

**Describe alternatives you've considered**
An alternative is to make 'Unlimited Anchor Search' the default when GG is started. However the consensus in the 'Help with: Guiguts' forum, such as it was at time of submitting this request, is against that. The responders are happier with the less risky compromise of making the setting by the user 'sticky' between invocations of GG.

**Additional context**
I routinely shut down GG at the end of each day. I am more than likely to load the same file when GG is restarted so that I can continue working from where I left off at the previous session. If I am trying to resolve issues with footnotes it can be easy to overlook the checking of 'Unlimited Anchor Search' again when GG is next restarted and Footnote Fixup rerun.

**Comment by windymilla** [comment]
In light of the forum discussion following [this post](https://www.pgdp.net/phpBB3/viewtopic.php?p=1254393#p1254393), the plan is to improve the wording in the Footnote Check dialog.
