### ISSUE TITLE
Re-running Word Frequency doesn't fully re-examine the text unless Guiguts is restarted

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#821]
In Word Frequency, "Check Spelling" found 10 occurrences of "Pskov" and one occurrence of "Pskow". I changed the latter to the former and after completing the spelling review, saved and re-ran Word Frequency using its "Rerun" button.  It reported 11 occurrences of "Pskov" (correctly) and one occurrence of "Pskow" (which no longer existed in the file).  I closed and reopened Word Frequency, but it still reported "Pskow".  Next, I saved the corrected text under a new name and, without closing Guiguts, reran Word Frequency, first with the "Rerun" button and then by closing/reopening the Tool.  In all cases, it still reported the now non-existent "Pskow". 

Only after closing and reopening Guiguts and then rerunning Word Frequency, did it no longer report "Pskow".

I don't know if this occurs with other Word Frequency tests or how important this is likely to be, but was able to reproduce it with this particular pair of words.

[wdfreq-bug.zip](https://github.com/DistributedProofreaders/guiguts/files/7035712/wdfreq-bug.zip)

**Comment by windymilla** [comment]
Bug has been there since at least 1.0.25 - the list of misspelt words was not being cleared when the Check Spellings button was clicked, so although new words could be added, and frequencies would be updated, old words would never be removed.
