### ISSUE TITLE
Non-fatal error message in MenuStructure.pm when saving a file

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#828]
When using "Save As...", this error message appears (but the save seems to have worked):

 10:38:46: Use of uninitialized value in concatenation (.) or string at D:/Documents/DistrProof/PP/GG 1.3.2/lib/Guiguts/MenuStructure.pm line 851.
10:44:43: Use of uninitialized value in concatenation (.) or string at D:/Documents/DistrProof/PP/GG 1.3.2/lib/Guiguts/MenuStructure.pm line 851.

It happened twice in a row, as seen in the message log.  The attached file is what was saved by the first occurrence, and it was modified afterwards, then saved under a new name, which produced the second message.

After composing this report, I closed GG, reopened it, set a bookmark, and did another Save As.  There were no messages this time, so you probably won't be able to use the files to recreate the error.

[saveasbug.zip](https://github.com/DistributedProofreaders/guiguts/files/7110274/saveasbug.zip)

**Comment by windymilla** [comment]
Had you done anything with your Custom Menu in the run of the program before the error (or perhaps in the previous run)?
Assuming you haven't got a modified MenuStructure.pm different to the released 1.3.2 version, that bit of code is building the Custom Menu. 
If you weren't doing anything to the Custom Menu, could you check that line 851 is in the menu_custom routine in your  MenuStructure.pm file.
Thanks

**Comment by charliehoward4dp** [comment]
Haven't changed Custom Menu in months. I did look at it recently, and that inevitably saves it even when there have been no changes.

The date on "MenuStructure.pm" is 8/18/2021 and line 851 is "map", which is in "custom_menu.

The error has not occurred since being reported.

**Comment by windymilla** [comment]
Sorry - unable to reproduce. Will close shortly, but can be re-opened or a fresh issue added if a reproducible error is found.

**Comment by windymilla** [comment]
Unable to reproduce
