### ISSUE TITLE
Spellcheck Dictionary Selection Tool - Doesn't Change Project Language

### ISSUE THREAD

**Issue by tomcosnj** [DistributedProofreaders/guiguts#833]
**Problem:** The "Spell Check Options" popup only seems to allow selection of ONE Dictionary. We SHOULD be able to select multiple Languages for the field titled "Current Dictionary (ies)" and have it set the Project Language to match. 

**Solution:** The list of Dictionaries should either allow several items to be selected or perhaps change to Check Boxes for each Language and allow multiple Languages to be selected.

Proposed Workflow:
1. Open Spellcheck.
2. Click on Options.
3. Select desired Dictionary for Project or to Add to Project.
4. Click OK.
5. Project's Language is updated.
6.  Spellcheck utilizes all of the chosen Dictionaries.

**Comment by windymilla** [comment]
Multiple language spellchecking is the solution to this issue.

**Comment by tomcosnj** [comment]
Okay! Thanks for your assistance!

Tom C
