### ISSUE TITLE
Malformed regex freezes Guiguts so it can't even be killed easily

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#835]
This malformed regex:

  id="i_(.+?)"((.|\n)+?)&lt;i&gt;Figure (\d+?)(a*?)/.&lt;/i&gt;

the error is that the forward slash / before the last period should be a backslash \\

causes Guiguts 1.3.2 to freeze in such a way that clicking the "X" box in the Windows Title line does nothing.  It can be killed by clicking the "X" box in the Perl Command-line window, but there's a delay before that happens.

**Comment by wf49670** [comment]
It looks like the parens are properly balanced to me, Charlie.  WaltOn Sep 21, 2021 12:55 AM, Charlie Howard ***@***.***> wrote:
This malformed regex:
id="i_(.+?)"((.|\n)+?)<i>Figure (\d+?)(a*?)/.</i>
(the / before the last period should be a ) causes Guiguts 1.3.2 to freeze in such a way that clicking the "X" box in the Windows Title line does nothing.  It can be killed by clicking the "X" box in the Perl Command-line window, but there's a delay before that happens.

**Comment by charliehoward4dp** [comment]
Github didn’t display what I typed: the malformation is not parentheses but a slash that should be a backslash, just before the final period. I need to add an escape in the form of a double backslash just for display purposes here.

**Comment by windymilla** [comment]
For future reference, you can use backquotes to encapsulate code/special characters so they doesn't get interpreted, e.g. if I use backquote, backslash, backquote, I get `\`

**Comment by srjfoo** [comment]
> For future reference, you can use backquotes to encapsulate code/special characters so they doesn't get interpreted, e.g. if I use backquote, backslash, backquote, I get `\`

You can also escape special characters with a backslash. I find that it helps me a lot to use the "Preview" tab if I know I'm using special characters or some kind of markup. It shows me what my comment will actually look like (and allows me to test links).

**Comment by windymilla** [comment]
I tried pasting that expression into the S&R dialog with Regex checked. When I searched, it didn't find any occurrences which isn't surprising, but it didn't lock up the system at all.

**Comment by charliehoward4dp** [comment]
Nigel explained that this is not a bug, but a performance issue that is a consequence of how some regexes are processed. Given enough time, this one finishes and Guiguts becomes responsive again. Thank you for investigating it thoroughly.
