### ISSUE TITLE
Hebrew ordering

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts#848]
Open Guiguts
Copy & paste this paragraph:

Andreae MÜLLERI, ‖ Greiffenhagii, ‖ DISQUISITIO ‖ Geographica &
Historica, ‖ De ‖ CHATAJA, ‖ In Quâ ‖ I. Praecipuè Geographorum nobilis
‖ illa Controversia: Quaenam CHATAJA sit, & an ‖ sit idem ille terrarum
tractus, quem Sinas, & vul-‖ gó Chinam vocant, aut pars ejus aliqua? ‖
latissimè tractatur; ‖ 2. Eâdem verò operâ pleraque rerum, quae unquam
‖ de Chataja, deq́ue Sinis memorabilia ‖ fuerunt, atque etiam nunc
sunt, compendiosè ‖ enarrantur. ‖—Ecclesiastae I. v. 15. ‖: לתסטת תסות
לא יוכל ‖ Senec. de Beneficiis VI. I. ‖ _Etiam quod discere supervacuum
est prodest_ ‖ cognoscere. ‖ —Berolini, Typis Rungianis. ‖ Anno M. DC.
LXX, 2 ff. not numbered + pp. 115 on 2 col.

Issue:
The ordering of the Hebrew starting line 7 does not match that displayed in Notepad++, VSCode, Firefox when I let it wrap the text, or even in this edit box. Each pair of words is reversed.

Update: it seems to depend on the font. Issue is in Source Code Pro, it is OK in Courier New. When I switch fonts I can see it change.

**Comment by windymilla** [comment]
I'm sorry - I don't think it will be possible for me to fix this, partly due to my ignorance, and partly due to Perl/Tk's poor support for left-right and right-left text. I'll wait a bit, then close this issue unless there's any brilliant solution suggested.

**Comment by rtonsing** [comment]
No problem, I can't even imagine why it would be an issue in one font and not another.

**Comment by windymilla** [comment]
As per discussion above
