### ISSUE TITLE
epubmaker and Nu Validators disagree about the "summary" attribute in <table>

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#876]
In GG 1.4.0-test1, The Nu HTML Validators say that the "summary" attribute in &lt;table&gt; is obsolete and should not be used. If that attribute is omitted, eBookMaker issues a warning that &lt;table&gt; lacks "summary" attribute, and this causes GG's Message Log to appear:

> 17:20:55: Beginning ebookmaker
> 17:20:55: Files will appear in the directory D:\Documents\DistrProof\PP\Active\609-sympathy\
> WARNING:root:No gnu dbm support found. Rhyming dictionary not used.
> INFO:root:Running html thru tidy.
> WARNING:root:tidy: line 583 column 1 - &lt;table&gt; lacks "summary" attribute
> WARNING:root:tidy: line 892 column 1 - &lt;table&gt; lacks "summary" attribute
> WARNING:root:tidy: line 6136 column 1 - &lt;table&gt; lacks "summary" attribute
> INFO:root:tidy: Document content looks like HTML Proprietary

It would be nicer for these two programs to agree, and for the Message Log to not pop up.

**Comment by windymilla** [comment]
Eric and I have identified some incompatibilities in the way that Tidy and ebookmaker interact. In current versions of ebookmaker, it uses Tidy to generate an intermediate file that ebookmaker then processes to create the epub file. However, the combination of XML, HTML4 and HTML5 is not being handled smoothly, leading to issues such as this one. There will be a new ebookmaker, perhaps in a month's time, that may not use Tidy (or may use it differently) and hopefully these problems will melt away :)
