### ISSUE TITLE
Unicode Character Search tool to show the ordinal as a decimal number as well as a hex number

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#879]
**Describe the solution you'd like**
With a couple of exceptions, HTML5 does not accept HTML character entities. They instead must be entered with their ordinal value expressed either in decimal (e.g. `&#65;`) or hexadecimal (e.g. `&#x0041;`).  However the Unicode Character Search tool currently only displays the ordinal as a hex value. It would be useful for displayed it as a decimal value as well. E.g. something like

     A   LATIN CAPITAL LETTER A - Hex 0041 Dec 65 - Basic Latin

**Describe alternatives you've considered**
If you want to insert ordinal values in decimal into an HTML5 file you need to look up the decimal value using a tool outside of GG or convert the hex value yourself that is displayed by Unicode Character Search tool.

**Additional context**

**Comment by windymilla** [comment]
Added backquotes (code markup) around the entity codes so they are not converted to the actual character.
