### ISSUE TITLE
Failure in Footnotes Fixup First Pass

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts#885]
**Describe the bug**
14:28:47: Use of uninitialized value in concatenation (.) or string at C:/guiguts/lib/Guiguts/Footnotes.pm line 606.
14:28:47: Use of uninitialized value in string eq at C:/guiguts/lib/Guiguts/Footnotes.pm line 608.
14:28:47: Use of uninitialized value in string eq at C:/guiguts/lib/Guiguts/Footnotes.pm line 608.
14:28:48: Tk::Error: bad text index "" at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .frame.linenumbertext.frame.textunicode
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 Tk::Derived::Delegate at C:/Strawberry/perl/site/lib/Tk/Derived.pm line 469
 Tk::Widget::__ANON__ at C:/Strawberry/perl/site/lib/Tk/Widget.pm line 322
 Guiguts::Footnotes::fnview at C:/guiguts/lib/Guiguts/Footnotes.pm line 614
 Guiguts::Footnotes::__ANON__ at C:/guiguts/lib/Guiguts/Footnotes.pm line 47
 Tk callback for .toplevel3.frame.button2
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 Tk::Button::butUp at C:/Strawberry/perl/site/lib/Tk/Button.pm line 175
 <ButtonRelease-1>
 (command bound to event)
14:29:40: Tk::Error: Unmatched [ in regex; marked by <-- HERE in m/(?<!/[*#Ii])\[[ <-- HERE \]/ at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .frame.linenumbertext.frame.textunicode
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 Tk::Derived::Delegate at C:/Strawberry/perl/site/lib/Tk/Derived.pm line 469
 Tk::Widget::__ANON__ at C:/Strawberry/perl/site/lib/Tk/Widget.pm line 322
 Guiguts::Footnotes::footnotefixup at C:/guiguts/lib/Guiguts/Footnotes.pm line 791
 Guiguts::Footnotes::fnfirstpass at C:/guiguts/lib/Guiguts/Footnotes.pm line 356
 Guiguts::Footnotes::__ANON__ at C:/guiguts/lib/Guiguts/Footnotes.pm line 34
 Tk callback for .toplevel7.frame.button
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 Tk::Button::butUp at C:/Strawberry/perl/site/lib/Tk/Button.pm line 175
 <ButtonRelease-1>
 (command bound to event)

**To Reproduce**
1. Open Guiguts with file
2. Open Footnote Fixup
3. Run First Pass

**Expected behavior**
Summary showing any footnotes issues found

**Environment**
Guiguts, Version: 1.3.3
Platform: MSWin32
Microsoft Windows [Version 10.0.22000.376]
Perl v5.32.1
Aspell 0.50.3
perl/Tk Version: 804.036
Tk patchLevel: 8.4
Tk libraries: C:/Strawberry/perl/site/lib/Tk

**Additional context**
File has a large number of footnotes ("[Footnote" found 1591 times). 
Check Orphaned Brackets finds no unmatched brackets
If issue is in file, I can't tell how to find it.
Will supply file on request.

**Comment by windymilla** [comment]
Yes, please - definitely upload the file for me here, please

**Comment by rtonsing** [comment]
Thanks,
- Robert 

    On Sunday, January 2, 2022, 02:51:06 PM CST, Nigel ***@***.***> wrote:  
 
 


Yes, please - definitely upload the file for me here, please

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by windymilla** [comment]
Hi Robert - I can't see a link to the file - did you upload it? I notice you replied by email to Github. It's possible you can't upload a file like when you add a comment using that method, but you can go the website and drag the file onto a new comment, and it will put a link in the comment. Thanks

**Comment by rtonsing** [comment]
[fossilplants2.zip](https://github.com/DistributedProofreaders/guiguts/files/7802993/fossilplants2.zip)

**Comment by windymilla** [comment]
Just FYI, so you can fix it, the faulty footnote is at line 7009:
`[Footnote 1 Seward and Hill (00).]`
There is no colon after the number 1. I will investigate why that leads to the error you saw, rather than a useful error, but at least you can correct it in your text file.

**Comment by windymilla** [comment]
Actually, clicking Check Footnotes gives you a good clue as to where it is - if you scroll to the bottom of the list that pops up, you can see the final one is faulty, and the line number of the last good footnote (6986) tells you where to start looking.

**Comment by windymilla** [comment]
If you'd like to test out the fix, this [Footnotes.zip](https://github.com/DistributedProofreaders/guiguts/files/7803169/Footnotes.zip) contains a new Footnotes.pm file which you can put in the lib/Guiguts folder.

**Comment by rtonsing** [comment]
Very good. No error, but it flags the line. Thanks!

**Comment by windymilla** [comment]
Thanks - will put the fix in, ready for the next release
