### ISSUE TITLE
Inconsistent convertion of superscript inside /* */

### ISSUE THREAD

**Issue by jandac-2020** [DistributedProofreaders/guiguts#892]
GG correctly converts abc^x and abc^{xy} in normal text paragraphs.

However inside a nowrap section /* */ it converts some superscripts but not all of them.
In the attached file (pre-generation) there are 28 caret elements.
After generation (I used the default header file) 11 were converted correctly, and 17 were left unchanged.

I have also seen the case (but not with this test file) where an element such as abc^{xy} was converted, but incorrectly,  to abcxy.

I suspect this issue was present in 1.0.25, but I don't have that on my system anymore.

**To Reproduce**
1. Load the attached file gg-caret test.txt into Guiguts
2. Open the HTML Generator menu, and run generation.
3. Search for ^ and `<sup>`

**Expected behavior**
All caret elements should be converted to <sup>xx</sup>

**Environment**
* Guiguts version:  1.3.3
* OS and version:  Windows 10
* Perl version: 
* Perl distribution: Strawberry
* 
[gg-caret test.txt](https://github.com/DistributedProofreaders/guiguts/files/7916789/gg-caret.test.txt)

**Comment by jandac-2020** [comment]
I hope my post makes sense... github interpreted my text < sup > [no spaces] as a command and not my text.
JohnC

**Comment by windymilla** [comment]
Thanks - I'll look into it. For future reference, you can type backquotes to surround code, e.g. \`\<sup>\`, or the Insert Code button (above where you type - it looks like `<>`), or Ctrl-e is a keyboard shortcut. You can also use Preview (above where you type) to check it has had the desired effect.

**Comment by windymilla** [comment]
I found the bug. @jandac-2020 was right that it has been there for a long time - surprising that it hadn't been found previously.
Quick summary - the routine doing the superscript conversion forgot to tell the code that does the block conversion that it had made a change to the line, so the old line with the DP markup could get re-inserted back into the file. Thanks for the report.
This change will be in release 1.4.x - contact me by PM if you need the fix urgently.
