### ISSUE TITLE
headerdefault.txt minor suggestion

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts#897]
**Describe the bug**
In the line 
`<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="BOOKLANG" lang="BOOKLANG">`
I don't think the "xml:lang" attribute is needed in an HTML5 document. But I'm only gradually learning HTML5 parsing.

http://www.html-5.com/attributes/xml-attributes.htm:
	"The HTML lang attribute serves the same purpose as the xml:lang attribute and should be used instead."

Python html5lib parser returns warning:
	html5lib\_ihatexml.py:266: DataLossWarning: Coercing non-XML name: xml:lang

**Comment by windymilla** [comment]
Discussion [here](https://www.pgdp.net/phpBB3/viewtopic.php?p=1269645#p1269645)

**Comment by windymilla** [comment]
Following on from the above discussion, and Eric's [comment](https://www.pgdp.net/phpBB3/viewtopic.php?p=1269730#p1269730) that ebookmaker will ensure both `xml:lang` and `lang` are present in the posted file, it seems it is best to retain both in the Guiguts output.

**Comment by rtonsing** [comment]
Agreed.
