### ISSUE TITLE
Simple regex Rpl All seems to go into a loop in the patched 1.4.0 test version

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#904]
When the following regex is used in a Rpl All on the attached file, GG 1.4-test3 seems to go into a loop-like state, deleting one character at a time (or none).  It doesn't happen with single/manual S&R's, and didn't happen in the past.  I suspect the "recent" patch associated with "Rpl All" is the cause (I made the patch by editing "SearchReplaceMenu.pm" according to instructions.)

Here's the regex:
  S:  \\[Blank Page]\\n

The Replace term is null. The regex is just supposed to delete lines containing [Blank Page]
[regex_bug.zip](https://github.com/DistributedProofreaders/guiguts/files/8310257/regex_bug.zip)

EDIT: The backslashes were there, but Github originally didn't display them. This edit doubled them so they now show.

**Comment by windymilla** [comment]
Shouldn't there be backslashes to escape the square brackets, otherwise
it's deleting all those letters individually
