### ISSUE TITLE
Ability to Suppress ID Tag in Image Generation

### ISSUE THREAD

**Issue by tomcosnj** [DistributedProofreaders/guiguts#914]
**Allow Suppression of the ID Tag**
When the user utilizes the Image popup Tool, an id="img_name" is automatically added to the generated HTML Code. For insertion of decorative elements (for example bar_dot.png) which may occur multiple times in a volume, this leads to errors when trying to insert hyperlinks. An error message "More than one instance of the anchor bar_dot in text." Therefore, if the Image Tool had a checkbox which would allow the user to suppress the insertion of the ID tag, this problem can be avoided. The default would be to ENABLE this feature each time Guiguts is run but by unchecking it, the user can temporarily disable its insertion.

**Two Alternatives Found**
Once you finish inserting the first instance of the decorative element, the user would remove the id tag. The user would Copy the HTML. Then, at every instance where the image is to be inserted. Paste in the modified HTML. The other alternative would be to use Search/Replace to locate the id="bar_dot" and Replace with an empty string.

**Comment by windymilla** [comment]
Alternative: when there is already a "bar_dot" id, for example, then next time of trying to add bar_dot.png, add an id "bar_dot2". If that already exists, then try bar_dot3, etc.
