### ISSUE TITLE
The View in Browser radio button on the HTML Generator menu produces misleading output in the browser window

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#915]
**Describe the bug**
The **View in Browser** radio button on the **HTML Generator** menu produces misleading output in the browser window it opens. Instead of displaying the result of the HTML autogeneration it instead displays the file _before_ it was converted to HTML. In order to display the generated HTML you have to first Save it in GG then refresh the browser window that GG opened.

**To Reproduce**
1. Open Guiguts with 
[bug-report.txt](https://github.com/DistributedProofreaders/guiguts/files/8505426/bug-report.txt)

2. Save As bug-report.html
3. HTML->HTML Generator->View in Browser
4. See displayed content in the browser window just opened by GG

**Expected behavior**
When I clicked the Autogenerate HTML radio button then the View in Browser radio button, I naively expected to see displayed in a browser window the result of the HTML just generated. I instead see the text before HTML autogeneration was applied. The display in the browser window makes it look like the HTML is in some way faulty.

**Environment**
* Guiguts version: 1.3.3 (and earlier I suspect), 1.4-test3 (with new HTMLConvert.pm)
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
Both the "View in browser" buttons (HTMLGenerator dialog and the first entry in the Custom menu) open the latest saved version of the currently loaded file from the disk, not an unsaved version in the GG window. 

Under Windows, it uses the "start" command, which actually launches the default app given the files extension. For example, if you do it to a ".txt" file, it starts Notepad (may depend on your version of Windows), and it you do it to an HTML file, it starts your default browser. I think Mac & some Linux systems use "open" instead of "start", or the user has to manually set up the command that gets run.

I'm not sure it's worth saving what's in the GG window to a temporary file, then starting the browser on that, especially as that could break the way the one in the Custom menu works (using $d$f$e to concatenate the directory, filename and extension). One option would be to check if the file has been edited since it was last saved (which it would be if Autogenerate had ben run) and either force a save with no warning (not nice, although Word Frequency does it) or it could pop up an error, saying "Save file before trying to view it". Another option would be to add a note to the relevant manual page to explain what "View in browser" actually does.

Any thoughts?

**Comment by G4OEU** [comment]
Placing that "View in Browser" button right next to the "Autogenerate HTML" button implies that what you will be viewing is the HTML that was just generated. If it does not do that then it seems to me the button is misleading, serves little purpose, and ought to be removed.

If the button is to be kept then GG needs to either save to the file that is open in the GG window or save to a temporary file then display that in the browser window. I agree with you that the latter is probably not the way to go for the reasons you give.

That leaves saving to to the file that is open in the GG window then displaying those contents.  So if a save is needed why not say that on the button label? Something like "Save File and View in Browser"?

The button will now do something useful and the label is self-documenting. No pop up warning about a save is needed. It is much safer than keeping the current button label but relying on a paragraph in the GG Manual explaining that "View in Browser" saves before displaying the contents of the file in a browser window.

The button label saying "Save File and View in Browser" would also mirror the steps I currently do:

1.     Load file.html (produced when the common file is split into .txt and .html versions)
2.     HTML->HTML Generator->Autogenerate HTML
3.     Close HTML Generator menu
4.     File->Save (more usually CTRL/S)
5.     Custom->View in browser
6.     [Then an ongoing series of edits, etc., of the file until the HTML displays as required.]

You will see from steps 3. & 4. that I have never before used the "View in Browser" button on that menu!

**Comment by windymilla** [comment]
Yes - "Save & View in Browser" or something similar seems like an improvement.

**Comment by srjfoo** [comment]
I discovered well before DP that I couldn't display an HTML file in a browser unless I'd saved it (before I knew anything like GG existed, and didn't even have a "view in browser" button).

However ... this goes back to the "Undo" function. What if the change I make is large, but turns out to be wrong. In other word processing/text editing programs, I can Undo back past the previous save if it was wrong. In GG, I can't.

So, yes, it make sense to have a saved file to display in the browser. The browser doesn't know about changes that haven't been saved, because the changes aren't on the disk for the browser to see. Losing Undo may not be of concern to regular GG users, if they're used to not having it past the most recent save, but I thought I'd mention it.

**Comment by G4OEU** [comment]
Sharon, I note your point about "Undo" but this is a very particular situation. The "Undo" function is not relevant in the HTML Generator menu. You have opened this menu to do a very specific and necessary task; namely autogenerating the HTML and then seeing how it appears in a browser.

If you think about the processing steps involved, a trusted program (GG) is going to do a huge labour-saving job for you in creating the _initial_ HTML version of the transcript. It will be correct HTML but of course is unlikely to be optimal and will need tweaking. And it is in all those _subsequent_ steps (done over over hours/days) of editing and adjusting the HTML that the "Undo" function is needed in GG. It's just not needed after autogenerate->save->display in browser. That is a one-off task.

And if you don't trust GG to generate correct HTML here then you can always keep a backup copy of the file you are about to convert to HTML. In fact in most processing work flows, that backup is 'automatic' as the common file from which you split the initial TEXT and HTML files can simply be used to recreate the HTML file again in the unlikely event that autogenerate went awry.

**Comment by G4OEU** [comment]
Sharon, I misread your response above so have withdrawn my reply (which you will have in any case seen in an email). If I read your post correctly, you seem to be addressing a more general problem/feature of GG, rather than the proposed solution to the specific problem I raised in this Github issue?

**Comment by srjfoo** [comment]
> Sharon, I misread your response above so have withdrawn my reply (which you will have in any case seen in an email). If I read your post correctly, you seem to be addressing a more general problem/feature of GG, rather than the proposed solution to the specific problem I raised in this Github issue?

Quentin -- yes, the point I was trying to make was a more general one. After any save, you lose the undo history. (I was just being my usual over-explaining the issue thing.)

I also acknowledge that those who use GG for the specific purpose of PP at DP may not be bothered by that, but I felt like it was worth mentioning. I know from the previous discussions that it's not an easy issue to fix, or Nigel would have fixed it already.

**Comment by G4OEU** [comment]
Sharon, thanks for the reply.  I understand your point now. 

And yes, DPers I know who routinely use GG for PPing will always "Save a Copy As" before committing any major changes to disk. It is an automatic action for us! 

I was a programmer in my professional life. None of the text editors I routinely used during that time (one of which I still use) had an ability to restore a file from before the last save. So I feel quite comfortable with the limitations of GG in this area because that is the way I always had to work when editing files! But I do appreciate that others who are used to a different text editing environment would wish GG to be more like the editors they know.

But in the context of the particular problem for which I opened this Github issue, the assertion I made in my original reply to you still holds. There is no need for an "Undo" mechanism in the HTML Generator menu changes proposed here. I suspect we probably can both agree on that?

The user is trusting GG's Autogenerate HTML to make a specific set of changes to the file which will result in correct initial HTML. It is a one-off task and there is no way to avoid that initial 'Save & Display in Browser' step.

What is initially produced and saved may not be optimal and do all that you want but it will be _correct_ HTML so the 'save' is safe. That saved file will be the starting point of what will eventually become the HTML that is uploaded to PG.

**Comment by srjfoo** [comment]
> Sharon, thanks for the reply. I understand your point now.
> 
> I was a programmer in my professional life. None of the text editors I routinely used during that time (one of which I still use) had an ability to restore a file from before the last save. ...

Wow! I routinely use vim, and it will undo past the last save. I honestly didn't realize there were text editors that didn't, other than GG.

> But in the context of the particular problem for which I opened this Github issue, the assertion I made in my original reply to you still holds. There is no need for an "Undo" mechanism in the HTML Generator menu changes proposed here. I suspect we probably can both agree on that?
> 
> The user is trusting GG's Autogenerate HTML to make a specific set of changes to the file which will result in correct initial HTML. It is a one-off task and there is no way to avoid that initial 'Save & Display in Browser' step.
> 
> What is initially produced and saved may not be optimal and do all that you want but it will be _correct_ HTML so the 'save' is safe. That saved file will be the starting point of what will eventually become the HTML that is uploaded to PG.

As you describe it, I definitely agree that in this context, the save is appropriate and the undo would not be useful.

**Comment by windymilla** [comment]
Reviewing this discussion, Quentin's earlier comment "If the button is to be kept then GG needs to..." made me think that it would perhaps be best to remove the button. The option "View in browser" appears at the top of the Custom Menu, where it can be used multiple times during the HTML generation, tweaking and testing. I don't think that button belongs in the Autogenerate dialog at all.
