### ISSUE TITLE
Make Stealth Scannos operate like other tools

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#919]
Other tools work by creating a log of errors and displaying them with line numbers, e.g. bookloupe.
Consider doing the same for Stealth Scannos.

Points to consider:
1. May be better to order by scanno, rather than primarily by line number
2. [These python files](https://github.com/DistributedProofreaders/guiguts/files/8550257/ppscannos1r103.zip) might be useful 
3. [This wiki page may be useful](https://www.pgdp.net/wiki/PPTools/Ppscannos1)
4. A similar issue has been entered for spellchecking - #916

**Comment by charliehoward4dp** [comment]
The current Stealth lists are user-editable. Would the enhanced version still allow user customization and hints?

**Comment by windymilla** [comment]
I don't think the task would be worth doing if there isn't a way to incorporate customisation and hints, but I haven't thought about how that could work.

The proposed version wouldn't support "previous" since I don't think there would a concept of next and previous scannos. Similarly, search backwards isn't used in that way of working, since all the "errors" are listed in the error dialog.

It may be that there's not a good way of doing this for scannos, but it was suggested after someone saw the issue to implement a different spellcheck mechanism. Whether a new way is implemented or not, there are no plans to remove the old way.

**Comment by charliehoward4dp** [comment]
`It may be that there's not a good way of doing this for scannos, but it was suggested after someone saw the issue to implement a different spellcheck mechanism. Whether a new way is implemented or not, there are no plans to remove the old way.`

(_Sigh of relief._)  I can go very quickly through Scannos, knowing I can go backwards once a potential error registers (in what remains of my mind).  The standard tools' method of right-click to delete and see next is somewhat slower, and the only way to be able to go back without restarting the tool is to left-click each item and keep it on the screen ... which is even slower.

**Comment by windymilla** [comment]
Sorry - unable to find a good way to achieve this, certainly within a reasonable timeframe.

**Comment by charliehoward4dp** [comment]
Glad to know Stealth will stay the way it is.
