### ISSUE TITLE
Copy-paste error in GG 14.0.0

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#930]
When text containing curly quotes is copied from a GG window containing the Plain Text version of a document, to a separate GG window containing the HTML version, the curly quotes transform into other, non-utf8 characters. The attached files will demonstrate this. The text to copy is at the very end, in the Transcriber's Notes, and snippets below also demonstrate this, step-by-step.  BTW, this error did not occur when each of the first two copied notes (for Page 7 and Page 15) was copied "live" yesterday, but it is happening now in today's test.

Pasting the same snippet into this Github window, or Notepad, or Notepad++ all work properly.

The GG documentation [HERE](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Edit_Menu#Copy_and_Paste_Between_Documents_and_Programs) discusses copy/paste issues but doesn't mention this one, and I don't recall encountering it before.  As mentioned above, it didn't necessarily happen last night, either.

Here are the last few lines of the Plain Text:
```
“Johnnisfeuer” may be a misspelling for “Johannisfeuer.”

Page 7: “a chilly, waspish pig” was printed that way, but it may be
a misprint for “a chilly, waspish prig”.

Page 15: “Dr. Jekyl and Mr. Hyde” was printed that way, but it is a
misprint for “Dr. Jekyll and Mr. Hyde”.

Pages 49 and 98: “The Admirable Bashville, or Constancy Rewarded”
was printed that way, but is a misprint for “The Admirable Bashville,
or Constancy Unrewarded”.
```

Here are the last few lines of the HTML, before copy-paste is done:

```
<p>“Johnnisfeuer” may be a misspelling for “Johannisfeuer.”</p>
</div></div>

</body>
</html>
```

This is what I copied from the Plain Text window (started right after the period that ended the previous paragraph):

```

Pages 49 and 98: “The Admirable Bashville, or Constancy Rewarded”
was printed that way, but is a misprint for “The Admirable Bashville,
or Constancy Unrewarded”.
```

This is how the new last few lines of the HTML looked after the copied text was pasted (started right after the &lt;/p&gt; that ended the previous paragraph, and some invisible added characters appear here on my screen as hollow rectangles; but the curlies are gone and an "â" followed by two hollow rectangles are in their place):

```
<p>“Johnnisfeuer” may be a misspelling for “Johannisfeuer.”</p>

Pages 49 and 98: âThe Admirable Bashville, or Constancy Rewardedâ
was printed that way, but is a misprint for âThe Admirable Bashville,
or Constancy Unrewardedâ.
</div></div>
```
[copypastebug.zip](https://github.com/DistributedProofreaders/guiguts/files/8710643/copypastebug.zip)

**Comment by windymilla** [comment]
I understand it might be difficult for you to reproduce this, but if you can, could you try "Alternative Paste" from the Edit Menu, or Ctrl-Alt-V. You have described this in the manual [here](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Edit_Menu#Type.2C_Cut.2C_Copy.2C_Paste).

It definitely looks like a Unicode encoding issue, which is what prompted the Alternative Paste feature - it seems to fail somehow internally within the Perl/Tk code, so I didn't have any way to fix it. We can't use Alternative Paste all the time because that sometimes crashes IIRC.

If it does look like that issue, and you think it is documented OK in the manual, then I'm afraid we'll probably have to close this.

**Comment by charliehoward4dp** [comment]
I will update the section of documentation I referenced in the report so that it suggests Alternate Paste. That’s probably where it should have been in the first place, so now it’ll be in both places.

**Comment by windymilla** [comment]
Thanks
