### ISSUE TITLE
Change to invitation label in ctrl+alt+h popup (highlight arbitrary characters in selection)

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#933]
**Describe the solution you'd like**
I take things too literally. So when I tried out the ctrl+alt+h keyboard shortcut, which invited me to "Highlight Character(s) or Regex", I entered the two characters **[** and **{** in order to highlight both "[" and "{" characters in the file. However nothing happened. I had assumed that "Highlight Character(s)" meant that I could type in two or more characters into the input field then click on Exact>Select Whole File>Apply Highlights and both those characters would be highlighted.

On reflection I realised that to highlight more than one character at the same time then I needed to use a Regex and to click on "Regex" rather than "Exact". The header text mislead me.

**Describe alternatives you've considered**
In order to avoid literalists like me being mislead by the invitation in the popup it should be recast to say something like "Highlight Character or Characters in Regex".

The word "Character(s)" is not necessary in the recasting above. The rewritten invitation now means highlight the single character that was input for an _exact_ match or the multiple characters in the _regex_ match. Note that you would not use a regex unless you wanted to highlight more than one character, hence the reference in the recast invitation to "Characters in the Regex". 

**Additional context**

**Comment by windymilla** [comment]
Entering the characters `[{` does have a meaning, and potential value: it means highlight occurrences of `[{`, i.e. where both brackets appear consecutively. That exact string might not be useful, but other strings could be.

The [manual ](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Navigation#Highlight_Arbitrary_Characters_in_Selection)says

> The command Highlight arbitrary characters... opens a dialog in which you can specify any of:
> - A single special character, for example an ampersand
> - A literal string, for example :=
> - A regular expression that selects various characters or a class of characters

So, the manual does make it clear that you enter a single character, or several characters, or a regex.

Again, this is an old feature, and I assume is mostly used (if at all) for finding single characters, which is probably how the button text came about. I don't think your suggested change would be accurate, given the possibility of entering several characters, but I'm open to changing the button if people think it needs clarifying.

**Comment by G4OEU** [comment]
I agree that the manual page describes this clearly. My comment in another issue about a shortcut entry in the Help Menu linking to a fuller description elsewhere in the manual applies here too.

Perhaps it would be more accurate if the popup text and hotkeys.txt file entry said something like "Highlight Character, Literal String or Characters in Regex"? That could be shortened to "Highlight Literal String or Characters in Regex"

**Comment by windymilla** [comment]
I don't really agree with "... Characters in regex". It doesn't have to be just multiple untie characters, like "[abc]" I don't think. How about "Highlight Character, String or Regex" ?

**Comment by G4OEU** [comment]
That is a neater recasting.
