### ISSUE TITLE
A simple edit that works in 1.3 does not work correctly in 1.4

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#940]
**Describe the bug**
Selecting text over two lines by dragging the cursor then replacing that selected text by a single character no longer works as expected on 1.4

**To Reproduce**
1. Open Guiguts with file [bug-report-04.txt](https://github.com/DistributedProofreaders/guiguts/files/8817573/bug-report-04.txt)
2. Position cursor at start of Ln 14
3. Drag cursor down to next line to include the '#' character (but not the following `/` character). This selects the blank Ln 14 and the `#` character at the start of Ln 15.
4. Replace the selected text with `$`. What happens in 1.4 is that Ln 14 remains blank and Ln 15 has ` #$` starting in column 0.

**Expected behavior**
The purpose of the edit is to have `$/` at the start of Ln 14 to close the rewrap markers for the paragraph.

**Environment**
* Guiguts version: 1.4.0-test4 [still haven't replaced it with the public 1.4.0 install!]
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**
[bug-report-04.txt](https://github.com/DistributedProofreaders/guiguts/files/8817573/bug-report-04.txt)

**Additional context**
This edit works as expected in 1.3.

**Comment by windymilla** [comment]
> Guiguts version: 1.4.0-test4 [still haven't replaced it with the public 1.4.0 install!]
This might be the issue - it works OK for me in the 1.4.0 release.
Possibly a file I sent you to test something has caused the bug - I'd be surprised if the official 1.4.0 was different in a significant way like that.
I think the only way to check is for you to try the official release - sorry!

**Comment by G4OEU** [comment]
Installing the official 1.4.0 fixes the problem. I should have done this earlier I suppose!
