### ISSUE TITLE
Add utf8-friendly spellcheck

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#95]
Platform: Windows

Aspell for Windows does not recognise utf8 characters.
See #94 for related bug with curly apostrophes.

**Comment by cpeel** [comment]
[aspell 0.5](http://aspell.net/win32/) is the latest version for Windows and it is not fully-UTF-8 compliant.

**Comment by windymilla** [comment]
Consider using Hunspell instead of Aspell. It is used by LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird.
See [Hunspell website](http://hunspell.github.io/)
Also see [Perl interface to Hunspell](https://metacpan.org/pod/release/ELEONORA/text_hunspell_1.2/Hunspell.pm)

**Comment by cpeel** [comment]
I would be very interested in any Hunspell research you do to see if it would be a good replacement for WordCheck and/or ppwb.

**Comment by windymilla** [comment]
No luck wrestling unicode input, output to/from Hunspell - abandoning for now.

**Comment by windymilla** [comment]
Will resurrect this at some point if the problem of utf-8 compliant pipe communication between GG and Hunspell can be resolved.
