### ISSUE TITLE
Make it easier to transfer settings from an old release

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#954]
Maybe it could check if the current release has a setting.rc file (early on).
If not, it could pop a dialog to browse for an old release to get settings from - cancel to avoid doing this.
Alternatively, ask first "Do you want to copy settings from an previously installed GG release?"
As it copies them across, it could make any necessary changes between releases.

**Comment by tangledhelix** [comment]
Have you considered having a pairing of files, one global, one a user-override? I'll explain what I mean by that:

- Ship `setting.rc` with Guiguts, which is meant to be static, and only includes the default value for each setting
- Guiguts doesn't edit `setting.rc` when the user changes settings
- If the user changes any setting from the default, `setting-user.rc` is created and the value is stored there
- Perhaps `setting-user.rc` could be stored in the user's home directory, not in the app directory
- On startup, first load `setting.rc`, then load `setting-user.rc` - most things would be default values, but `setting-user.rc` would override some values

I am thinking ahead here to what I would desire if I continue with my own project to create a Mac app bundle. The way a Mac app bundle works is that it's a (static) bundle of files. It's arranged in a directory tree, but in a special format that the OS considers to be an "app" and treats as one object you can drag around, launch, delete... but it's not supposed to contain any changing parts, because the app must be signed. So in that model, you would always want the contents of the app directory to be static, and any user settings to be in another file. In macOS, the settings files can either live in a Library directory in $HOME or they can be unix-style dotfiles... but the important thing is they are not a part of the application as-shipped.

So, this idea would become important in a Mac app, but I can see the value to separate these two layers in all situations, on all platforms, because the current upgrade handling of setting.rc can be non-intuitive for users (IMHO).

I'd be willing to look at creating a PR to implement this, if the idea seems reasonable to you.

**Comment by windymilla** [comment]
That's an interesting idea with some definite benefits. Here are a few thoughts:

1. I don't think there would be any point in having a static `setting.rc` with default values. This is because `setting.rc` is not currently shipped with the code - all the default values are in the main Perl code (variables generally need initialising anyway, and `setting.rc` is just a bit of Perl code that gets run, setting the value of some of those variables). Guiguts writes `setting.rc` during your first run of the program. So I think equivalent to what you're suggesting would be to simply write `setting.rc` outside the release, e.g. the user's home directory, instead of inside the release.
2.  Many (most?) Windows users would have no idea what you mean by "your home directory". Settings files are not generally saved there under Windows, apart from some Linux-derived tools - On the work computer I use, I have .cpanm, .idlerc, .gitconfig, etc in my home directory (a network drive `H:\`) but also some similar things in my other home directory (`C:\Users\myname`). In the GitBash shell, `echo $HOME` returns `/h/`. Due to work, my setup is a little unusual, but you can see that Windows is weird. Some programs do store settings in some subfolder of the home directory, often a hidden folder, or maybe in the Windows registry - again a complete mystery to most users. This means that they wouldn't know where the file was if they did need to access it for any reason (e.g. they get a new computer) and/or could potentially delete it if they saw it lying around and didn't know it was a vital part of their GG release.
3. It was obviously historically tricky to handle some changes (e.g. changing a dialog from non-resizable to resizable or vice versa) since these have needed different variables saving in the `setting.rc`, which then caused issues if the `setting.rc` from an old release is read into a new release. After I took over supporting GG, I had to recommend people start with a fresh `setting.rc` when moving between certain releases. Future coding could probably be organised to avoid this type of issue, but there are still little special cases in the code to trap and fix some of these. Since some people (not just devs) run more than one release concurrently, it would also have to cope somehow with forwards/backwards compatibility if it's going to run smoothly.
4. In fact, most of these settings don't matter too much if they get changed/lost. Not many settings get changed by users, especially since the relatively recent change to make most file paths (e.g. for bookloupe) relative to the release directory. You could actually argue that some of the settings should be static and not allow the user to change them at all - bookloupe location would be one of those.

Just some thoughts - not trying to dismiss the idea at all

**Comment by tangledhelix** [comment]
> So I think equivalent to what you're suggesting would be to simply write `setting.rc` outside the release, e.g. the user's home directory, instead of inside the release.

The idea in my head was actually to only write out any individual settings that were *not* the default value... not necessarily the entire file. But, either could work. For my purposes with a Mac app, the important thing is that there is no changing file inside the application itself; it must be somewhere else.

> Many (most?) Windows users would have no idea what you mean by "your home directory".

I realized after my last reply that I would have no idea how to do this on Windows. I don't have any Windows computers to develop with, either. My offer to tinker on code and make a PR still stands, but I can only make it work on macOS and Linux/Unix. I'd have to leave the Windows code path for you, but hopefully it could work the same way, just with a different path.

**Comment by rtonsing** [comment]
If you do this, I recommend using a "Guiguts" folder under the environment variable %HOMEPATH% and the Documents folder: "%HOMEPATH%\Documents", which translates to "C:\Users\(username)\Documents", and shows up as shortcut "Documents" in File Explorer in Win 10/11. This makes finding the settings file easy to find for editing.

Alternatively you could use %LOCALAPPDATA%, but I think that is more for files that the user does not look for directly.

Either way it would have the advantage of not overwriting the file when unzipping a new version.

**Comment by windymilla** [comment]
@tangledhelix - thanks Dan. If you'd like to tinker and make a PR, you'd be very welcome. Having had a quick look in the code, I see there is already something that attempts to get the home directory (should be in a platform-independent way). See [here].(https://github.com/DistributedProofreaders/guiguts/blob/9b2cb199c10a6f4f00351dbba8feb038c0adec62/src/lib/Guiguts/Utilities.pm#L1139) 
I hope that means you would be able to code it in a way that would work on all platforms - I'm very happy to test on Windows of course.

Robert's idea of making a Guiguts subfolder there makes sense because there are also some files in the Guiguts data subfolder that get created by GG when the release is run, e.g. how to translate words like FOOTNOTES. They get copied from a default one to the one that gets used. The user can customize them, or create a new one for a language that isn't currently supported. So either under this issue or a fresh one, those files should be dealt with too.

**Comment by tangledhelix** [comment]
> This makes finding the settings file easy to find for editing.

I agree with that point, but I'll also point out that Guiguts is an editor, so another option we have is to add a menu item that will open the settings file for editing. That seems even easier than expecting users to find the file on their own.

**Comment by windymilla** [comment]
> > This makes finding the settings file easy to find for editing.
> 
> I agree with that point, but I'll also point out that Guiguts is an editor, so another option we have is to add a menu item that will open the settings file for editing. That seems even easier than expecting users to find the file on their own.

Various menu items edit that file, in effect, so probably no need for an entry to edit the file. It shouldn't be necessary for anyone to manually edit, but you know how things are - some people need to occasionally, but it's probably best not to encourage it.

**Comment by charliehoward4dp** [comment]
A file such as "setting.rc" in a common folder would [adversely] affect those of us who go back and forth between multiple versions of Guiguts. I do this routinely when testing pre-releases, and occasionally when checking to see whether what appears to be a bug in a production release was present in earlier releases.

**Comment by tangledhelix** [comment]
> A file such as "setting.rc" in a common folder would [adversely] affect those of us who go back and forth between multiple versions of Guiguts.

I see your concern, but a case like this could be solved by specifying a path to Guiguts "home" at runtime, e.g.

```
perl guiguts.pl --home $PWD
```

while leaving the default at a global directory. For the majority of users, and for non-testing runs even for you, you can use the global default and not worry about it. But for testing cases such as you describe, it gives you an override control to specify where setting.rc (and the other "user" files) are written. Or, I guess a user who really really doesn't like the global idea could always use this flag if that's what they prefer.

If that isn't acceptable to the devs, I could solve the problem I'm working on for my macOS app by checking the app launch path and only specifying a global settings path if Guiguts is running from the app path, leaving any other use of Guiguts with the current behavior unchanged.

**Comment by tangledhelix** [comment]
I've been thinking about this and I don't like the idea of changing default behavior.

I'll try to implement `--home <path>` as an optional flag. My macOS app can use it, and anybody else could choose to. Most users would not be disrupted.

This also means that Guiguts doesn't need to be "smart" and intuit the correct path to use.

**Comment by tangledhelix** [comment]
Reference to PR: #958
