### ISSUE TITLE
Crash when saving new file immediately after opening GG

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#960]
**Describe the bug**
Opening GG and using Save sometimes generates a Bus error or Segmentation fault on Macs and crashes silently on Windows

**To Reproduce**
1. Open Guiguts
2. Use File--> Save
3. Type new filename, e.g. `abc.txt`

**Comment by srjfoo** [comment]
I don't know if this is useful information or not, but ... I've tested it on two MacBook Pros, both running Monterey (macOS 12.4). One is an M1 Mac, the other is an Intel Mac. Both have been updated to XQuartz 2.8.2
