### ISSUE TITLE
Focus repeatedly switches to image viewer when Auto Img is turned on

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#98]
Platform: Windows
Perl version: Strawberry Perl v5.30.2
Guiguts version: 1.1.0
Viewer: XnView

To reproduce:
1. Load file into GG which has page scans
2. Turn on Auto Img in the status bar (and select page scans folder if needed)
3. In main window, use arrow keys to scroll down
4. When cursor crosses page boundary, new page image appears in viewer and focus moves to viewer
5. User has to click in GG again to continue editing or searching

Make focus stay in text window - possibly with option to turn feature on/off

**Comment by srjfoo** [comment]
Note that it's not just a Windows issue, but also a Mac issue that the focus changes from GG to the image viewer (my experience is with Preview) upon crossing a page boundary.
